// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { ApolloOutputConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Apollo tools ──────────────────────────────────────────────

/**
 * Enrich a person via Apollo.io by Apollo ID, email, or name plus company domain. Returns contact details, seniority, location, and employer firmographics. Consumes one Apollo export credit per successful match.
 */
export interface ApolloEnrichPersonParams {
    /**
     * Apollo person ID, e.g. from apollo_search_people results. The most reliable match key.
     */
    id?: string | null
    /**
     * The person's email address.
     */
    email?: string | null
    /**
     * The person's first name.
     */
    firstName?: string | null
    /**
     * The person's last name.
     */
    lastName?: string | null
    /**
     * The person's full name, if first/last are not known separately.
     */
    name?: string | null
    /**
     * The person's employer domain, without www or @ (e.g. acme.com).
     */
    domain?: string | null
    /**
     * The person's employer name.
     */
    organizationName?: string | null
    /**
     * The person's LinkedIn profile URL.
     */
    linkedinUrl?: string | null
    /**
     * Also return personal emails (may consume extra credits; suppressed for people in GDPR regions). Default false.
     */
    revealPersonalEmails?: boolean | null
}

export interface ApolloEnrichPersonResult {
    success: boolean
    actions?: RunHistoryAction[]
    found: boolean
    person: {
        id: string
        firstName: string | null
        lastName: string | null
        name: string | null
        title: string | null
        seniority: string | null
        email: string | null
        emailStatus: string | null
        linkedinUrl: string | null
        city: string | null
        state: string | null
        country: string | null
        organization: {
            id: string | null
            name: string | null
            websiteUrl: string | null
            primaryDomain: string | null
            industry: string | null
            estimatedNumEmployees: number | null
        } | null
    } | null
}

/**
 * Enrich up to 10 people in a single Apollo.io call, using the same match keys as apollo_enrich_person. Consumes one Apollo export credit per matched person. Prefer this over repeated apollo_enrich_person calls for lists.
 */
export interface ApolloBulkEnrichPeopleParams {
    /**
     * Up to 10 people to enrich (Apollo's bulk_match limit). Each entry needs at least one match key (id, email, or name + domain).
     */
    people: {
        /**
         * Apollo person ID, e.g. from apollo_search_people results. The most reliable match key.
         */
        id?: string | null
        /**
         * The person's email address.
         */
        email?: string | null
        /**
         * The person's first name.
         */
        firstName?: string | null
        /**
         * The person's last name.
         */
        lastName?: string | null
        /**
         * The person's full name, if first/last are not known separately.
         */
        name?: string | null
        /**
         * The person's employer domain, without www or @ (e.g. acme.com).
         */
        domain?: string | null
        /**
         * The person's employer name.
         */
        organizationName?: string | null
        /**
         * The person's LinkedIn profile URL.
         */
        linkedinUrl?: string | null
    }[]
    /**
     * Also return personal emails (may consume extra credits; suppressed for people in GDPR regions). Default false.
     */
    revealPersonalEmails?: boolean | null
}

export interface ApolloBulkEnrichPeopleResult {
    success: boolean
    actions?: RunHistoryAction[]
    matches: {
        id: string
        firstName: string | null
        lastName: string | null
        name: string | null
        title: string | null
        seniority: string | null
        email: string | null
        emailStatus: string | null
        linkedinUrl: string | null
        city: string | null
        state: string | null
        country: string | null
        organization: {
            id: string | null
            name: string | null
            websiteUrl: string | null
            primaryDomain: string | null
            industry: string | null
            estimatedNumEmployees: number | null
        } | null
    }[]
    matchedCount: number
    requestedCount: number
}

/**
 * Enrich a company via Apollo.io by domain. Returns firmographics: industry, headcount, revenue, funding, location, keywords, and technologies. Consumes one Apollo export credit per matched company.
 */
export interface ApolloEnrichOrganizationParams {
    /**
     * The company domain to enrich, without www or @ (e.g. acme.com).
     */
    domain: string
}

export interface ApolloEnrichOrganizationResult {
    success: boolean
    actions?: RunHistoryAction[]
    found: boolean
    organization: {
        id: string | null
        name: string | null
        websiteUrl: string | null
        primaryDomain: string | null
        industry: string | null
        estimatedNumEmployees: number | null
        keywords: string[]
        annualRevenuePrinted: string | null
        totalFundingPrinted: string | null
        latestFundingStage: string | null
        foundedYear: number | null
        city: string | null
        state: string | null
        country: string | null
        linkedinUrl: string | null
        shortDescription: string | null
        technologyNames: string[]
    } | null
}

/**
 * Search Apollo.io for people by title, seniority, location, company domain, and headcount filters to build prospect lists. Consumes no credits but requires the connected key to be an Apollo master API key. Results never include emails — pass result ids to apollo_bulk_enrich_people to unlock contact data.
 */
export interface ApolloSearchPeopleParams {
    /**
     * Job titles to match, e.g. ["Head of Marketing", "DevRel"].
     */
    personTitles?: string[] | null
    /**
     * Whether to also match titles similar to personTitles. Default true.
     */
    includeSimilarTitles?: boolean | null
    /**
     * Seniorities to match: owner, founder, c_suite, partner, vp, head, director, manager, senior, entry, intern.
     */
    personSeniorities?: string[] | null
    /**
     * Person locations, e.g. ["New York, US", "Germany"].
     */
    personLocations?: string[] | null
    /**
     * Company HQ locations.
     */
    organizationLocations?: string[] | null
    /**
     * Company domains to search within, without www or @.
     */
    organizationDomains?: string[] | null
    /**
     * Headcount ranges as "min,max" strings, e.g. ["11,50", "51,200"].
     */
    organizationNumEmployeesRanges?: string[] | null
    /**
     * Free-text keywords to narrow results.
     */
    keywords?: string | null
    /**
     * Filter by email status: verified, unverified, likely to engage, unavailable.
     */
    contactEmailStatus?: string[] | null
    /**
     * Result page to fetch. Default 1.
     */
    page?: number | null
    /**
     * Results per page, 1-100. Default 25.
     */
    perPage?: number | null
}

export interface ApolloSearchPeopleResult {
    success: boolean
    actions?: RunHistoryAction[]
    people: {
        id: string
        firstName: string | null
        lastName: string | null
        name: string | null
        title: string | null
        hasEmail: boolean | null
        linkedinUrl: string | null
        city: string | null
        state: string | null
        country: string | null
        organization: {
            id: string | null
            name: string | null
            websiteUrl: string | null
            primaryDomain: string | null
            industry: string | null
            estimatedNumEmployees: number | null
        } | null
    }[]
    totalEntries: number
    page: number
    perPage: number
}

/**
 * List active job postings at a company via Apollo.io, as a hiring signal (open roles, titles, locations, posted dates). Takes the Apollo organization ID from apollo_enrich_organization. Works with any Apollo key (no master key needed) but consumes Apollo credits per page of results returned — fetch one large page instead of paging in small steps. Postings include title/url/location metadata only, not full descriptions; assess role fit from the title.
 */
export interface ApolloListJobPostingsParams {
    /**
     * The Apollo organization ID to list job postings for, e.g. the id returned by apollo_enrich_organization or in apollo_search_people results.
     */
    organizationId: string
    /**
     * Result page to fetch. Default 1.
     */
    page?: number | null
    /**
     * Results per page, 1-500. Default 100. Apollo charges per page returned, so prefer one large page over many small ones.
     */
    perPage?: number | null
}

export interface ApolloListJobPostingsResult {
    success: boolean
    actions?: RunHistoryAction[]
    postings: {
        id: string
        title: string | null
        url: string | null
        city: string | null
        state: string | null
        country: string | null
        postedAt: string | null
        lastSeenAt: string | null
    }[]
    totalPostings: number
    page: number
    perPage: number
}

export type ApolloGeneratedTools = {
    /** Enrich a person via Apollo.io by Apollo ID, email, or name plus company domain. Returns contact details, seniority, location, and employer firmographics. Consumes one Apollo export credit per successful match. */
    enrichPerson(params: ApolloEnrichPersonParams): Promise<ApolloEnrichPersonResult>
    /** Enrich up to 10 people in a single Apollo.io call, using the same match keys as apollo_enrich_person. Consumes one Apollo export credit per matched person. Prefer this over repeated apollo_enrich_person calls for lists. */
    bulkEnrichPeople(params: ApolloBulkEnrichPeopleParams): Promise<ApolloBulkEnrichPeopleResult>
    /** Enrich a company via Apollo.io by domain. Returns firmographics: industry, headcount, revenue, funding, location, keywords, and technologies. Consumes one Apollo export credit per matched company. */
    enrichOrganization(params: ApolloEnrichOrganizationParams): Promise<ApolloEnrichOrganizationResult>
    /** Search Apollo.io for people by title, seniority, location, company domain, and headcount filters to build prospect lists. Consumes no credits but requires the connected key to be an Apollo master API key. Results never include emails — pass result ids to apollo_bulk_enrich_people to unlock contact data. */
    searchPeople(params: ApolloSearchPeopleParams): Promise<ApolloSearchPeopleResult>
    /** List active job postings at a company via Apollo.io, as a hiring signal (open roles, titles, locations, posted dates). Takes the Apollo organization ID from apollo_enrich_organization. Works with any Apollo key (no master key needed) but consumes Apollo credits per page of results returned — fetch one large page instead of paging in small steps. Postings include title/url/location metadata only, not full descriptions; assess role fit from the title. */
    listJobPostings(params: ApolloListJobPostingsParams): Promise<ApolloListJobPostingsResult>
}

export const apolloTools: ApolloGeneratedTools = {
    enrichPerson: (params: ApolloEnrichPersonParams) =>
        TerseAgent.executeTool<ApolloEnrichPersonResult>("apollo_enrich_person", { ...(params), integrationId: "cmrpdyr8a0007mc2ayq8hc6e1" }),
    bulkEnrichPeople: (params: ApolloBulkEnrichPeopleParams) =>
        TerseAgent.executeTool<ApolloBulkEnrichPeopleResult>("apollo_bulk_enrich_people", { ...(params), integrationId: "cmrpdyr8a0007mc2ayq8hc6e1" }),
    enrichOrganization: (params: ApolloEnrichOrganizationParams) =>
        TerseAgent.executeTool<ApolloEnrichOrganizationResult>("apollo_enrich_organization", { ...(params), integrationId: "cmrpdyr8a0007mc2ayq8hc6e1" }),
    searchPeople: (params: ApolloSearchPeopleParams) =>
        TerseAgent.executeTool<ApolloSearchPeopleResult>("apollo_search_people", { ...(params), integrationId: "cmrpdyr8a0007mc2ayq8hc6e1" }),
    listJobPostings: (params: ApolloListJobPostingsParams) =>
        TerseAgent.executeTool<ApolloListJobPostingsResult>("apollo_list_job_postings", { ...(params), integrationId: "cmrpdyr8a0007mc2ayq8hc6e1" }),
}

// ── Apollo skill ──────────────────────────────────────────────

/** Apollo — enrich people and companies and search for prospects. Enrichment consumes Apollo export credits; search is credit-free but requires a master API key. */
export function apolloSkill(): TypedSkill<"apollo_bulk_enrich_people" | "apollo_enrich_organization" | "apollo_enrich_person"> {
    return new ApolloOutputConfig("cmrpdyr8a0007mc2ayq8hc6e1")
}