// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    AttioOutputConfig,
    TerseAgent,
    TypedSkill,
    registerEventTransform,
} from "terse-sdk"
import { AttioObject } from "./attio.schemas.js"
import type { AttioSelectOption, GeneratedAttioObject, GeneratedAttioList, AttioRecordBase, AttioRecordsResult, AttioWorkspaceMembersResult, AttioTasksOutput, AttioNotesOutput, AttioCommentsOutput, AttioListsResult, AttioMeetingsOutput, AttioFilesOutput, AttioSchemaOutput, AttioListWorkspaceMembersParams, AttioGetWorkspaceMemberParams, AttioListTasksParams, AttioGetTaskParams, AttioCreateTaskParams, AttioUpdateTaskParams, AttioDeleteTaskParams, AttioListNotesParams, AttioGetNoteParams, AttioCreateNoteParams, AttioDeleteNoteParams, AttioGetCommentParams, AttioListThreadsParams, AttioGetThreadParams, AttioCreateCommentParams, AttioDeleteCommentParams, AttioCreateListParams, AttioListMeetingsParams, AttioGetMeetingParams, AttioListCallRecordingsParams, AttioGetCallTranscriptParams, AttioListFilesParams, AttioGetFileParams, AttioGetFileDownloadUrlParams, AttioUploadFileParams, AttioDeleteFileParams, AttioListObjectsParams, AttioGetObjectParams, AttioListAttributesParams, AttioListStatusesParams, AttioListSelectOptionsParams, AttioCreateObjectParams, AttioUpdateObjectParams, AttioCreateAttributeParams, AttioUpdateAttributeParams, AttioCreateStatusParams, AttioUpdateStatusParams, AttioCreateSelectOptionParams, AttioUpdateSelectOptionParams, __AttioRecordWithValues, AttioRecordValuesFor, AttioAttributeSlug, AttioRecordFor, AttioQueryRecordsParams, AttioSearchRecordsParams, AttioGetRecordParams, AttioCreateRecordParams, AttioUpdateRecordParams, AttioUpsertRecordParams, AttioDeleteRecordParams, AttioGetAttributeHistoryParams, AttioQueryRecordsResult, AttioSearchRecordsResult, AttioUpsertRecordResult, AttioSingleRecordResult, AttioEntryValuesFor, AttioEntryFilterFor, AttioListEntryFor, AttioListEntriesResult, AttioListEntryResult, __AttioSingleValue, AttioAttributeHistoryResult } from "./attio.schemas.js"

// ── Attio tools ───────────────────────────────────────────────

export type AttioGeneratedTools = {
    /** List records of an object, with optional filtering and limit/offset pagination. */
    queryRecords<TObject extends GeneratedAttioObject>(params: AttioQueryRecordsParams<TObject>): Promise<AttioQueryRecordsResult<TObject>>
    /** Fuzzy-search records following Attio's in-product matching: names/domains/emails/phones on people and companies, the record label on other objects (e.g. deal names). Query with a distinctive substring of the target; extra tokens that are not in the record's name can prevent matches. Results are eventually consistent (a just-created record may not be indexed yet) — use 'query' for read-after-write. */
    searchRecords<TObject extends GeneratedAttioObject>(params: AttioSearchRecordsParams<TObject>): Promise<AttioSearchRecordsResult>
    /** Fetch a single record by its ID. */
    getRecord<TObject extends GeneratedAttioObject>(params: AttioGetRecordParams<TObject>): Promise<AttioSingleRecordResult<TObject>>
    /** Fetch the historic values of one attribute on a record (e.g. every stage a deal has been in). */
    getAttributeHistory<TObject extends GeneratedAttioObject, TAttr extends AttioAttributeSlug<TObject>>(params: AttioGetAttributeHistoryParams<TObject> & { attribute: TAttr }): Promise<AttioAttributeHistoryResult<__AttioSingleValue<NonNullable<AttioRecordValuesFor<TObject>[TAttr & keyof AttioRecordValuesFor<TObject>]>>>>
    /** Create a new record in Attio. Unlike attio_upsert_record, no matching attribute is needed, so this works for objects without a unique writable attribute (e.g. deals). */
    createRecord<TObject extends GeneratedAttioObject>(params: AttioCreateRecordParams<TObject>): Promise<AttioSingleRecordResult<TObject>>
    /** Update an existing Attio record by its ID. Only the attributes present in 'values' are touched; multiselectMode 'append' adds to multi-value attributes instead of overwriting them. */
    updateRecord<TObject extends GeneratedAttioObject>(params: AttioUpdateRecordParams<TObject>): Promise<AttioSingleRecordResult<TObject>>
    /** Create or update one or more Attio records, matched on a unique writable attribute (e.g. 'email_addresses' for people, 'domains' for companies). If a match is found the record is updated, otherwise a new one is created. Throws if ANY record in the batch fails, naming each failure; earlier records may already be written (upserts are safe to retry). */
    upsertRecord<TObject extends GeneratedAttioObject>(params: AttioUpsertRecordParams<TObject>): Promise<AttioUpsertRecordResult<TObject>>
    /** Permanently delete an Attio record by its ID. This cannot be undone. */
    deleteRecord<TObject extends GeneratedAttioObject>(params: AttioDeleteRecordParams<TObject>): Promise<void>
    /** List every workspace member (name, email address, access level). Use to resolve a record's owner to a person, or to find the ID/email to write into an actor-reference attribute. */
    listWorkspaceMembers(params?: AttioListWorkspaceMembersParams): Promise<{ members: NonNullable<AttioWorkspaceMembersResult["members"]>; count: number }>
    /** Fetch a single workspace member by ID (e.g. the referenced_actor_id of a record's owner value). */
    getWorkspaceMember(params: AttioGetWorkspaceMemberParams): Promise<NonNullable<AttioWorkspaceMembersResult["member"]>>
    /** List tasks, optionally filtered by linked record, assignee or completion state. */
    listTasks(params?: AttioListTasksParams): Promise<{ tasks: NonNullable<AttioTasksOutput["tasks"]>; count: number }>
    /** Fetch a single task by ID. */
    getTask(params: AttioGetTaskParams): Promise<NonNullable<AttioTasksOutput["task"]>>
    /** Create an Attio task: content (plaintext) plus optional deadline, assignees (workspace-member emails or IDs) and linked records. */
    createTask(params: AttioCreateTaskParams): Promise<NonNullable<AttioTasksOutput["task"]>>
    /** Update an Attio task's deadline, completion state, assignees or linked records. Task content cannot be changed. */
    updateTask(params: AttioUpdateTaskParams): Promise<NonNullable<AttioTasksOutput["task"]>>
    /** Permanently delete an Attio task. */
    deleteTask(params: AttioDeleteTaskParams): Promise<void>
    /** List notes, optionally scoped to one record. */
    listNotes(params?: AttioListNotesParams): Promise<{ notes: NonNullable<AttioNotesOutput["notes"]>; count: number }>
    /** Fetch a single note by ID. */
    getNote(params: AttioGetNoteParams): Promise<NonNullable<AttioNotesOutput["note"]>>
    /** Create a note on an Attio record: title + markdown or plaintext content. Use for logging research, call summaries or context onto CRM records. */
    createNote(params: AttioCreateNoteParams): Promise<NonNullable<AttioNotesOutput["note"]>>
    /** Permanently delete an Attio note. */
    deleteNote(params: AttioDeleteNoteParams): Promise<void>
    /** Fetch a single comment by ID. */
    getComment(params: AttioGetCommentParams): Promise<NonNullable<AttioCommentsOutput["comment"]>>
    /** List comment threads on a record. */
    listThreads(params?: AttioListThreadsParams): Promise<{ threads: NonNullable<AttioCommentsOutput["threads"]>; count: number }>
    /** Fetch a thread with all of its comments. */
    getThread(params: AttioGetThreadParams): Promise<NonNullable<AttioCommentsOutput["thread"]>>
    /** Create an Attio comment: reply to a thread via threadId, or start a new thread on a record via objectSlug + recordId. Requires an author workspace member ID (use attio_workspace_members to find it). */
    createComment(params: AttioCreateCommentParams): Promise<NonNullable<AttioCommentsOutput["comment"]>>
    /** Permanently delete an Attio comment. */
    deleteComment(params: AttioDeleteCommentParams): Promise<void>
    /** List all lists in the workspace. */
    listLists(): Promise<{ lists: NonNullable<AttioListsResult["lists"]>; count: number }>
    /** Fetch a list's configuration by ID or slug. */
    getList(params: { list: GeneratedAttioList | string }): Promise<NonNullable<AttioListsResult["list"]>>
    /** Create a new Attio list over an object. This changes the workspace for every user. */
    createList(params: AttioCreateListParams): Promise<NonNullable<AttioListsResult["list"]>>
    /** Rename an Attio list. */
    updateList(params: { list: GeneratedAttioList | string; name: string }): Promise<NonNullable<AttioListsResult["list"]>>
    /** List entries in a list, with optional filter, parent-record lookup, and limit/offset pagination. */
    queryListEntries<TList extends GeneratedAttioList | string>(params: { list: TList; filter?: AttioEntryFilterFor<TList> | null; parentRecordId?: string | null; parentObjectSlug?: string; limit?: number | null; offset?: number | null }): Promise<AttioListEntriesResult<TList>>
    /** Fetch a single list entry. */
    getListEntry<TList extends GeneratedAttioList | string>(params: { list: TList; entryId: string }): Promise<AttioListEntryResult<TList>>
    /** Add a record to an Attio list as a new entry, with optional entry attribute values (e.g. a stage). Throws on unique-attribute conflicts; the same record may appear in multiple entries. */
    addListEntry<TList extends GeneratedAttioList | string>(params: { list: TList; parentRecordId: string; parentObjectSlug?: string; entryValues?: AttioEntryValuesFor<TList> | null }): Promise<AttioListEntryResult<TList>>
    /** Create or update an Attio list entry keyed by its parent record (idempotent membership): updates the existing entry if the record is already in the list, otherwise adds it. */
    upsertListEntry<TList extends GeneratedAttioList | string>(params: { list: TList; parentRecordId: string; parentObjectSlug?: string; entryValues?: AttioEntryValuesFor<TList> | null }): Promise<AttioListEntryResult<TList>>
    /** Update an Attio list entry's attribute values (e.g. move its stage). multiselectMode 'append' adds to multi-value attributes instead of overwriting. */
    updateListEntry<TList extends GeneratedAttioList | string>(params: { list: TList; entryId: string; entryValues: Partial<AttioEntryValuesFor<TList>>; multiselectMode?: "overwrite" | "append" | null }): Promise<AttioListEntryResult<TList>>
    /** Remove an entry from an Attio list. The parent record itself is untouched. */
    removeListEntry(params: { list: GeneratedAttioList | string; entryId: string }): Promise<void>
    /** List meetings, optionally filtered by linked record, participants or time range. Uses cursor pagination. */
    listMeetings(params?: AttioListMeetingsParams): Promise<{ meetings: NonNullable<AttioMeetingsOutput["meetings"]>; count: number; nextCursor: string | null }>
    /** Fetch a single meeting by ID. */
    getMeeting(params: AttioGetMeetingParams): Promise<NonNullable<AttioMeetingsOutput["meeting"]>>
    /** List call recordings for a meeting. */
    listCallRecordings(params: AttioListCallRecordingsParams): Promise<{ recordings: NonNullable<AttioMeetingsOutput["recordings"]>; count: number; nextCursor: string | null }>
    /** Fetch the transcript of a call recording. */
    getCallTranscript(params: AttioGetCallTranscriptParams): Promise<{ transcript: NonNullable<AttioMeetingsOutput["transcript"]>; nextCursor: string | null }>
    /** List files attached to a record. */
    listFiles(params: AttioListFilesParams): Promise<{ files: NonNullable<AttioFilesOutput["files"]>; count: number; nextCursor: string | null }>
    /** Fetch a file's metadata by ID. */
    getFile(params: AttioGetFileParams): Promise<NonNullable<AttioFilesOutput["file"]>>
    /** Get a signed download URL for a file. */
    getFileDownloadUrl(params: AttioGetFileDownloadUrlParams): Promise<NonNullable<AttioFilesOutput["downloadUrl"]>>
    /** Upload a file to an Attio record from base64 content (native Attio storage, max 50 MB). */
    uploadFile(params: AttioUploadFileParams): Promise<NonNullable<AttioFilesOutput["file"]>>
    /** Permanently delete a file from Attio (deleting a folder deletes its descendants). */
    deleteFile(params: AttioDeleteFileParams): Promise<void>
    /** List all object types in the workspace with their attributes and field definitions. Call this before creating or updating records. */
    listObjects(params?: AttioListObjectsParams): Promise<{ objects: NonNullable<AttioSchemaOutput["objects"]>; count: number }>
    /** Fetch one object's configuration. */
    getObject(params: AttioGetObjectParams): Promise<NonNullable<AttioSchemaOutput["object"]>>
    /** List the attributes defined on an object or list. */
    listAttributes(params: AttioListAttributesParams): Promise<{ attributes: NonNullable<AttioSchemaOutput["attributes"]>; count: number }>
    /** List the statuses of a status attribute (e.g. deal stages). */
    listStatuses(params: AttioListStatusesParams): Promise<{ statuses: NonNullable<AttioSchemaOutput["statuses"]>; count: number }>
    /** List the options of a select attribute. */
    listSelectOptions(params: AttioListSelectOptionsParams): Promise<{ selectOptions: NonNullable<AttioSchemaOutput["selectOptions"]>; count: number }>
    /** Create a custom object type. This changes the workspace schema for every user. */
    createObject(params: AttioCreateObjectParams): Promise<NonNullable<AttioSchemaOutput["object"]>>
    /** Update an object's slug or display names. */
    updateObject(params: AttioUpdateObjectParams): Promise<NonNullable<AttioSchemaOutput["object"]>>
    /** Create a new attribute on an object or list. This changes the workspace schema for every user. */
    createAttribute(params: AttioCreateAttributeParams): Promise<NonNullable<AttioSchemaOutput["attribute"]>>
    /** Update an attribute's title, description, slug, constraints, default value or config, or archive it. */
    updateAttribute(params: AttioUpdateAttributeParams): Promise<NonNullable<AttioSchemaOutput["attribute"]>>
    /** Add a new status to a status attribute. Rerun terse generate afterwards to refresh generated constants. */
    createStatus(params: AttioCreateStatusParams): Promise<NonNullable<AttioSchemaOutput["status"]>>
    /** Rename, reconfigure or archive a status. */
    updateStatus(params: AttioUpdateStatusParams): Promise<NonNullable<AttioSchemaOutput["status"]>>
    /** Add an option to a select attribute. Rerun terse generate afterwards to refresh generated constants. */
    createSelectOption(params: AttioCreateSelectOptionParams): Promise<NonNullable<AttioSchemaOutput["selectOption"]>>
    /** Rename or archive a select option. */
    updateSelectOption(params: AttioUpdateSelectOptionParams): Promise<NonNullable<AttioSchemaOutput["selectOption"]>>
}

export const attioTools: AttioGeneratedTools = {
    queryRecords: <TObject extends GeneratedAttioObject>(params: AttioQueryRecordsParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_read_records", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "query", objectSlug: __normalizeAttioObjectSlug(params.object), filter: __serializeAttioFilter(params.filter), limit: params.limit ?? null, offset: params.offset ?? null } }).then(result => __enhanceAttioQueryResult(params.object, result)),
    searchRecords: <TObject extends GeneratedAttioObject>(params: AttioSearchRecordsParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_read_records", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "search", objectSlug: __normalizeAttioObjectSlug(params.object), query: params.query, limit: params.limit ?? null } }).then(result => __enhanceAttioSearchResult(result)),
    getRecord: <TObject extends GeneratedAttioObject>(params: AttioGetRecordParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_read_records", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", objectSlug: __normalizeAttioObjectSlug(params.object), recordId: params.recordId } }).then(result => __enhanceAttioSingleRecordResult(params.object, result)),
    getAttributeHistory: <TObject extends GeneratedAttioObject, TAttr extends AttioAttributeSlug<TObject>>(params: AttioGetAttributeHistoryParams<TObject> & { attribute: TAttr }) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_read_records", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get_attribute_history", objectSlug: __normalizeAttioObjectSlug(params.object), recordId: params.recordId, attributeSlug: params.attribute, limit: params.limit ?? null, offset: params.offset ?? null } }).then(result => __enhanceAttioHistoryResult<__AttioSingleValue<NonNullable<AttioRecordValuesFor<TObject>[TAttr & keyof AttioRecordValuesFor<TObject>]>>>(result)),
    createRecord: <TObject extends GeneratedAttioObject>(params: AttioCreateRecordParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_create_record", { integrationId: "cmltphnii001pp32jakhvweb2", request: { objectSlug: __normalizeAttioObjectSlug(params.object), values: JSON.stringify(params.values) } }).then(result => __enhanceAttioSingleRecordResult(params.object, result)),
    updateRecord: <TObject extends GeneratedAttioObject>(params: AttioUpdateRecordParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_update_record", { integrationId: "cmltphnii001pp32jakhvweb2", request: { objectSlug: __normalizeAttioObjectSlug(params.object), recordId: params.recordId, values: JSON.stringify(params.values), multiselectMode: params.multiselectMode ?? null } }).then(result => __enhanceAttioSingleRecordResult(params.object, result)),
    upsertRecord: <TObject extends GeneratedAttioObject>(params: AttioUpsertRecordParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_upsert_record", { integrationId: "cmltphnii001pp32jakhvweb2", request: { objectSlug: __normalizeAttioObjectSlug(params.object), matchingAttribute: params.matchingAttribute, records: __serializeAttioRecords(params.records) } }).then(result => __enhanceAttioUpsertResult(params.object, result)),
    deleteRecord: <TObject extends GeneratedAttioObject>(params: AttioDeleteRecordParams<TObject>) =>
        TerseAgent.executeTool<AttioRecordsResult>("attio_delete_record", { integrationId: "cmltphnii001pp32jakhvweb2", request: { objectSlug: __normalizeAttioObjectSlug(params.object), recordId: params.recordId } }).then(() => undefined),
    listWorkspaceMembers: (params: AttioListWorkspaceMembersParams = {}) =>
        TerseAgent.executeTool<AttioWorkspaceMembersResult>("attio_workspace_members", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list", ...params } }).then(result => ({ members: result.members ?? [], count: (result.members ?? []).length })),
    getWorkspaceMember: (params: AttioGetWorkspaceMemberParams) =>
        TerseAgent.executeTool<AttioWorkspaceMembersResult>("attio_workspace_members", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", ...params } }).then(result => __requireAttioPayload(result.member, "workspace member")),
    listTasks: (params: AttioListTasksParams = {}) =>
        TerseAgent.executeTool<AttioTasksOutput>("attio_read_tasks", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list", ...params } }).then(result => ({ tasks: result.tasks ?? [], count: (result.tasks ?? []).length })),
    getTask: (params: AttioGetTaskParams) =>
        TerseAgent.executeTool<AttioTasksOutput>("attio_read_tasks", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", ...params } }).then(result => __requireAttioPayload(result.task, "task")),
    createTask: (params: AttioCreateTaskParams) =>
        TerseAgent.executeTool<AttioTasksOutput>("attio_create_task", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(result => __requireAttioPayload(result.task, "task")),
    updateTask: (params: AttioUpdateTaskParams) =>
        TerseAgent.executeTool<AttioTasksOutput>("attio_update_task", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(result => __requireAttioPayload(result.task, "task")),
    deleteTask: (params: AttioDeleteTaskParams) =>
        TerseAgent.executeTool<AttioTasksOutput>("attio_delete_task", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(() => undefined),
    listNotes: (params: AttioListNotesParams = {}) =>
        TerseAgent.executeTool<AttioNotesOutput>("attio_read_notes", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list", ...params } }).then(result => ({ notes: result.notes ?? [], count: (result.notes ?? []).length })),
    getNote: (params: AttioGetNoteParams) =>
        TerseAgent.executeTool<AttioNotesOutput>("attio_read_notes", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", ...params } }).then(result => __requireAttioPayload(result.note, "note")),
    createNote: (params: AttioCreateNoteParams) =>
        TerseAgent.executeTool<AttioNotesOutput>("attio_create_note", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(result => __requireAttioPayload(result.note, "note")),
    deleteNote: (params: AttioDeleteNoteParams) =>
        TerseAgent.executeTool<AttioNotesOutput>("attio_delete_note", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(() => undefined),
    getComment: (params: AttioGetCommentParams) =>
        TerseAgent.executeTool<AttioCommentsOutput>("attio_read_comments", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", ...params } }).then(result => __requireAttioPayload(result.comment, "comment")),
    listThreads: (params: AttioListThreadsParams = {}) =>
        TerseAgent.executeTool<AttioCommentsOutput>("attio_read_comments", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list_threads", ...params } }).then(result => ({ threads: result.threads ?? [], count: (result.threads ?? []).length })),
    getThread: (params: AttioGetThreadParams) =>
        TerseAgent.executeTool<AttioCommentsOutput>("attio_read_comments", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get_thread", ...params } }).then(result => __requireAttioPayload(result.thread, "thread")),
    createComment: (params: AttioCreateCommentParams) =>
        TerseAgent.executeTool<AttioCommentsOutput>("attio_create_comment", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(result => __requireAttioPayload(result.comment, "comment")),
    deleteComment: (params: AttioDeleteCommentParams) =>
        TerseAgent.executeTool<AttioCommentsOutput>("attio_delete_comment", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(() => undefined),
    listLists: () =>
        TerseAgent.executeTool<AttioListsResult>("attio_read_lists", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list" } }).then(result => ({ lists: result.lists ?? [], count: (result.lists ?? []).length })),
    getList: (params: { list: GeneratedAttioList | string }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_read_lists", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", listIdOrSlug: __normalizeAttioObjectSlug(params.list) } }).then(result => __requireAttioPayload(result.list, "list")),
    createList: (params: AttioCreateListParams) =>
        TerseAgent.executeTool<AttioListsResult>("attio_create_list", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(result => __requireAttioPayload(result.list, "list")),
    updateList: (params: { list: GeneratedAttioList | string; name: string }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_update_list", { integrationId: "cmltphnii001pp32jakhvweb2", request: { listIdOrSlug: __normalizeAttioObjectSlug(params.list), name: params.name } }).then(result => __requireAttioPayload(result.list, "list")),
    queryListEntries: <TList extends GeneratedAttioList | string>(params: { list: TList; filter?: AttioEntryFilterFor<TList> | null; parentRecordId?: string | null; parentObjectSlug?: string; limit?: number | null; offset?: number | null }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_read_list_entries", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "query_entries", listIdOrSlug: __normalizeAttioObjectSlug(params.list), filter: __serializeAttioFilter(params.filter), parentRecordId: params.parentRecordId ?? null, parentObjectSlug: params.parentRecordId ? __requireAttioListParentObject(params.list, params.parentObjectSlug) : null, limit: params.limit ?? null, offset: params.offset ?? null } }).then(result => __enhanceAttioListEntriesResult(params.list, result)),
    getListEntry: <TList extends GeneratedAttioList | string>(params: { list: TList; entryId: string }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_read_list_entries", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get_entry", listIdOrSlug: __normalizeAttioObjectSlug(params.list), entryId: params.entryId } }).then(result => __enhanceAttioListEntryResult(params.list, result)),
    addListEntry: <TList extends GeneratedAttioList | string>(params: { list: TList; parentRecordId: string; parentObjectSlug?: string; entryValues?: AttioEntryValuesFor<TList> | null }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_add_list_entry", { integrationId: "cmltphnii001pp32jakhvweb2", request: { listIdOrSlug: __normalizeAttioObjectSlug(params.list), parentObjectSlug: __requireAttioListParentObject(params.list, params.parentObjectSlug), parentRecordId: params.parentRecordId, entryValues: __serializeAttioValues(params.entryValues) } }).then(result => __enhanceAttioListEntryResult(params.list, result)),
    upsertListEntry: <TList extends GeneratedAttioList | string>(params: { list: TList; parentRecordId: string; parentObjectSlug?: string; entryValues?: AttioEntryValuesFor<TList> | null }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_upsert_list_entry", { integrationId: "cmltphnii001pp32jakhvweb2", request: { listIdOrSlug: __normalizeAttioObjectSlug(params.list), parentObjectSlug: __requireAttioListParentObject(params.list, params.parentObjectSlug), parentRecordId: params.parentRecordId, entryValues: __serializeAttioValues(params.entryValues) } }).then(result => __enhanceAttioListEntryResult(params.list, result)),
    updateListEntry: <TList extends GeneratedAttioList | string>(params: { list: TList; entryId: string; entryValues: Partial<AttioEntryValuesFor<TList>>; multiselectMode?: "overwrite" | "append" | null }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_update_list_entry", { integrationId: "cmltphnii001pp32jakhvweb2", request: { listIdOrSlug: __normalizeAttioObjectSlug(params.list), entryId: params.entryId, entryValues: __serializeAttioValues(params.entryValues), multiselectMode: params.multiselectMode ?? null } }).then(result => __enhanceAttioListEntryResult(params.list, result)),
    removeListEntry: (params: { list: GeneratedAttioList | string; entryId: string }) =>
        TerseAgent.executeTool<AttioListsResult>("attio_remove_list_entry", { integrationId: "cmltphnii001pp32jakhvweb2", request: { listIdOrSlug: __normalizeAttioObjectSlug(params.list), entryId: params.entryId } }).then(() => undefined),
    listMeetings: (params: AttioListMeetingsParams = {}) =>
        TerseAgent.executeTool<AttioMeetingsOutput>("attio_meetings", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list", ...params } }).then(result => ({ meetings: result.meetings ?? [], count: (result.meetings ?? []).length, nextCursor: result.nextCursor ?? null })),
    getMeeting: (params: AttioGetMeetingParams) =>
        TerseAgent.executeTool<AttioMeetingsOutput>("attio_meetings", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", ...params } }).then(result => __requireAttioPayload(result.meeting, "meeting")),
    listCallRecordings: (params: AttioListCallRecordingsParams) =>
        TerseAgent.executeTool<AttioMeetingsOutput>("attio_meetings", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list_recordings", ...params } }).then(result => ({ recordings: result.recordings ?? [], count: (result.recordings ?? []).length, nextCursor: result.nextCursor ?? null })),
    getCallTranscript: (params: AttioGetCallTranscriptParams) =>
        TerseAgent.executeTool<AttioMeetingsOutput>("attio_meetings", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get_transcript", ...params } }).then(result => ({ transcript: __requireAttioPayload(result.transcript, "transcript"), nextCursor: result.nextCursor ?? null })),
    listFiles: (params: AttioListFilesParams) =>
        TerseAgent.executeTool<AttioFilesOutput>("attio_read_files", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list", ...params } }).then(result => ({ files: result.files ?? [], count: (result.files ?? []).length, nextCursor: result.nextCursor ?? null })),
    getFile: (params: AttioGetFileParams) =>
        TerseAgent.executeTool<AttioFilesOutput>("attio_read_files", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get", ...params } }).then(result => __requireAttioPayload(result.file, "file")),
    getFileDownloadUrl: (params: AttioGetFileDownloadUrlParams) =>
        TerseAgent.executeTool<AttioFilesOutput>("attio_read_files", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get_download_url", ...params } }).then(result => __requireAttioPayload(result.downloadUrl, "download URL")),
    uploadFile: (params: AttioUploadFileParams) =>
        TerseAgent.executeTool<AttioFilesOutput>("attio_upload_file", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(result => __requireAttioPayload(result.file, "file")),
    deleteFile: (params: AttioDeleteFileParams) =>
        TerseAgent.executeTool<AttioFilesOutput>("attio_delete_file", { integrationId: "cmltphnii001pp32jakhvweb2", request: params }).then(() => undefined),
    listObjects: (params: AttioListObjectsParams = {}) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_read_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list_objects", ...params } }).then(result => ({ objects: result.objects ?? [], count: (result.objects ?? []).length })),
    getObject: (params: AttioGetObjectParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_read_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "get_object", ...params } }).then(result => __requireAttioPayload(result.object, "object")),
    listAttributes: (params: AttioListAttributesParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_read_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list_attributes", ...params } }).then(result => ({ attributes: result.attributes ?? [], count: (result.attributes ?? []).length })),
    listStatuses: (params: AttioListStatusesParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_read_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list_statuses", ...params } }).then(result => ({ statuses: result.statuses ?? [], count: (result.statuses ?? []).length })),
    listSelectOptions: (params: AttioListSelectOptionsParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_read_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "list_select_options", ...params } }).then(result => ({ selectOptions: result.selectOptions ?? [], count: (result.selectOptions ?? []).length })),
    createObject: (params: AttioCreateObjectParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "create_object", ...params } }).then(result => __requireAttioPayload(result.object, "object")),
    updateObject: (params: AttioUpdateObjectParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "update_object", ...params } }).then(result => __requireAttioPayload(result.object, "object")),
    createAttribute: (params: AttioCreateAttributeParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "create_attribute", ...params } }).then(result => __requireAttioPayload(result.attribute, "attribute")),
    updateAttribute: (params: AttioUpdateAttributeParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "update_attribute", ...params } }).then(result => __requireAttioPayload(result.attribute, "attribute")),
    createStatus: (params: AttioCreateStatusParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "create_status", ...params } }).then(result => __requireAttioPayload(result.status, "status")),
    updateStatus: (params: AttioUpdateStatusParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "update_status", ...params } }).then(result => __requireAttioPayload(result.status, "status")),
    createSelectOption: (params: AttioCreateSelectOptionParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "create_select_option", ...params } }).then(result => __requireAttioPayload(result.selectOption, "selectOption")),
    updateSelectOption: (params: AttioUpdateSelectOptionParams) =>
        TerseAgent.executeTool<AttioSchemaOutput>("attio_modify_schema", { integrationId: "cmltphnii001pp32jakhvweb2", request: { action: "update_select_option", ...params } }).then(result => __requireAttioPayload(result.selectOption, "selectOption")),
}

// ── Attio skill ───────────────────────────────────────────────

/** Attio — query and upsert records on a CRM object */
export function attioSkill(opts: { object: AttioObject<any> }): TypedSkill<"attio_add_list_entry" | "attio_create_comment" | "attio_create_list" | "attio_create_note" | "attio_create_record" | "attio_create_task" | "attio_delete_comment" | "attio_delete_file" | "attio_delete_note" | "attio_delete_record" | "attio_delete_task" | "attio_modify_schema" | "attio_remove_list_entry" | "attio_update_list" | "attio_update_list_entry" | "attio_update_record" | "attio_update_task" | "attio_upload_file" | "attio_upsert_list_entry" | "attio_upsert_record"> {
    return new AttioOutputConfig("cmltphnii001pp32jakhvweb2", opts.object.apiSlug)
}

// ── Attio internals (generated plumbing — no need to read) ────

function __normalizeAttioObjectSlug(object: unknown): string {
    if (object && typeof object === "object" && "apiSlug" in (object as Record<string, unknown>)) {
        const apiSlug = (object as { apiSlug?: unknown }).apiSlug
        if (typeof apiSlug === "string" && apiSlug.length > 0) return apiSlug
    }
    return typeof object === "string" ? object : ""
}

function __serializeAttioFilter(filter: unknown): string | null {
    if (filter === undefined || filter === null) return null
    return JSON.stringify(filter)
}

function __serializeAttioValues(values: unknown): string {
    return JSON.stringify(values ?? {})
}

function __serializeAttioRecords(records: unknown): string {
    if (!Array.isArray(records)) return JSON.stringify([])
    return JSON.stringify(records.filter((record): record is Record<string, unknown> => typeof record === "object" && record !== null && !Array.isArray(record)))
}

function __enhanceAttioRecord<TObject extends GeneratedAttioObject>(object: TObject, record: unknown): __AttioRecordWithValues<AttioRecordValuesFor<TObject>> | undefined {
    if (!record || typeof record !== "object") return undefined
    const values = __getAttioRecordValues<AttioRecordValuesFor<TObject>>(__normalizeAttioObjectSlug(object), record)
    return { ...values, ...(record as AttioRecordBase), values, attributes: values } as __AttioRecordWithValues<AttioRecordValuesFor<TObject>>
}

function __requireAttioPayload<T>(value: T | null | undefined, what: string): T {
    if (value === null || value === undefined) throw new Error("Attio returned a response without the expected " + what + " payload.")
    return value
}

function __enhanceAttioQueryResult<TObject extends GeneratedAttioObject>(object: TObject, result: AttioRecordsResult): AttioQueryRecordsResult<TObject> {
    const records = (result.records || []).map(record => __enhanceAttioRecord(object, record)).filter(Boolean) as Array<AttioRecordFor<TObject>>
    return { records, count: records.length, offset: result.offset ?? 0 }
}

function __enhanceAttioSearchResult(result: AttioRecordsResult): AttioSearchRecordsResult {
    const matches = result.matches ?? []
    return { matches, count: matches.length }
}

function __enhanceAttioUpsertResult<TObject extends GeneratedAttioObject>(object: TObject, result: AttioRecordsResult): AttioUpsertRecordResult<TObject> {
    const records = (result.records || []).map(record => __enhanceAttioRecord(object, record)).filter(Boolean) as Array<AttioRecordFor<TObject>>
    return { records, count: records.length }
}

function __enhanceAttioSingleRecordResult<TObject extends GeneratedAttioObject>(object: TObject, result: AttioRecordsResult): AttioSingleRecordResult<TObject> {
    return __requireAttioPayload(__enhanceAttioRecord(object, result.record), "record")
}

const __attioMetadataKeys = new Set([
    "active_from",
    "active_until",
    "attribute_type",
    "created_by_actor",
])

const __attioMultiValueAttributeSlugsByObject: Record<string, readonly string[]> = {
    "workspaces": ["users"],
    "people": ["email_addresses", "phone_numbers", "associated_deals", "associated_users"],
    "companies": ["domains", "team", "categories", "associated_deals", "associated_workspaces"],
    "deals": ["associated_people", "competitors"],
    "users": ["workspace"],
}

const __attioObjectSlugByObjectId: Record<string, string> = {
    "1438f767-a019-4481-988c-a8b9652e9316": "workspaces",
    "1bcfaec9-d780-435d-8088-05032f38cf71": "people",
    "32b97358-5905-46af-963b-83fc48bd8188": "companies",
    "3aa184f1-23e9-445d-bbb7-13ea0fac7bf4": "deals",
    "adaa14a2-967b-4101-8a95-31b68087379a": "users",
}

function __flattenAttioLeafValue(value: unknown): unknown {
    if (value === null || value === undefined) return value
    if (Array.isArray(value)) return value.map(entry => __flattenAttioLeafValue(entry))
    if (typeof value !== "object") return value
    const rawObject = value as Record<string, unknown>
    if (rawObject.attribute_type === "status") return __toAttioSelectOption(rawObject.status)
    if (rawObject.attribute_type === "select") return __toAttioSelectOption(rawObject.option)
    if (typeof rawObject.full_name === "string") return rawObject.full_name
    if (typeof rawObject.email_address === "string") return rawObject.email_address
    if (typeof rawObject.domain === "string") return rawObject.domain
    if (typeof rawObject.phone_number === "string") return rawObject.phone_number
    if ("value" in rawObject) return __flattenAttioLeafValue(rawObject.value)
    const dataEntries = Object.entries(rawObject).filter(([key]) => !__attioMetadataKeys.has(key))
    if (dataEntries.length === 0) return rawObject
    if (dataEntries.length === 1) return __flattenAttioLeafValue(dataEntries[0][1])
    return Object.fromEntries(dataEntries.map(([key, entryValue]) => [key, __flattenAttioLeafValue(entryValue)]))
}

function __toAttioSelectOption(option: unknown): unknown {
    if (!option || typeof option !== "object") return option
    const rawOption = option as Record<string, unknown>
    const rawId = rawOption.id && typeof rawOption.id === "object" ? (rawOption.id as Record<string, unknown>) : undefined
    const id = rawId?.status_id ?? rawId?.option_id ?? rawOption.id
    return {
        id: typeof id === "string" ? id : "",
        title: typeof rawOption.title === "string" ? rawOption.title : "",
        is_archived: rawOption.is_archived === true,
    } satisfies AttioSelectOption
}

function __flattenAttioAttributeValue(rawValue: unknown, preferArray: boolean): unknown {
    if (!Array.isArray(rawValue)) return __flattenAttioLeafValue(rawValue)
    const flattened = rawValue.map(entry => __flattenAttioLeafValue(entry)).filter(entry => entry !== undefined)
    return preferArray ? flattened : flattened[0]
}

function __isAttioMultiValueAttribute(objectSlug: string, attributeSlug: string): boolean {
    return (__attioMultiValueAttributeSlugsByObject[objectSlug] || []).includes(attributeSlug)
}

function __getAttioRecordValues<TValues extends Record<string, unknown>>(objectSlug: string, record: unknown): TValues {
    const rawValues = record && typeof record === "object" ? (record as { values?: unknown }).values : undefined
    if (!rawValues || typeof rawValues !== "object" || Array.isArray(rawValues)) return {} as TValues
    const flattenedValues: Record<string, unknown> = {}
    for (const [attributeSlug, rawValue] of Object.entries(rawValues)) {
        flattenedValues[attributeSlug] = __flattenAttioAttributeValue(rawValue, __isAttioMultiValueAttribute(objectSlug, attributeSlug))
    }
    return flattenedValues as TValues
}

const __attioMultiValueEntrySlugsByList: Record<string, readonly string[]> = {
    "feedback_requests": [],
    "ee49fa72-4e4e-41b6-8c60-2d0e23a464cf": [],
    "icp_prospects": [],
    "d56f425e-cb02-478e-bd00-73574aa1231c": [],
}

function __getAttioEntryValues<TValues extends Record<string, unknown>>(listKey: string, rawEntryValues: unknown): TValues {
    if (!rawEntryValues || typeof rawEntryValues !== "object" || Array.isArray(rawEntryValues)) return {} as TValues
    const flattenedValues: Record<string, unknown> = {}
    const multiValueSlugs = __attioMultiValueEntrySlugsByList[listKey] || []
    for (const [attributeSlug, rawValue] of Object.entries(rawEntryValues)) {
        flattenedValues[attributeSlug] = __flattenAttioAttributeValue(rawValue, multiValueSlugs.includes(attributeSlug))
    }
    return flattenedValues as TValues
}

function __requireAttioListParentObject(list: unknown, parentObjectSlug: string | null | undefined): string {
    if (parentObjectSlug) return parentObjectSlug
    if (list && typeof list === "object" && "parentObject" in (list as Record<string, unknown>)) {
        const parentObject = (list as { parentObject?: unknown }).parentObject
        if (typeof parentObject === "string" && parentObject.length > 0) return parentObject
    }
    throw new Error("parentObjectSlug is required when the list is passed as a plain ID/slug rather than a generated AttioList constant.")
}

function __enhanceAttioListEntry<TList>(list: TList, entry: unknown): AttioListEntryFor<TList> {
    const raw = (entry && typeof entry === "object" ? entry : {}) as { entry_values?: unknown }
    return { ...(raw as object), entry_values: __getAttioEntryValues(__normalizeAttioObjectSlug(list), raw.entry_values) } as AttioListEntryFor<TList>
}

function __enhanceAttioListEntriesResult<TList>(list: TList, result: AttioListsResult): AttioListEntriesResult<TList> {
    const entries = (result.entries || []).map(entry => __enhanceAttioListEntry(list, entry))
    return { entries, count: entries.length, offset: result.offset ?? 0 }
}

function __enhanceAttioListEntryResult<TList>(list: TList, result: AttioListsResult): AttioListEntryResult<TList> {
    if (!result.entry) throw new Error("Attio returned a response without the expected list entry payload.")
    return __enhanceAttioListEntry(list, result.entry)
}

function __enhanceAttioHistoryResult<TValue>(result: AttioRecordsResult): AttioAttributeHistoryResult<TValue> {
    const history = (result.history || []).map(entry => ({ active_from: entry.active_from, active_until: entry.active_until, value: __flattenAttioLeafValue(entry) as TValue }))
    return { history, count: history.length }
}

registerEventTransform("attio", (event) => {
    const e = event as { record?: { values?: unknown }; resourceIds?: { object_id?: string } }
    if (!e?.record?.values) return event
    const objectId = e.resourceIds?.object_id
    const slug = objectId ? __attioObjectSlugByObjectId[objectId] : undefined
    if (!slug) return event
    return { ...e, record: { ...e.record, values: __getAttioRecordValues(slug, e.record) } }
})