// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    AttioEventType,
    AttioInputConfig,
    SDKTrigger,
    TypedTrigger,
} from "terse-sdk"
import type { AttioWorkspaceRecordValues, AttioPersonRecordValues, AttioCompanyRecordValues, AttioDealRecordValues, AttioUserRecordValues, GeneratedAttioObject } from "./attio.schemas.js"

// ── Attio triggers ────────────────────────────────────────────

export interface AttioCallRecordingCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "call-recording.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioCallRecordingCreatedTrigger = SDKTrigger<AttioCallRecordingCreatedTriggerPayload>

export interface AttioCommentCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "comment.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioCommentCreatedTrigger = SDKTrigger<AttioCommentCreatedTriggerPayload>

export interface AttioCommentResolvedTriggerPayload {
    integrationType: "attio"
    eventType: "comment.resolved"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioCommentResolvedTrigger = SDKTrigger<AttioCommentResolvedTriggerPayload>

export interface AttioCommentUnresolvedTriggerPayload {
    integrationType: "attio"
    eventType: "comment.unresolved"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioCommentUnresolvedTrigger = SDKTrigger<AttioCommentUnresolvedTriggerPayload>

export interface AttioCommentDeletedTriggerPayload {
    integrationType: "attio"
    eventType: "comment.deleted"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioCommentDeletedTrigger = SDKTrigger<AttioCommentDeletedTriggerPayload>

export interface AttioListCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "list.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListCreatedTrigger = SDKTrigger<AttioListCreatedTriggerPayload>

export interface AttioListUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "list.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListUpdatedTrigger = SDKTrigger<AttioListUpdatedTriggerPayload>

export interface AttioListDeletedTriggerPayload {
    integrationType: "attio"
    eventType: "list.deleted"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListDeletedTrigger = SDKTrigger<AttioListDeletedTriggerPayload>

export interface AttioListAttributeCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "list-attribute.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListAttributeCreatedTrigger = SDKTrigger<AttioListAttributeCreatedTriggerPayload>

export interface AttioListAttributeUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "list-attribute.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListAttributeUpdatedTrigger = SDKTrigger<AttioListAttributeUpdatedTriggerPayload>

export interface AttioListEntryCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "list-entry.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListEntryCreatedTrigger = SDKTrigger<AttioListEntryCreatedTriggerPayload>

export interface AttioListEntryUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "list-entry.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListEntryUpdatedTrigger = SDKTrigger<AttioListEntryUpdatedTriggerPayload>

export interface AttioListEntryDeletedTriggerPayload {
    integrationType: "attio"
    eventType: "list-entry.deleted"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioListEntryDeletedTrigger = SDKTrigger<AttioListEntryDeletedTriggerPayload>

export interface AttioObjectAttributeCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "object-attribute.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioObjectAttributeCreatedTrigger = SDKTrigger<AttioObjectAttributeCreatedTriggerPayload>

export interface AttioObjectAttributeUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "object-attribute.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioObjectAttributeUpdatedTrigger = SDKTrigger<AttioObjectAttributeUpdatedTriggerPayload>

export interface AttioNoteCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "note.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioNoteCreatedTrigger = SDKTrigger<AttioNoteCreatedTriggerPayload>

export interface AttioNoteContentUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "note-content.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioNoteContentUpdatedTrigger = SDKTrigger<AttioNoteContentUpdatedTriggerPayload>

export interface AttioNoteUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "note.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioNoteUpdatedTrigger = SDKTrigger<AttioNoteUpdatedTriggerPayload>

export interface AttioNoteDeletedTriggerPayload {
    integrationType: "attio"
    eventType: "note.deleted"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioNoteDeletedTrigger = SDKTrigger<AttioNoteDeletedTriggerPayload>

export interface AttioRecordCreatedTriggerPayload<TValues = Record<string, unknown>> {
    integrationType: "attio"
    eventType: "record.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
    record: {
        id: {
            workspace_id: string
            object_id: string
            record_id: string
        }
        values: TValues
        web_url?: string
        created_at?: string
    }
}

export type AttioRecordCreatedTrigger<TValues = Record<string, unknown>> = SDKTrigger<AttioRecordCreatedTriggerPayload<TValues>>

export interface AttioRecordMergedTriggerPayload<TValues = Record<string, unknown>> {
    integrationType: "attio"
    eventType: "record.merged"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
    record: {
        id: {
            workspace_id: string
            object_id: string
            record_id: string
        }
        values: TValues
        web_url?: string
        created_at?: string
    }
}

export type AttioRecordMergedTrigger<TValues = Record<string, unknown>> = SDKTrigger<AttioRecordMergedTriggerPayload<TValues>>

export interface AttioRecordUpdatedTriggerPayload<TValues = Record<string, unknown>> {
    integrationType: "attio"
    eventType: "record.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
    record: {
        id: {
            workspace_id: string
            object_id: string
            record_id: string
        }
        values: TValues
        web_url?: string
        created_at?: string
    }
}

export type AttioRecordUpdatedTrigger<TValues = Record<string, unknown>> = SDKTrigger<AttioRecordUpdatedTriggerPayload<TValues>>

export interface AttioRecordDeletedTriggerPayload {
    integrationType: "attio"
    eventType: "record.deleted"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioRecordDeletedTrigger = SDKTrigger<AttioRecordDeletedTriggerPayload>

export interface AttioTaskCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "task.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioTaskCreatedTrigger = SDKTrigger<AttioTaskCreatedTriggerPayload>

export interface AttioTaskUpdatedTriggerPayload {
    integrationType: "attio"
    eventType: "task.updated"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioTaskUpdatedTrigger = SDKTrigger<AttioTaskUpdatedTriggerPayload>

export interface AttioTaskDeletedTriggerPayload {
    integrationType: "attio"
    eventType: "task.deleted"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioTaskDeletedTrigger = SDKTrigger<AttioTaskDeletedTriggerPayload>

export interface AttioWorkspaceMemberCreatedTriggerPayload {
    integrationType: "attio"
    eventType: "workspace-member.created"
    eventId: string
    createdAt: string
    workspaceId: string
    resourceIds: {
        workspace_id: string
        object_id?: string
        record_id?: string
        list_id?: string
        entry_id?: string
        note_id?: string
        task_id?: string
        comment_id?: string
        attribute_id?: string
        call_recording_id?: string
        meeting_id?: string
        workspace_member_id?: string
    }
    objectSlug?: string | null
    actor: {
        type: ("api-token" | "workspace-member" | "system" | "app") | null
        id: string | null
    }
    rawEvent: {
        [k: string]: unknown
    }
}

export type AttioWorkspaceMemberCreatedTrigger = SDKTrigger<AttioWorkspaceMemberCreatedTriggerPayload>

export type AttioTrigger = AttioCallRecordingCreatedTrigger | AttioCommentCreatedTrigger | AttioCommentResolvedTrigger | AttioCommentUnresolvedTrigger | AttioCommentDeletedTrigger | AttioListCreatedTrigger | AttioListUpdatedTrigger | AttioListDeletedTrigger | AttioListAttributeCreatedTrigger | AttioListAttributeUpdatedTrigger | AttioListEntryCreatedTrigger | AttioListEntryUpdatedTrigger | AttioListEntryDeletedTrigger | AttioObjectAttributeCreatedTrigger | AttioObjectAttributeUpdatedTrigger | AttioNoteCreatedTrigger | AttioNoteContentUpdatedTrigger | AttioNoteUpdatedTrigger | AttioNoteDeletedTrigger | AttioRecordCreatedTrigger | AttioRecordMergedTrigger | AttioRecordUpdatedTrigger | AttioRecordDeletedTrigger | AttioTaskCreatedTrigger | AttioTaskUpdatedTrigger | AttioTaskDeletedTrigger | AttioWorkspaceMemberCreatedTrigger

export type AttioWorkspaceRecordCreatedPayload = AttioRecordCreatedTriggerPayload<AttioWorkspaceRecordValues>
export type AttioWorkspaceRecordCreatedTrigger = AttioRecordCreatedTrigger<AttioWorkspaceRecordValues>
export type AttioWorkspaceRecordUpdatedPayload = AttioRecordUpdatedTriggerPayload<AttioWorkspaceRecordValues>
export type AttioWorkspaceRecordUpdatedTrigger = AttioRecordUpdatedTrigger<AttioWorkspaceRecordValues>
export type AttioWorkspaceRecordMergedPayload = AttioRecordMergedTriggerPayload<AttioWorkspaceRecordValues>
export type AttioWorkspaceRecordMergedTrigger = AttioRecordMergedTrigger<AttioWorkspaceRecordValues>
export type AttioPersonRecordCreatedPayload = AttioRecordCreatedTriggerPayload<AttioPersonRecordValues>
export type AttioPersonRecordCreatedTrigger = AttioRecordCreatedTrigger<AttioPersonRecordValues>
export type AttioPersonRecordUpdatedPayload = AttioRecordUpdatedTriggerPayload<AttioPersonRecordValues>
export type AttioPersonRecordUpdatedTrigger = AttioRecordUpdatedTrigger<AttioPersonRecordValues>
export type AttioPersonRecordMergedPayload = AttioRecordMergedTriggerPayload<AttioPersonRecordValues>
export type AttioPersonRecordMergedTrigger = AttioRecordMergedTrigger<AttioPersonRecordValues>
export type AttioCompanyRecordCreatedPayload = AttioRecordCreatedTriggerPayload<AttioCompanyRecordValues>
export type AttioCompanyRecordCreatedTrigger = AttioRecordCreatedTrigger<AttioCompanyRecordValues>
export type AttioCompanyRecordUpdatedPayload = AttioRecordUpdatedTriggerPayload<AttioCompanyRecordValues>
export type AttioCompanyRecordUpdatedTrigger = AttioRecordUpdatedTrigger<AttioCompanyRecordValues>
export type AttioCompanyRecordMergedPayload = AttioRecordMergedTriggerPayload<AttioCompanyRecordValues>
export type AttioCompanyRecordMergedTrigger = AttioRecordMergedTrigger<AttioCompanyRecordValues>
export type AttioDealRecordCreatedPayload = AttioRecordCreatedTriggerPayload<AttioDealRecordValues>
export type AttioDealRecordCreatedTrigger = AttioRecordCreatedTrigger<AttioDealRecordValues>
export type AttioDealRecordUpdatedPayload = AttioRecordUpdatedTriggerPayload<AttioDealRecordValues>
export type AttioDealRecordUpdatedTrigger = AttioRecordUpdatedTrigger<AttioDealRecordValues>
export type AttioDealRecordMergedPayload = AttioRecordMergedTriggerPayload<AttioDealRecordValues>
export type AttioDealRecordMergedTrigger = AttioRecordMergedTrigger<AttioDealRecordValues>
export type AttioUserRecordCreatedPayload = AttioRecordCreatedTriggerPayload<AttioUserRecordValues>
export type AttioUserRecordCreatedTrigger = AttioRecordCreatedTrigger<AttioUserRecordValues>
export type AttioUserRecordUpdatedPayload = AttioRecordUpdatedTriggerPayload<AttioUserRecordValues>
export type AttioUserRecordUpdatedTrigger = AttioRecordUpdatedTrigger<AttioUserRecordValues>
export type AttioUserRecordMergedPayload = AttioRecordMergedTriggerPayload<AttioUserRecordValues>
export type AttioUserRecordMergedTrigger = AttioRecordMergedTrigger<AttioUserRecordValues>

function attioParentObjectFilter(object: GeneratedAttioObject | undefined) {
    if (!object) return null
    return { $and: [{ field: "id.object_id", operator: "equals" as const, value: object.objectId }] }
}

export const attioTriggers = {
    /** Trigger when a call recording is created */
    onCallRecordingCreated(): TypedTrigger<AttioCallRecordingCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.CALL_RECORDING_CREATED }])
    },
    /** Trigger when a comment is created */
    onCommentCreated(): TypedTrigger<AttioCommentCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.COMMENT_CREATED }])
    },
    /** Trigger when a comment is resolved */
    onCommentResolved(): TypedTrigger<AttioCommentResolvedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.COMMENT_RESOLVED }])
    },
    /** Trigger when a comment is unresolved */
    onCommentUnresolved(): TypedTrigger<AttioCommentUnresolvedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.COMMENT_UNRESOLVED }])
    },
    /** Trigger when a comment is deleted */
    onCommentDeleted(): TypedTrigger<AttioCommentDeletedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.COMMENT_DELETED }])
    },
    /** Trigger when a list is created */
    onListCreated(): TypedTrigger<AttioListCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_CREATED }])
    },
    /** Trigger when a list is updated */
    onListUpdated(): TypedTrigger<AttioListUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_UPDATED }])
    },
    /** Trigger when a list is deleted */
    onListDeleted(): TypedTrigger<AttioListDeletedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_DELETED }])
    },
    /** Trigger when a list attribute is created */
    onListAttributeCreated(): TypedTrigger<AttioListAttributeCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_ATTRIBUTE_CREATED }])
    },
    /** Trigger when a list attribute is updated */
    onListAttributeUpdated(): TypedTrigger<AttioListAttributeUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_ATTRIBUTE_UPDATED }])
    },
    /** Trigger when a list entry is created */
    onListEntryCreated(): TypedTrigger<AttioListEntryCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_ENTRY_CREATED }])
    },
    /** Trigger when a list entry is updated */
    onListEntryUpdated(): TypedTrigger<AttioListEntryUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_ENTRY_UPDATED }])
    },
    /** Trigger when a list entry is deleted */
    onListEntryDeleted(): TypedTrigger<AttioListEntryDeletedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.LIST_ENTRY_DELETED }])
    },
    /** Trigger when an object attribute is created */
    onObjectAttributeCreated(): TypedTrigger<AttioObjectAttributeCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.OBJECT_ATTRIBUTE_CREATED }])
    },
    /** Trigger when an object attribute is updated */
    onObjectAttributeUpdated(): TypedTrigger<AttioObjectAttributeUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.OBJECT_ATTRIBUTE_UPDATED }])
    },
    /** Trigger when a note is created */
    onNoteCreated(): TypedTrigger<AttioNoteCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.NOTE_CREATED }])
    },
    /** Trigger when a note's content is updated */
    onNoteContentUpdated(): TypedTrigger<AttioNoteContentUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.NOTE_CONTENT_UPDATED }])
    },
    /** Trigger when a note is updated */
    onNoteUpdated(): TypedTrigger<AttioNoteUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.NOTE_UPDATED }])
    },
    /** Trigger when a note is deleted */
    onNoteDeleted(): TypedTrigger<AttioNoteDeletedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.NOTE_DELETED }])
    },
    /** Trigger when a record is created. Pass `object` to scope to a specific Attio object. */
    onRecordCreated<T extends GeneratedAttioObject = never>(opts?: { object: T }): TypedTrigger<AttioRecordCreatedTrigger<[T] extends [never] ? GeneratedAttioObject["__recordValues"] : T["__recordValues"]>> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.RECORD_CREATED, filter: attioParentObjectFilter(opts?.object) }])
    },
    /** Trigger when records are merged. Pass `object` to scope to a specific Attio object. */
    onRecordMerged<T extends GeneratedAttioObject = never>(opts?: { object: T }): TypedTrigger<AttioRecordMergedTrigger<[T] extends [never] ? GeneratedAttioObject["__recordValues"] : T["__recordValues"]>> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.RECORD_MERGED, filter: attioParentObjectFilter(opts?.object) }])
    },
    /** Trigger when a record is updated. Pass `object` to scope to a specific Attio object. */
    onRecordUpdated<T extends GeneratedAttioObject = never>(opts?: { object: T }): TypedTrigger<AttioRecordUpdatedTrigger<[T] extends [never] ? GeneratedAttioObject["__recordValues"] : T["__recordValues"]>> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.RECORD_UPDATED, filter: attioParentObjectFilter(opts?.object) }])
    },
    /** Trigger when a record is deleted. Pass `object` to scope to a specific Attio object. */
    onRecordDeleted(opts?: { object?: GeneratedAttioObject }): TypedTrigger<AttioRecordDeletedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.RECORD_DELETED, filter: attioParentObjectFilter(opts?.object) }])
    },
    /** Trigger when a task is created */
    onTaskCreated(): TypedTrigger<AttioTaskCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.TASK_CREATED }])
    },
    /** Trigger when a task is updated */
    onTaskUpdated(): TypedTrigger<AttioTaskUpdatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.TASK_UPDATED }])
    },
    /** Trigger when a task is deleted */
    onTaskDeleted(): TypedTrigger<AttioTaskDeletedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.TASK_DELETED }])
    },
    /** Trigger when a workspace member is added */
    onWorkspaceMemberCreated(): TypedTrigger<AttioWorkspaceMemberCreatedTrigger> {
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", [{ eventType: AttioEventType.WORKSPACE_MEMBER_CREATED }])
    },
    /** Trigger on one or more Attio event types. Pass `object` to scope record events to a specific Attio object. */
    trigger(opts: { eventTypes: AttioEventType[]; object?: GeneratedAttioObject }): TypedTrigger<AttioTrigger> {
        const filter = attioParentObjectFilter(opts.object)
        return new AttioInputConfig("cmltphnii001pp32jakhvweb2", opts.eventTypes.map(eventType => ({ eventType, filter })))
    },
}