// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import type { RunHistoryAction } from "./common.js"

// ── Attio workspace schemas ───────────────────────────────────

export interface AttioSelectOption {
    id: string
    title: string
    is_archived: boolean
}

export type AttioActorReferenceInput =
    | string
    | {
          workspace_member_email_address: string
      }
    | {
          referenced_actor_type: "workspace-member"
          referenced_actor_id: string
      }

export type AttioRecordReferenceInput =
    | {
          target_object: string
          target_record_id: string
      }
    | {
          [k: string]: unknown
      }

export interface AttioActorReference {
    referenced_actor_type: string
    referenced_actor_id: string | null
}

export interface AttioRecordReferenceValue {
    target_object: string
    target_record_id: string
}

export interface AttioCurrencyValue {
    currency_value: number
    currency_code: string | null
}

export type AttioWorkspaceRecordValues = {
    record_id?: string
    workspace_id?: string
    name?: string
    users?: AttioRecordReferenceValue[]
    company?: AttioRecordReferenceValue
    avatar_url?: string
    created_at?: string
    created_by?: AttioActorReference
}

export type AttioWorkspaceInputValues = {
    record_id?: string
    workspace_id?: string
    name?: string
    users?: AttioRecordReferenceInput[]
    company?: AttioRecordReferenceInput
    avatar_url?: string
    created_at?: string
    created_by?: AttioActorReferenceInput
}

export type AttioPersonRecordValues = {
    record_id?: string
    name?: string
    email_addresses?: string[]
    description?: string
    company?: AttioRecordReferenceValue
    job_title?: string
    avatar_url?: string
    phone_numbers?: number[]
    primary_location?: {
        [k: string]: unknown
    }
    angellist?: string
    facebook?: string
    instagram?: string
    linkedin?: string
    twitter?: string
    twitter_follower_count?: number
    first_calendar_interaction?: unknown
    last_calendar_interaction?: unknown
    next_calendar_interaction?: unknown
    first_email_interaction?: unknown
    last_email_interaction?: unknown
    first_interaction?: unknown
    last_interaction?: unknown
    next_interaction?: unknown
    strongest_connection_strength_legacy?: number
    strongest_connection_strength?: AttioSelectOption
    strongest_connection_user?: AttioActorReference
    associated_deals?: AttioRecordReferenceValue[]
    associated_users?: AttioRecordReferenceValue[]
    created_at?: string
    created_by?: AttioActorReference
    posthog_health_status?: AttioSelectOption
    posthog_last_built?: string
    posthog_builder_actions_7d?: number
    posthog_builder_trend_wow?: number
    posthog_jobs_run_7d?: number
    posthog_jobs_completed_7d?: number
    posthog_job_failures_7d?: number
    posthog_deploy_failures_7d?: number
    posthog_automation_status?: AttioSelectOption
    posthog_integrations_added_7d?: number
    posthog_agent_runs_7d?: number
    posthog_agent_actions_7d?: number
    posthog_projects_created_7d?: number
    posthog_projects_deployed_7d?: number
    posthog_jobs_created_7d?: number
    posthog_cli_logins_7d?: number
}

export type AttioPersonInputValues = {
    record_id?: string
    name?: string
    email_addresses?: string[]
    description?: string
    company?: AttioRecordReferenceInput
    job_title?: string
    avatar_url?: string
    phone_numbers?: number[]
    primary_location?: {
        [k: string]: unknown
    }
    angellist?: string
    facebook?: string
    instagram?: string
    linkedin?: string
    twitter?: string
    twitter_follower_count?: number
    first_calendar_interaction?: unknown
    last_calendar_interaction?: unknown
    next_calendar_interaction?: unknown
    first_email_interaction?: unknown
    last_email_interaction?: unknown
    first_interaction?: unknown
    last_interaction?: unknown
    next_interaction?: unknown
    strongest_connection_strength_legacy?: number
    strongest_connection_strength?: "Very weak" | "Weak" | "Good" | "Strong" | "Very strong"
    strongest_connection_user?: AttioActorReferenceInput
    associated_deals?: AttioRecordReferenceInput[]
    associated_users?: AttioRecordReferenceInput[]
    created_at?: string
    created_by?: AttioActorReferenceInput
    posthog_health_status?: "Power builder" | "Active" | "Cooling off" | "Dormant"
    posthog_last_built?: string
    posthog_builder_actions_7d?: number
    posthog_builder_trend_wow?: number
    posthog_jobs_run_7d?: number
    posthog_jobs_completed_7d?: number
    posthog_job_failures_7d?: number
    posthog_deploy_failures_7d?: number
    posthog_automation_status?: "Running" | "Stalled" | "Not running"
    posthog_integrations_added_7d?: number
    posthog_agent_runs_7d?: number
    posthog_agent_actions_7d?: number
    posthog_projects_created_7d?: number
    posthog_projects_deployed_7d?: number
    posthog_jobs_created_7d?: number
    posthog_cli_logins_7d?: number
}

export type AttioCompanyRecordValues = {
    record_id?: string
    domains?: string[]
    name?: string
    description?: string
    team?: AttioRecordReferenceValue[]
    categories?: AttioSelectOption[]
    primary_location?: {
        [k: string]: unknown
    }
    logo_url?: string
    angellist?: string
    facebook?: string
    instagram?: string
    linkedin?: string
    twitter?: string
    twitter_follower_count?: number
    estimated_arr_usd?: AttioSelectOption
    funding_raised_usd?: AttioCurrencyValue
    foundation_date?: string
    employee_range?: AttioSelectOption
    first_calendar_interaction?: unknown
    last_calendar_interaction?: unknown
    next_calendar_interaction?: unknown
    first_email_interaction?: unknown
    last_email_interaction?: unknown
    first_interaction?: unknown
    last_interaction?: unknown
    next_interaction?: unknown
    strongest_connection_strength_legacy?: number
    strongest_connection_strength?: AttioSelectOption
    strongest_connection_user?: AttioActorReference
    associated_deals?: AttioRecordReferenceValue[]
    associated_workspaces?: AttioRecordReferenceValue[]
    created_at?: string
    created_by?: AttioActorReference
}

export type AttioCompanyInputValues = {
    record_id?: string
    domains?: string[]
    name?: string
    description?: string
    team?: AttioRecordReferenceInput[]
    categories?: (
        | "3D Printing"
        | "Accounting"
        | "Aerospace & Defense"
        | "Agriculture"
        | "Airlines"
        | "Alternative Medicine"
        | "Animation"
        | "Apparel & Footwear"
        | "Architecture"
        | "Arts"
        | "Arts & Crafts"
        | "Asset Management"
        | "Audio"
        | "Automation"
        | "Automotive"
        | "B2B"
        | "B2C"
        | "Banking & Mortgages"
        | "Beverages"
        | "Biotechnology"
        | "Broadcasting"
        | "Building Materials"
        | "Business Supplies"
        | "Chemicals"
        | "Civil Engineering"
        | "Cloud Services"
        | "Communications"
        | "Computer Hardware"
        | "Construction"
        | "Construction Contractors & Services"
        | "Consulting & Professional Services"
        | "Consumer Discretionary"
        | "Consumer Electronics"
        | "Consumer Goods"
        | "Consumer Staples"
        | "Corporate & Business"
        | "Cosmetics"
        | "Design"
        | "E-commerce"
        | "E-Commerce & Marketplaces"
        | "E-Learning"
        | "Education"
        | "Electrical"
        | "Energy"
        | "Energy & Utilities"
        | "Enterprise"
        | "Entertainment & Recreation"
        | "Events"
        | "Eyewear"
        | "Facilities"
        | "Family Services"
        | "Finance"
        | "Financial Services"
        | "Fine Art"
        | "Firearms"
        | "Fishery"
        | "Food"
        | "Food Production"
        | "Forums"
        | "Fundraising"
        | "Gambling & Casinos"
        | "Government"
        | "Ground Transportation"
        | "Health & Wellness"
        | "Health Care"
        | "Higher Education"
        | "Home & Furniture"
        | "Home Improvement"
        | "Human Resources"
        | "Import & Export"
        | "Industrials & Manufacturing"
        | "Information Technology & Services"
        | "Insurance"
        | "International Relations"
        | "International Trade"
        | "Internet"
        | "Investment"
        | "Investment Banking"
        | "Investment Management"
        | "ISP"
        | "Jewelry Watches & Luxury Goods"
        | "Judiciary"
        | "Law Enforcement"
        | "Legal Services"
        | "Libraries"
        | "Machinery"
        | "Maritime"
        | "Market Research"
        | "Marketing & Advertising"
        | "Marketplace"
        | "Mechanical Engineering"
        | "Media"
        | "Medicine"
        | "Military"
        | "Mining & Metals"
        | "Mobile"
        | "Movies & TV"
        | "Museums"
        | "Music"
        | "Nanotechnology"
        | "Networking"
        | "Non-Profit & Philanthropy"
        | "Oil & Gas"
        | "Outsourcing"
        | "Packaging & Containers"
        | "Paper Goods"
        | "Payments"
        | "Performing Arts"
        | "Pharmaceuticals"
        | "Pharmacy"
        | "Photography"
        | "Plastics"
        | "Plumbing"
        | "Political Organization"
        | "Pornography"
        | "Primary & Secondary Education"
        | "Printing"
        | "Public Relations"
        | "Publishing"
        | "Ranching"
        | "Real Estate"
        | "Religion"
        | "Renewables & Environment"
        | "Restaurants"
        | "Retail"
        | "SAAS"
        | "Sanitization Services"
        | "Scientific & Academic Research"
        | "Security"
        | "Services"
        | "Shipbuilding"
        | "Shipping & Logistics"
        | "Society"
        | "Sporting Goods"
        | "Sports & Fitness"
        | "Stores"
        | "Talent Agencies"
        | "Technology"
        | "Telecommunications"
        | "Textiles"
        | "Tobacco"
        | "Tools"
        | "Translation"
        | "Transportation"
        | "Travel & Leisure"
        | "Utilities"
        | "Venture Capital"
        | "Veterinary"
        | "Video Games"
        | "Warehousing"
        | "Web Services & Apps"
        | "Wholesale"
    )[]
    primary_location?: {
        [k: string]: unknown
    }
    logo_url?: string
    angellist?: string
    facebook?: string
    instagram?: string
    linkedin?: string
    twitter?: string
    twitter_follower_count?: number
    estimated_arr_usd?:
        | "$0-$1M"
        | "$1M-$10M"
        | "$10M-$50M"
        | "$50M-$100M"
        | "$100M-$250M"
        | "$250M-$500M"
        | "$500M-$1B"
        | "$1B-$10B"
        | "$10B+"
    funding_raised_usd?: number
    foundation_date?: string
    employee_range?: "1-10" | "11-50" | "51-250" | "251-1K" | "1K-5K" | "5K-10K" | "10K-50K" | "50K-100K" | "100K+"
    first_calendar_interaction?: unknown
    last_calendar_interaction?: unknown
    next_calendar_interaction?: unknown
    first_email_interaction?: unknown
    last_email_interaction?: unknown
    first_interaction?: unknown
    last_interaction?: unknown
    next_interaction?: unknown
    strongest_connection_strength_legacy?: number
    strongest_connection_strength?: "Very weak" | "Weak" | "Good" | "Strong" | "Very strong"
    strongest_connection_user?: AttioActorReferenceInput
    associated_deals?: AttioRecordReferenceInput[]
    associated_workspaces?: AttioRecordReferenceInput[]
    created_at?: string
    created_by?: AttioActorReferenceInput
}

export type AttioDealRecordValues = {
    record_id?: string
    name?: string
    stage?: AttioSelectOption
    owner?: AttioActorReference
    value?: AttioCurrencyValue
    associated_people?: AttioRecordReferenceValue[]
    associated_company?: AttioRecordReferenceValue
    created_at?: string
    created_by?: AttioActorReference
    trial_pipeline?: AttioSelectOption
    lead_key?: string
    metrics?: string
    economic_buyer?: string
    decision_criteria?: string
    decision_process?: string
    identify_pain?: string
    champion?: string
    competitors?: AttioSelectOption[]
    lost_reason?: string
    renewal_date?: string
}

export type AttioDealInputValues = {
    record_id?: string
    name?: string
    stage?: "Lead" | "In Progress" | "Won 🎉" | "Lost" | "Negotiation" | "Proposal"
    owner?: AttioActorReferenceInput
    value?: number
    associated_people?: AttioRecordReferenceInput[]
    associated_company?: AttioRecordReferenceInput
    created_at?: string
    created_by?: AttioActorReferenceInput
    trial_pipeline?: "Invited"
    lead_key?: string
    metrics?: string
    economic_buyer?: string
    decision_criteria?: string
    decision_process?: string
    identify_pain?: string
    champion?: string
    competitors?: ("Workato" | "Zapier Enterprise")[]
    lost_reason?: string
    renewal_date?: string
}

export type AttioUserRecordValues = {
    record_id?: string
    person?: AttioRecordReferenceValue
    primary_email_address?: string
    created_at?: string
    created_by?: AttioActorReference
    user_id?: string
    workspace?: AttioRecordReferenceValue[]
    first_name?: string
    last_name?: string
    full_name?: string
}

export type AttioUserInputValues = {
    record_id?: string
    person?: AttioRecordReferenceInput
    primary_email_address?: string
    created_at?: string
    created_by?: AttioActorReferenceInput
    user_id?: string
    workspace?: AttioRecordReferenceInput[]
    first_name?: string
    last_name?: string
    full_name?: string
}

export type AttioFeedbackRequestsEntryRecordValues = {
    entry_id?: string
    created_at?: string
    created_by?: AttioActorReference
}

export type AttioFeedbackRequestsEntryValues = {
    entry_id?: string
    created_at?: string
    created_by?: AttioActorReferenceInput
}

export type AttioICPProspectsEntryRecordValues = {
    entry_id?: string
    created_at?: string
    created_by?: AttioActorReference
}

export type AttioICPProspectsEntryValues = {
    entry_id?: string
    created_at?: string
    created_by?: AttioActorReferenceInput
}

export const AttioPersonConnectionStrength = {
    VeryWeak: "Very weak",
    Weak: "Weak",
    Good: "Good",
    Strong: "Strong",
    VeryStrong: "Very strong",
} as const

export const AttioPersonBuilderHealth = {
    PowerBuilder: "Power builder",
    Active: "Active",
    CoolingOff: "Cooling off",
    Dormant: "Dormant",
} as const

export const AttioPersonAutomationStatus = {
    Running: "Running",
    Stalled: "Stalled",
    NotRunning: "Not running",
} as const

export const AttioCompanyCategories = {
    _3DPrinting: "3D Printing",
    Accounting: "Accounting",
    AerospaceDefense: "Aerospace & Defense",
    Agriculture: "Agriculture",
    Airlines: "Airlines",
    AlternativeMedicine: "Alternative Medicine",
    Animation: "Animation",
    ApparelFootwear: "Apparel & Footwear",
    Architecture: "Architecture",
    Arts: "Arts",
    ArtsCrafts: "Arts & Crafts",
    AssetManagement: "Asset Management",
    Audio: "Audio",
    Automation: "Automation",
    Automotive: "Automotive",
    B2B: "B2B",
    B2C: "B2C",
    BankingMortgages: "Banking & Mortgages",
    Beverages: "Beverages",
    Biotechnology: "Biotechnology",
    Broadcasting: "Broadcasting",
    BuildingMaterials: "Building Materials",
    BusinessSupplies: "Business Supplies",
    Chemicals: "Chemicals",
    CivilEngineering: "Civil Engineering",
    CloudServices: "Cloud Services",
    Communications: "Communications",
    ComputerHardware: "Computer Hardware",
    Construction: "Construction",
    ConstructionContractorsServices: "Construction Contractors & Services",
    ConsultingProfessionalServices: "Consulting & Professional Services",
    ConsumerDiscretionary: "Consumer Discretionary",
    ConsumerElectronics: "Consumer Electronics",
    ConsumerGoods: "Consumer Goods",
    ConsumerStaples: "Consumer Staples",
    CorporateBusiness: "Corporate & Business",
    Cosmetics: "Cosmetics",
    Design: "Design",
    ECommerce: "E-commerce",
    ECommerceMarketplaces: "E-Commerce & Marketplaces",
    ELearning: "E-Learning",
    Education: "Education",
    Electrical: "Electrical",
    Energy: "Energy",
    EnergyUtilities: "Energy & Utilities",
    Enterprise: "Enterprise",
    EntertainmentRecreation: "Entertainment & Recreation",
    Events: "Events",
    Eyewear: "Eyewear",
    Facilities: "Facilities",
    FamilyServices: "Family Services",
    Finance: "Finance",
    FinancialServices: "Financial Services",
    FineArt: "Fine Art",
    Firearms: "Firearms",
    Fishery: "Fishery",
    Food: "Food",
    FoodProduction: "Food Production",
    Forums: "Forums",
    Fundraising: "Fundraising",
    GamblingCasinos: "Gambling & Casinos",
    Government: "Government",
    GroundTransportation: "Ground Transportation",
    HealthWellness: "Health & Wellness",
    HealthCare: "Health Care",
    HigherEducation: "Higher Education",
    HomeFurniture: "Home & Furniture",
    HomeImprovement: "Home Improvement",
    HumanResources: "Human Resources",
    ImportExport: "Import & Export",
    IndustrialsManufacturing: "Industrials & Manufacturing",
    InformationTechnologyServices: "Information Technology & Services",
    Insurance: "Insurance",
    InternationalRelations: "International Relations",
    InternationalTrade: "International Trade",
    Internet: "Internet",
    Investment: "Investment",
    InvestmentBanking: "Investment Banking",
    InvestmentManagement: "Investment Management",
    ISP: "ISP",
    JewelryWatchesLuxuryGoods: "Jewelry Watches & Luxury Goods",
    Judiciary: "Judiciary",
    LawEnforcement: "Law Enforcement",
    LegalServices: "Legal Services",
    Libraries: "Libraries",
    Machinery: "Machinery",
    Maritime: "Maritime",
    MarketResearch: "Market Research",
    MarketingAdvertising: "Marketing & Advertising",
    Marketplace: "Marketplace",
    MechanicalEngineering: "Mechanical Engineering",
    Media: "Media",
    Medicine: "Medicine",
    Military: "Military",
    MiningMetals: "Mining & Metals",
    Mobile: "Mobile",
    MoviesTV: "Movies & TV",
    Museums: "Museums",
    Music: "Music",
    Nanotechnology: "Nanotechnology",
    Networking: "Networking",
    NonProfitPhilanthropy: "Non-Profit & Philanthropy",
    OilGas: "Oil & Gas",
    Outsourcing: "Outsourcing",
    PackagingContainers: "Packaging & Containers",
    PaperGoods: "Paper Goods",
    Payments: "Payments",
    PerformingArts: "Performing Arts",
    Pharmaceuticals: "Pharmaceuticals",
    Pharmacy: "Pharmacy",
    Photography: "Photography",
    Plastics: "Plastics",
    Plumbing: "Plumbing",
    PoliticalOrganization: "Political Organization",
    Pornography: "Pornography",
    PrimarySecondaryEducation: "Primary & Secondary Education",
    Printing: "Printing",
    PublicRelations: "Public Relations",
    Publishing: "Publishing",
    Ranching: "Ranching",
    RealEstate: "Real Estate",
    Religion: "Religion",
    RenewablesEnvironment: "Renewables & Environment",
    Restaurants: "Restaurants",
    Retail: "Retail",
    SAAS: "SAAS",
    SanitizationServices: "Sanitization Services",
    ScientificAcademicResearch: "Scientific & Academic Research",
    Security: "Security",
    Services: "Services",
    Shipbuilding: "Shipbuilding",
    ShippingLogistics: "Shipping & Logistics",
    Society: "Society",
    SportingGoods: "Sporting Goods",
    SportsFitness: "Sports & Fitness",
    Stores: "Stores",
    TalentAgencies: "Talent Agencies",
    Technology: "Technology",
    Telecommunications: "Telecommunications",
    Textiles: "Textiles",
    Tobacco: "Tobacco",
    Tools: "Tools",
    Translation: "Translation",
    Transportation: "Transportation",
    TravelLeisure: "Travel & Leisure",
    Utilities: "Utilities",
    VentureCapital: "Venture Capital",
    Veterinary: "Veterinary",
    VideoGames: "Video Games",
    Warehousing: "Warehousing",
    WebServicesApps: "Web Services & Apps",
    Wholesale: "Wholesale",
} as const

export const AttioCompanyEstimatedARR = {
    _01M: "$0-$1M",
    _1M10M: "$1M-$10M",
    _10M50M: "$10M-$50M",
    _50M100M: "$50M-$100M",
    _100M250M: "$100M-$250M",
    _250M500M: "$250M-$500M",
    _500M1B: "$500M-$1B",
    _1B10B: "$1B-$10B",
    _10B: "$10B+",
} as const

export const AttioCompanyEmployeeRange = {
    _110: "1-10",
    _1150: "11-50",
    _51250: "51-250",
    _2511K: "251-1K",
    _1K5K: "1K-5K",
    _5K10K: "5K-10K",
    _10K50K: "10K-50K",
    _50K100K: "50K-100K",
    _100K: "100K+",
} as const

export const AttioCompanyConnectionStrength = {
    VeryWeak: "Very weak",
    Weak: "Weak",
    Good: "Good",
    Strong: "Strong",
    VeryStrong: "Very strong",
} as const

export const AttioDealStage = {
    Lead: "Lead",
    InProgress: "In Progress",
    Won: "Won 🎉",
    Lost: "Lost",
    Negotiation: "Negotiation",
    Proposal: "Proposal",
} as const

export const AttioDealTrialPipeline = {
    Invited: "Invited",
} as const

export const AttioDealCompetitors = {
    Workato: "Workato",
    ZapierEnterprise: "Zapier Enterprise",
} as const

export type AttioAttributeDefinition<TSlug extends string = string, TType extends string = string> = {
    apiSlug: TSlug
    title?: string
    type?: TType
    isRequired?: boolean
    isUnique?: boolean
}

export class AttioObject<
    TSlug extends string = string,
    TRecordValues extends Record<string, unknown> = Record<string, unknown>,
    TInputValues extends Record<string, unknown> = TRecordValues
> {
    constructor(
        public readonly apiSlug: TSlug,
        public readonly name: string,
        public readonly objectId: string,
        public readonly attributes: readonly AttioAttributeDefinition[] = []
    ) {}

    declare readonly __recordValues: TRecordValues
    declare readonly __inputValues: TInputValues

    static Workspace = new AttioObject<"workspaces", AttioWorkspaceRecordValues, AttioWorkspaceInputValues>("workspaces", "Workspace", "1438f767-a019-4481-988c-a8b9652e9316", [
        { apiSlug: "record_id", title: "Record ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "workspace_id", title: "Workspace ID", type: "text", isRequired: true, isUnique: true },
        { apiSlug: "name", title: "Name", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "users", title: "Users", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "company", title: "Company", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "avatar_url", title: "Avatar URL", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "created_at", title: "Created at", type: "timestamp", isRequired: false, isUnique: false },
        { apiSlug: "created_by", title: "Created by", type: "actor-reference", isRequired: false, isUnique: false }
    ])
    static Person = new AttioObject<"people", AttioPersonRecordValues, AttioPersonInputValues>("people", "Person", "1bcfaec9-d780-435d-8088-05032f38cf71", [
        { apiSlug: "record_id", title: "Record ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "name", title: "Name", type: "personal-name", isRequired: false, isUnique: false },
        { apiSlug: "email_addresses", title: "Email addresses", type: "email-address", isRequired: false, isUnique: true },
        { apiSlug: "description", title: "Description", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "company", title: "Company", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "job_title", title: "Job title", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "avatar_url", title: "Avatar URL", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "phone_numbers", title: "Phone numbers", type: "phone-number", isRequired: false, isUnique: false },
        { apiSlug: "primary_location", title: "Primary location", type: "location", isRequired: false, isUnique: false },
        { apiSlug: "angellist", title: "AngelList", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "facebook", title: "Facebook", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "instagram", title: "Instagram", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "linkedin", title: "LinkedIn", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "twitter", title: "Twitter", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "twitter_follower_count", title: "Twitter follower count", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "first_calendar_interaction", title: "First calendar interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "last_calendar_interaction", title: "Last calendar interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "next_calendar_interaction", title: "Next calendar interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "first_email_interaction", title: "First email interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "last_email_interaction", title: "Last email interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "first_interaction", title: "First interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "last_interaction", title: "Last interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "next_interaction", title: "Next interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "strongest_connection_strength_legacy", title: "Connection strength (legacy)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "strongest_connection_strength", title: "Connection strength", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "strongest_connection_user", title: "Strongest connection", type: "actor-reference", isRequired: false, isUnique: false },
        { apiSlug: "associated_deals", title: "Associated deals", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "associated_users", title: "Associated users", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "created_at", title: "Created at", type: "timestamp", isRequired: false, isUnique: false },
        { apiSlug: "created_by", title: "Created by", type: "actor-reference", isRequired: false, isUnique: false },
        { apiSlug: "posthog_health_status", title: "Builder health", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "posthog_last_built", title: "Last built (PostHog)", type: "timestamp", isRequired: false, isUnique: false },
        { apiSlug: "posthog_builder_actions_7d", title: "Builder actions (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_builder_trend_wow", title: "Builder trend WoW %", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_jobs_run_7d", title: "Jobs run (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_jobs_completed_7d", title: "Jobs completed (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_job_failures_7d", title: "Job failures (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_deploy_failures_7d", title: "Deploy failures (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_automation_status", title: "Automation status", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "posthog_integrations_added_7d", title: "Integrations added (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_agent_runs_7d", title: "Agent runs (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_agent_actions_7d", title: "Agent actions (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_projects_created_7d", title: "Projects created (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_projects_deployed_7d", title: "Projects deployed (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_jobs_created_7d", title: "Jobs created (7d)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "posthog_cli_logins_7d", title: "CLI logins (7d)", type: "number", isRequired: false, isUnique: false }
    ])
    static Company = new AttioObject<"companies", AttioCompanyRecordValues, AttioCompanyInputValues>("companies", "Company", "32b97358-5905-46af-963b-83fc48bd8188", [
        { apiSlug: "record_id", title: "Record ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "domains", title: "Domains", type: "domain", isRequired: false, isUnique: true },
        { apiSlug: "name", title: "Name", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "description", title: "Description", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "team", title: "Team", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "categories", title: "Categories", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "primary_location", title: "Primary location", type: "location", isRequired: false, isUnique: false },
        { apiSlug: "logo_url", title: "Logo URL", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "angellist", title: "AngelList", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "facebook", title: "Facebook", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "instagram", title: "Instagram", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "linkedin", title: "LinkedIn", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "twitter", title: "Twitter", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "twitter_follower_count", title: "Twitter follower count", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "estimated_arr_usd", title: "Estimated ARR", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "funding_raised_usd", title: "Funding raised", type: "currency", isRequired: false, isUnique: false },
        { apiSlug: "foundation_date", title: "Foundation date", type: "date", isRequired: false, isUnique: false },
        { apiSlug: "employee_range", title: "Employee range", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "first_calendar_interaction", title: "First calendar interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "last_calendar_interaction", title: "Last calendar interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "next_calendar_interaction", title: "Next calendar interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "first_email_interaction", title: "First email interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "last_email_interaction", title: "Last email interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "first_interaction", title: "First interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "last_interaction", title: "Last interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "next_interaction", title: "Next interaction", type: "interaction", isRequired: false, isUnique: false },
        { apiSlug: "strongest_connection_strength_legacy", title: "Connection strength (legacy)", type: "number", isRequired: false, isUnique: false },
        { apiSlug: "strongest_connection_strength", title: "Connection strength", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "strongest_connection_user", title: "Strongest connection", type: "actor-reference", isRequired: false, isUnique: false },
        { apiSlug: "associated_deals", title: "Associated deals", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "associated_workspaces", title: "Associated workspaces", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "created_at", title: "Created at", type: "timestamp", isRequired: false, isUnique: false },
        { apiSlug: "created_by", title: "Created by", type: "actor-reference", isRequired: false, isUnique: false }
    ])
    static Deal = new AttioObject<"deals", AttioDealRecordValues, AttioDealInputValues>("deals", "Deal", "3aa184f1-23e9-445d-bbb7-13ea0fac7bf4", [
        { apiSlug: "record_id", title: "Record ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "name", title: "Deal name", type: "text", isRequired: true, isUnique: false },
        { apiSlug: "stage", title: "Deal stage", type: "status", isRequired: true, isUnique: false },
        { apiSlug: "owner", title: "Deal owner", type: "actor-reference", isRequired: true, isUnique: false },
        { apiSlug: "value", title: "Deal value", type: "currency", isRequired: false, isUnique: false },
        { apiSlug: "associated_people", title: "Associated people", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "associated_company", title: "Associated company", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "created_at", title: "Created at", type: "timestamp", isRequired: false, isUnique: false },
        { apiSlug: "created_by", title: "Created by", type: "actor-reference", isRequired: false, isUnique: false },
        { apiSlug: "trial_pipeline", title: "Trial Pipeline", type: "status", isRequired: false, isUnique: false },
        { apiSlug: "lead_key", title: "Lead key", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "metrics", title: "Metrics", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "economic_buyer", title: "Economic Buyer", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "decision_criteria", title: "Decision Criteria", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "decision_process", title: "Decision Process", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "identify_pain", title: "Identify Pain", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "champion", title: "Champion", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "competitors", title: "Competitors", type: "select", isRequired: false, isUnique: false },
        { apiSlug: "lost_reason", title: "Lost Reason", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "renewal_date", title: "Renewal date", type: "date", isRequired: false, isUnique: false }
    ])
    static User = new AttioObject<"users", AttioUserRecordValues, AttioUserInputValues>("users", "User", "adaa14a2-967b-4101-8a95-31b68087379a", [
        { apiSlug: "record_id", title: "Record ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "person", title: "Person", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "primary_email_address", title: "Primary email address", type: "email-address", isRequired: true, isUnique: true },
        { apiSlug: "created_at", title: "Created at", type: "timestamp", isRequired: false, isUnique: false },
        { apiSlug: "created_by", title: "Created by", type: "actor-reference", isRequired: false, isUnique: false },
        { apiSlug: "user_id", title: "User ID", type: "text", isRequired: true, isUnique: true },
        { apiSlug: "workspace", title: "Workspaces", type: "record-reference", isRequired: false, isUnique: false },
        { apiSlug: "first_name", title: "First Name", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "last_name", title: "Last Name", type: "text", isRequired: false, isUnique: false },
        { apiSlug: "full_name", title: "Full Name", type: "text", isRequired: false, isUnique: false }
    ])
}

export type GeneratedAttioObject =
    | typeof AttioObject.Workspace
    | typeof AttioObject.Person
    | typeof AttioObject.Company
    | typeof AttioObject.Deal
    | typeof AttioObject.User

export class AttioList<
    TSlug extends string = string,
    TEntryValues extends Record<string, unknown> = Record<string, unknown>,
    TEntryRecordValues extends Record<string, unknown> = TEntryValues
> {
    constructor(
        public readonly apiSlug: TSlug,
        public readonly name: string,
        public readonly listId: string,
        public readonly parentObject: string,
        public readonly attributes: readonly AttioAttributeDefinition[] = []
    ) {}

    declare readonly __entryValues: TEntryValues
    declare readonly __entryRecordValues: TEntryRecordValues

    static FeedbackRequests = new AttioList<"feedback_requests", AttioFeedbackRequestsEntryValues, AttioFeedbackRequestsEntryRecordValues>("feedback_requests", "Feedback Requests", "ee49fa72-4e4e-41b6-8c60-2d0e23a464cf", "people", [
        { apiSlug: "entry_id", title: "Entry ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "created_at", title: "Added to list at", type: "timestamp", isRequired: true, isUnique: false },
        { apiSlug: "created_by", title: "Added to list by", type: "actor-reference", isRequired: false, isUnique: false }
    ])
    static ICPProspects = new AttioList<"icp_prospects", AttioICPProspectsEntryValues, AttioICPProspectsEntryRecordValues>("icp_prospects", "ICP Prospects", "d56f425e-cb02-478e-bd00-73574aa1231c", "people", [
        { apiSlug: "entry_id", title: "Entry ID", type: "text", isRequired: false, isUnique: true },
        { apiSlug: "created_at", title: "Added to list at", type: "timestamp", isRequired: true, isUnique: false },
        { apiSlug: "created_by", title: "Added to list by", type: "actor-reference", isRequired: false, isUnique: false }
    ])
}

export type GeneratedAttioList =
    | typeof AttioList.FeedbackRequests
    | typeof AttioList.ICPProspects

// ── Attio type machinery ──────────────────────────────────────

export interface AttioRecordBase {
    id?: {
        workspace_id?: string
        object_id?: string
        record_id?: string
    }
    record_id?: string
    values?: {
        [k: string]: unknown
    }
    web_url?: string
    created_at?: string
}

export interface AttioSearchMatch {
    id?: {
        workspace_id?: string
        object_id?: string
        record_id?: string
        [k: string]: unknown
    }
    record_text?: string
    object_slug?: string
    [k: string]: unknown
}

export interface AttioAttributeHistoryEntry {
    active_from: string
    active_until: string | null
    attribute_type?: string
    [k: string]: unknown
}

export interface AttioTask {
    id: {
        workspace_id: string
        task_id: string
    }
    content_plaintext: string
    deadline_at: string | null
    is_completed: boolean
    linked_records: {
        target_object_id: string
        target_record_id: string
        [k: string]: unknown
    }[]
    assignees: {
        referenced_actor_type: string
        referenced_actor_id: string | null
        [k: string]: unknown
    }[]
    created_at: string
    [k: string]: unknown
}

export interface AttioNote {
    id: {
        workspace_id: string
        note_id: string
    }
    parent_object: string
    parent_record_id: string
    title: string
    content_plaintext: string | null
    content_markdown: string | null
    created_at: string
    [k: string]: unknown
}

export interface AttioComment {
    id: {
        workspace_id: string
        comment_id: string
    }
    thread_id: string
    content_plaintext: string
    author: {
        [k: string]: unknown
    }
    resolved_at: string | null
    created_at: string
    [k: string]: unknown
}

export interface AttioThread {
    id: {
        workspace_id: string
        thread_id: string
    }
    comments: AttioComment[]
    created_at: string
    [k: string]: unknown
}

export interface AttioMeeting {
    id: {
        workspace_id: string
        meeting_id: string
    }
    title: string | null
    description?: string | null
    is_all_day?: boolean
    start?: {
        datetime?: string
        timezone?: string | null
        date?: string
        [k: string]: unknown
    }
    end?: {
        datetime?: string
        timezone?: string | null
        date?: string
        [k: string]: unknown
    }
    participants: {
        [k: string]: unknown
    }[]
    linked_records: {
        [k: string]: unknown
    }[]
    created_at: string
    [k: string]: unknown
}

export interface AttioCallRecording {
    id: {
        workspace_id: string
        meeting_id: string
        call_recording_id: string
    }
    status: string
    created_at: string
    [k: string]: unknown
}

export interface AttioTranscript {
    id?: {
        workspace_id: string
        meeting_id: string
        call_recording_id: string
    }
    transcript: {
        speech: string
        start_time?: number
        end_time?: number
        [k: string]: unknown
    }[]
    [k: string]: unknown
}

export interface AttioFile {
    id: {
        [k: string]: unknown
    }
    name: string
    content_type?: string | null
    content_size?: number | null
    record_id?: string
    object_slug?: string
    created_at: string
    [k: string]: unknown
}

export interface AttioObjectSummary {
    id: {
        workspace_id: string
        object_id: string
    }
    api_slug: string
    singular_noun: string
    plural_noun: string
}

export interface AttioObjectInfo {
    id: {
        workspace_id: string
        object_id: string
    }
    api_slug: string
    singular_noun: string
    plural_noun: string
    attributes?: AttioAttributeInfo[]
}

export interface AttioAttributeInfo {
    api_slug?: string
    title?: string
    description?: string | null
    type?: string
    is_required?: boolean
    is_unique?: boolean
    is_multiselect?: boolean
    options?: string[]
    [k: string]: unknown
}

export interface AttioStatusEntity {
    id: {
        workspace_id?: string
        object_id?: string
        attribute_id?: string
        status_id?: string
        [k: string]: unknown
    }
    title: string
    is_archived: boolean
    [k: string]: unknown
}

export interface AttioSelectOptionEntity {
    id: {
        workspace_id?: string
        object_id?: string
        attribute_id?: string
        option_id?: string
        [k: string]: unknown
    }
    title: string
    is_archived: boolean
    [k: string]: unknown
}

export interface AttioWorkspaceMember {
    id: {
        workspace_id: string
        workspace_member_id: string
    }
    first_name: string | null
    last_name: string | null
    avatar_url: string | null
    email_address: string
    access_level: string
    created_at: string
    [k: string]: unknown
}

export interface AttioListInfo {
    id: {
        workspace_id: string
        list_id: string
    }
    api_slug: string
    name: string
    parent_object: string[] | string
    created_at: string
    web_url?: string
    [k: string]: unknown
}

export interface AttioListEntryInfo {
    id: {
        workspace_id: string
        list_id: string
        entry_id: string
    }
    parent_record_id: string
    parent_object: string
    entry_values: {
        [k: string]: unknown
    }
    created_at: string
    [k: string]: unknown
}

export interface AttioRecordsResult {
    actions?: RunHistoryAction[]
    records?: AttioRecordBase[]
    record?: AttioRecordBase
    matches?: AttioSearchMatch[]
    history?: AttioAttributeHistoryEntry[]
    count?: number
    offset?: number
}

export interface AttioWorkspaceMembersResult {
    actions?: RunHistoryAction[]
    members?: AttioWorkspaceMember[]
    member?: AttioWorkspaceMember
    count?: number
}

export interface AttioTasksOutput {
    actions?: RunHistoryAction[]
    tasks?: AttioTask[]
    task?: AttioTask
    count?: number
}

export interface AttioNotesOutput {
    actions?: RunHistoryAction[]
    notes?: AttioNote[]
    note?: AttioNote
    count?: number
}

export interface AttioCommentsOutput {
    actions?: RunHistoryAction[]
    comment?: AttioComment
    threads?: AttioThread[]
    thread?: AttioThread
    count?: number
}

export interface AttioListsResult {
    actions?: RunHistoryAction[]
    lists?: AttioListInfo[]
    list?: AttioListInfo
    entries?: AttioListEntryInfo[]
    entry?: AttioListEntryInfo
    count?: number
    offset?: number
}

export interface AttioMeetingsOutput {
    actions?: RunHistoryAction[]
    meetings?: AttioMeeting[]
    meeting?: AttioMeeting
    recordings?: AttioCallRecording[]
    transcript?: AttioTranscript
    count?: number
    nextCursor?: string | null
}

export interface AttioFilesOutput {
    actions?: RunHistoryAction[]
    files?: AttioFile[]
    file?: AttioFile
    downloadUrl?: string
    count?: number
    nextCursor?: string | null
}

export interface AttioSchemaOutput {
    actions?: RunHistoryAction[]
    objects?: AttioObjectInfo[]
    object?: AttioObjectSummary
    attributes?: AttioAttributeInfo[]
    attribute?: AttioAttributeInfo
    statuses?: AttioStatusEntity[]
    status?: AttioStatusEntity
    selectOptions?: AttioSelectOptionEntity[]
    selectOption?: AttioSelectOptionEntity
    count?: number
}

export interface AttioListWorkspaceMembersParams {}

export interface AttioGetWorkspaceMemberParams {
    /**
     * The workspace member ID (UUID).
     */
    workspaceMemberId: string
}

export interface AttioListTasksParams {
    /**
     * Filter to tasks linked to records of this object slug. Requires linkedRecordId.
     */
    linkedObjectSlug?: string | null
    /**
     * Filter to tasks linked to this record ID.
     */
    linkedRecordId?: string | null
    /**
     * Filter by completion state. Omit for all tasks.
     */
    isCompleted?: boolean | null
    /**
     * Maximum tasks to return.
     */
    limit?: number | null
    /**
     * Number of tasks to skip, for pagination.
     */
    offset?: number | null
}

export interface AttioGetTaskParams {
    taskId: string
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioCreateTaskParams {
    /**
     * The task text (plaintext, max 2000 chars).
     */
    content: string
    /**
     * Deadline as an ISO 8601 timestamp, or null for no deadline.
     */
    deadlineAt?: string | null
    /**
     * Whether the task starts completed. Defaults to false.
     */
    isCompleted?: boolean | null
    /**
     * Workspace member email addresses or member IDs (UUIDs) to assign.
     */
    assignees?: string[] | null
    /**
     * Records to link the task to.
     */
    linkedRecords?:
        | {
              /**
               * The object type slug of the record (e.g. 'people', 'companies').
               */
              objectSlug: string
              /**
               * The record ID (UUID).
               */
              recordId: string
          }[]
        | null
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioUpdateTaskParams {
    taskId: string
    /**
     * New deadline (ISO 8601), or null to clear.
     */
    deadlineAt?: string | null
    /**
     * New completion state. Omit to leave unchanged.
     */
    isCompleted?: boolean | null
    /**
     * Replacement assignee emails/IDs. Omit to leave unchanged.
     */
    assignees?: string[] | null
    /**
     * Replacement linked records. Omit to leave unchanged.
     */
    linkedRecords?:
        | {
              /**
               * The object type slug of the record (e.g. 'people', 'companies').
               */
              objectSlug: string
              /**
               * The record ID (UUID).
               */
              recordId: string
          }[]
        | null
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioDeleteTaskParams {
    taskId: string
}

export interface AttioListNotesParams {
    /**
     * Filter to notes on records of this object slug. Requires parentRecordId.
     */
    parentObjectSlug?: string | null
    /**
     * Filter to notes on this record ID.
     */
    parentRecordId?: string | null
    limit?: number | null
    offset?: number | null
}

export interface AttioGetNoteParams {
    noteId: string
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioCreateNoteParams {
    /**
     * The object type slug of the record the note belongs to.
     */
    parentObjectSlug: string
    /**
     * The record ID the note belongs to.
     */
    parentRecordId: string
    /**
     * The note title.
     */
    title: string
    /**
     * The note body.
     */
    content: string
    /**
     * Content format. Defaults to markdown.
     */
    format?: ("plaintext" | "markdown") | null
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioDeleteNoteParams {
    noteId: string
}

export interface AttioGetCommentParams {
    commentId: string
}

export interface AttioListThreadsParams {
    /**
     * With recordId: threads on this record.
     */
    objectSlug?: string | null
    recordId?: string | null
    limit?: number | null
    offset?: number | null
}

export interface AttioGetThreadParams {
    threadId: string
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioCreateCommentParams {
    /**
     * The comment text (plaintext).
     */
    content: string
    /**
     * The workspace member ID the comment is authored as. Use attio_workspace_members to find it.
     */
    authorWorkspaceMemberId: string
    /**
     * Reply to this thread. Pass null/omit when commenting on a record.
     */
    threadId?: string | null
    /**
     * With recordId: start a new comment thread on this record.
     */
    objectSlug?: string | null
    recordId?: string | null
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioDeleteCommentParams {
    commentId: string
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioCreateListParams {
    /**
     * Display name of the list.
     */
    name: string
    /**
     * Unique slug for the list (snake_case).
     */
    apiSlug: string
    /**
     * The object the list contains records of (e.g. 'companies').
     */
    parentObjectSlug: string
    /**
     * Workspace-wide access level. Defaults to full-access.
     */
    workspaceAccess?: ("full-access" | "read-and-write" | "read-only") | null
}

export interface AttioListMeetingsParams {
    linkedObjectSlug?: string | null
    linkedRecordId?: string | null
    /**
     * Comma-separated participant email addresses.
     */
    participants?: string | null
    /**
     * Only meetings starting before this ISO timestamp.
     */
    startsBefore?: string | null
    /**
     * Only meetings ending at/after this ISO timestamp.
     */
    endsFrom?: string | null
    /**
     * Maximum meetings to return (max 200).
     */
    limit?: number | null
    /**
     * Pagination cursor from a previous response's nextCursor.
     */
    cursor?: string | null
}

export interface AttioGetMeetingParams {
    meetingId: string
}

export interface AttioListCallRecordingsParams {
    meetingId: string
    limit?: number | null
    cursor?: string | null
}

export interface AttioGetCallTranscriptParams {
    meetingId: string
    callRecordingId: string
    cursor?: string | null
}

export interface AttioListFilesParams {
    /**
     * Object slug of the record.
     */
    objectSlug: string
    /**
     * Record ID.
     */
    recordId: string
    limit?: number | null
    cursor?: string | null
}

export interface AttioGetFileParams {
    fileId: string
}

export interface AttioGetFileDownloadUrlParams {
    fileId: string
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioUploadFileParams {
    objectSlug: string
    recordId: string
    /**
     * File name including extension.
     */
    fileName: string
    /**
     * The file content, base64-encoded.
     */
    contentBase64: string
    /**
     * MIME type. Defaults to application/octet-stream.
     */
    contentType?: string | null
}

/**
 * The operation to perform and its arguments.
 */
export interface AttioDeleteFileParams {
    fileId: string
}

export interface AttioListObjectsParams {}

export interface AttioGetObjectParams {
    objectSlug: string
}

export interface AttioListAttributesParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
}

export interface AttioListStatusesParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
}

export interface AttioListSelectOptionsParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
}

export interface AttioCreateObjectParams {
    /**
     * Unique slug (snake_case).
     */
    apiSlug: string
    /**
     * Singular display name (e.g. 'Ticket').
     */
    singularNoun: string
    /**
     * Plural display name (e.g. 'Tickets').
     */
    pluralNoun: string
}

export interface AttioUpdateObjectParams {
    objectSlug: string
    newApiSlug?: string | null
    singularNoun?: string | null
    pluralNoun?: string | null
}

export interface AttioCreateAttributeParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    /**
     * Display name of the attribute.
     */
    title: string
    /**
     * Unique attribute slug (snake_case).
     */
    apiSlug: string
    /**
     * Attio attribute type, e.g. 'text', 'number', 'checkbox', 'currency', 'date', 'timestamp', 'rating', 'status', 'select', 'record-reference', 'actor-reference', 'location', 'domain', 'email-address', 'phone-number'.
     */
    attributeType: string
    /**
     * Text description of the attribute, shown in the Attio UI.
     */
    description?: string | null
    /**
     * Whether a value is required. Defaults to false.
     */
    isRequired?: boolean | null
    /**
     * Whether values must be unique. Defaults to false.
     */
    isUnique?: boolean | null
    /**
     * Whether the attribute holds multiple values. Defaults to false.
     */
    isMultiselect?: boolean | null
    /**
     * Optional JSON object string for a default value, e.g. '{"type":"dynamic","template":"current-user"}' or '{"type":"static","template":[...]}'.
     */
    defaultValue?: string | null
    /**
     * Optional JSON object string creating the paired attribute of a bidirectional record-reference, e.g. '{"object":"companies","title":"Projects","api_slug":"projects","is_multiselect":true}'.
     */
    relationship?: string | null
    /**
     * Optional JSON object string for type-specific config, e.g. '{"record_reference":{"allowed_objects":["people"]}}'.
     */
    config?: string | null
}

export interface AttioUpdateAttributeParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
    title?: string | null
    /**
     * New unique attribute slug (snake_case).
     */
    newApiSlug?: string | null
    /**
     * Text description of the attribute. Pass an empty string to clear it.
     */
    description?: string | null
    isRequired?: boolean | null
    isUnique?: boolean | null
    /**
     * Archive or restore the attribute.
     */
    isArchived?: boolean | null
    /**
     * Optional JSON object string for a default value, e.g. '{"type":"dynamic","template":"current-user"}'.
     */
    defaultValue?: string | null
    /**
     * Optional JSON object string for type-specific config, e.g. '{"currency":{"default_currency_code":"USD","display_type":"symbol"}}'.
     */
    config?: string | null
}

export interface AttioCreateStatusParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
    /**
     * The status title.
     */
    title: string
    /**
     * Whether arriving at this status triggers a celebration effect. Defaults to false.
     */
    celebrationEnabled?: boolean | null
    /**
     * Target time a record should spend in this status, as an ISO-8601 duration (e.g. 'P7D').
     */
    targetTimeInStatus?: string | null
}

export interface AttioUpdateStatusParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
    /**
     * The status ID (UUID).
     */
    statusId: string
    title?: string | null
    /**
     * Whether arriving at this status triggers a celebration effect.
     */
    celebrationEnabled?: boolean | null
    /**
     * Target time a record should spend in this status, as an ISO-8601 duration (e.g. 'P7D').
     */
    targetTimeInStatus?: string | null
    isArchived?: boolean | null
}

export interface AttioCreateSelectOptionParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
    /**
     * The option title.
     */
    title: string
}

export interface AttioUpdateSelectOptionParams {
    /**
     * Whether the attribute lives on an object or a list.
     */
    target: "objects" | "lists"
    /**
     * The object slug (e.g. 'deals') or list ID/slug the attribute belongs to.
     */
    identifier: string
    attributeSlug: string
    /**
     * The option ID (UUID).
     */
    optionId: string
    title?: string | null
    isArchived?: boolean | null
}

export type __AttioPrimitive = string | number | boolean | null
export type __AttioStructuredValue = Record<string, unknown>
export type __AttioValue = __AttioPrimitive | __AttioStructuredValue | (__AttioPrimitive | __AttioStructuredValue)[]
export type __AttioFilterAtom<T> = T extends AttioSelectOption ? string : T extends AttioActorReference ? string : T extends AttioRecordReferenceValue ? string : T extends AttioCurrencyValue ? number : T
export type __AttioFilterShorthand<T> = T extends (infer U)[] ? __AttioFilterAtom<U> | __AttioFilterAtom<U>[] : __AttioFilterAtom<T>
export type __AttioFilterValue<T> = __AttioFilterShorthand<T> | { $eq?: __AttioFilterShorthand<T>; $contains?: string; $starts_with?: string; $ends_with?: string } | Record<string, unknown>
export type __AttioFilterExpression<TValues extends Record<string, unknown>> = Partial<{ [K in keyof TValues]: __AttioFilterValue<TValues[K]> }> & { $and?: Array<__AttioFilterExpression<TValues>>; $or?: Array<__AttioFilterExpression<TValues>> }
export type __AttioRecordWithValues<TValues extends Record<string, unknown>> = Omit<AttioRecordBase, "values"> & TValues & { values: TValues; attributes: TValues }

export type AttioInputValuesByObject = {
    "workspaces": AttioWorkspaceInputValues
    "people": AttioPersonInputValues
    "companies": AttioCompanyInputValues
    "deals": AttioDealInputValues
    "users": AttioUserInputValues
}

export type AttioRecordValuesByObject = {
    "workspaces": AttioWorkspaceRecordValues
    "people": AttioPersonRecordValues
    "companies": AttioCompanyRecordValues
    "deals": AttioDealRecordValues
    "users": AttioUserRecordValues
}

export type AttioFilterByObject = {
    "workspaces": __AttioFilterExpression<AttioRecordValuesByObject["workspaces"]>
    "people": __AttioFilterExpression<AttioRecordValuesByObject["people"]>
    "companies": __AttioFilterExpression<AttioRecordValuesByObject["companies"]>
    "deals": __AttioFilterExpression<AttioRecordValuesByObject["deals"]>
    "users": __AttioFilterExpression<AttioRecordValuesByObject["users"]>
}

export type AttioRecordByObject = {
    "workspaces": __AttioRecordWithValues<AttioRecordValuesByObject["workspaces"]>
    "people": __AttioRecordWithValues<AttioRecordValuesByObject["people"]>
    "companies": __AttioRecordWithValues<AttioRecordValuesByObject["companies"]>
    "deals": __AttioRecordWithValues<AttioRecordValuesByObject["deals"]>
    "users": __AttioRecordWithValues<AttioRecordValuesByObject["users"]>
}

export type AttioValuesFor<TObject extends GeneratedAttioObject = GeneratedAttioObject> = TObject extends { __inputValues: infer TInputValues } ? TInputValues : AttioInputValuesByObject[TObject["apiSlug"]]
export type AttioRecordValuesFor<TObject extends GeneratedAttioObject = GeneratedAttioObject> = TObject extends { __recordValues: infer TRecordValues } ? TRecordValues : AttioRecordValuesByObject[TObject["apiSlug"]]
export type AttioAttributeSlug<TObject extends GeneratedAttioObject = GeneratedAttioObject> = Extract<keyof AttioValuesFor<TObject>, string>
export type AttioFilterFor<TObject extends GeneratedAttioObject = GeneratedAttioObject> = __AttioFilterExpression<AttioRecordValuesFor<TObject>>
export type AttioRecordFor<TObject extends GeneratedAttioObject = GeneratedAttioObject> = __AttioRecordWithValues<AttioRecordValuesFor<TObject>>
export type AttioQueryRecordsParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; filter?: AttioFilterFor<TObject> | null; limit?: number | null; offset?: number | null }
export type AttioSearchRecordsParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; query: string; limit?: number | null }
export type AttioGetRecordParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; recordId: string }
export type AttioCreateRecordParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; values: AttioValuesFor<TObject> }
export type AttioUpdateRecordParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; recordId: string; values: Partial<AttioValuesFor<TObject>>; multiselectMode?: "overwrite" | "append" | null }
export type AttioUpsertRecordParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; matchingAttribute: AttioAttributeSlug<TObject>; records: AttioValuesFor<TObject>[] }
export type AttioDeleteRecordParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; recordId: string }
export type AttioGetAttributeHistoryParams<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { object: TObject; recordId: string; attribute: AttioAttributeSlug<TObject>; limit?: number | null; offset?: number | null }
export type AttioQueryRecordsResult<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { records: Array<AttioRecordFor<TObject>>; count: number; offset: number }
export type AttioSearchRecordsResult = { matches: NonNullable<AttioRecordsResult["matches"]>; count: number }
export type AttioUpsertRecordResult<TObject extends GeneratedAttioObject = GeneratedAttioObject> = { records: Array<AttioRecordFor<TObject>>; count: number }
export type AttioSingleRecordResult<TObject extends GeneratedAttioObject = GeneratedAttioObject> = AttioRecordFor<TObject>
export type AttioEntryValuesFor<TList> = TList extends { __entryValues: infer TValues } ? TValues : Record<string, unknown>
export type AttioEntryRecordValuesFor<TList> = TList extends { __entryRecordValues: infer TValues extends Record<string, unknown> } ? TValues : Record<string, unknown>
export type AttioEntryFilterFor<TList> = __AttioFilterExpression<AttioEntryRecordValuesFor<TList>>
export type AttioListEntryFor<TList> = { id: { workspace_id: string; list_id: string; entry_id: string }; parent_record_id: string; parent_object: string; created_at: string; entry_values: AttioEntryRecordValuesFor<TList> }
export type AttioListEntriesResult<TList> = { entries: Array<AttioListEntryFor<TList>>; count: number; offset: number }
export type AttioListEntryResult<TList> = AttioListEntryFor<TList>
export type __AttioSingleValue<T> = T extends (infer U)[] ? U : T
export type AttioAttributeHistoryEntryFor<TValue> = { active_from: string; active_until: string | null; value: TValue }
export type AttioAttributeHistoryResult<TValue = unknown> = { history: Array<AttioAttributeHistoryEntryFor<TValue>>; count: number }