// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

// ── Shared types ──────────────────────────────────────────────

export interface RunHistoryAction {
    action: string
    integration:
        | "github"
        | "hey_reach"
        | "resend"
        | "apollo"
        | "gmail"
        | "linear"
        | "slack"
        | "notion"
        | "terse"
        | "posthog"
        | "datadog"
        | "cron_job"
        | "launchdarkly"
        | "workos"
        | "attio"
        | "snowflake"
        | "webhook"
        | "webmonitor"
    target: string
    details: string
    url?: string
    step_id?: string
    type: "create" | "update" | "delete" | "read" | "approve" | "error"
    isReadOnly?: boolean
    output_items?: {
        output_item_id: string
        output_item_type:
            | "gmail"
            | "gmail_output"
            | "gmail_draft_output"
            | "slack"
            | "slack_output"
            | "notion"
            | "linear_input"
            | "linear_output"
            | "github"
            | "POSTHOG"
            | "DATADOG"
            | "time_trigger"
            | "launchdarkly"
            | "web"
            | "image_edit"
            | "memory"
            | "workos_input"
            | "workos_output"
            | "attio_input"
            | "attio_output"
            | "snowflake_output"
            | "webhook_input"
            | "webmonitor"
            | "hey_reach_input"
            | "resend_output"
            | "apollo_output"
    }[]
}