// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    GitHubConfig,
    GitHubEventType,
    SDKTrigger,
    TypedTrigger,
} from "terse-sdk"
import { Repos } from "./github.tools.js"

// ── GitHub triggers ───────────────────────────────────────────

export interface GithubPushTriggerPayload {
    integrationType: "github"
    username: string
    installationId: number
    repositoryName: string
    repository: {
        id: number
        name: string
        owner: string
        defaultBranch: string
    }
    sender: {
        login: string
        email?: string
    }
    eventType: "push"
    branch: string
    commits: {
        sha: string
        message?: string
        name: string
        fileDiffs: {
            filename: string
            diff: string
        }[]
    }[]
    pullRequest?: unknown
}

export type GithubPushTrigger = SDKTrigger<GithubPushTriggerPayload>

export interface GithubPROpenedTriggerPayload {
    integrationType: "github"
    username: string
    installationId: number
    repositoryName: string
    repository: {
        id: number
        name: string
        owner: string
        defaultBranch: string
    }
    sender: {
        login: string
        email?: string
    }
    pullRequest: {
        id: string
        number: number
        title: string
        body?: string
        state: "open" | "closed"
        merged: boolean
        head: {
            ref: string
            sha: string
        }
        base: {
            ref: string
            sha: string
        }
        user: {
            login: string
            email?: string
        }
        author?: {
            login: string
            email?: string
        }
        url?: string
    }
    branch?: string
    commits: {
        sha: string
        message?: string
        name: string
        fileDiffs: {
            filename: string
            diff: string
        }[]
    }[]
    eventType: "pull_request.opened"
}

export type GithubPROpenedTrigger = SDKTrigger<GithubPROpenedTriggerPayload>

export interface GithubPRSynchronizedTriggerPayload {
    integrationType: "github"
    username: string
    installationId: number
    repositoryName: string
    repository: {
        id: number
        name: string
        owner: string
        defaultBranch: string
    }
    sender: {
        login: string
        email?: string
    }
    pullRequest: {
        id: string
        number: number
        title: string
        body?: string
        state: "open" | "closed"
        merged: boolean
        head: {
            ref: string
            sha: string
        }
        base: {
            ref: string
            sha: string
        }
        user: {
            login: string
            email?: string
        }
        author?: {
            login: string
            email?: string
        }
        url?: string
    }
    branch?: string
    commits: {
        sha: string
        message?: string
        name: string
        fileDiffs: {
            filename: string
            diff: string
        }[]
    }[]
    eventType: "pull_request.synchronize"
}

export type GithubPRSynchronizedTrigger = SDKTrigger<GithubPRSynchronizedTriggerPayload>

export interface GithubPRClosedTriggerPayload {
    integrationType: "github"
    username: string
    installationId: number
    repositoryName: string
    repository: {
        id: number
        name: string
        owner: string
        defaultBranch: string
    }
    sender: {
        login: string
        email?: string
    }
    pullRequest: {
        id: string
        number: number
        title: string
        body?: string
        state: "open" | "closed"
        merged: boolean
        head: {
            ref: string
            sha: string
        }
        base: {
            ref: string
            sha: string
        }
        user: {
            login: string
            email?: string
        }
        author?: {
            login: string
            email?: string
        }
        url?: string
    }
    branch?: string
    commits: {
        sha: string
        message?: string
        name: string
        fileDiffs: {
            filename: string
            diff: string
        }[]
    }[]
    eventType: "pull_request.closed"
}

export type GithubPRClosedTrigger = SDKTrigger<GithubPRClosedTriggerPayload>

export interface GithubPRMergedTriggerPayload {
    integrationType: "github"
    username: string
    installationId: number
    repositoryName: string
    repository: {
        id: number
        name: string
        owner: string
        defaultBranch: string
    }
    sender: {
        login: string
        email?: string
    }
    pullRequest: {
        id: string
        number: number
        title: string
        body?: string
        state: "open" | "closed"
        merged: boolean
        head: {
            ref: string
            sha: string
        }
        base: {
            ref: string
            sha: string
        }
        user: {
            login: string
            email?: string
        }
        author?: {
            login: string
            email?: string
        }
        url?: string
    }
    branch?: string
    commits: {
        sha: string
        message?: string
        name: string
        fileDiffs: {
            filename: string
            diff: string
        }[]
    }[]
    eventType: "pull_request.merged"
}

export type GithubPRMergedTrigger = SDKTrigger<GithubPRMergedTriggerPayload>

export interface GithubIssueCommentCreatedTriggerPayload {
    integrationType: "github"
    username: string
    installationId: number
    repositoryName: string
    repository: {
        id: number
        name: string
        owner: string
        defaultBranch: string
    }
    sender: {
        login: string
        email?: string
    }
    eventType: "issue_comment.created"
    issue: {
        id: number
        number: number
        title: string
        body?: string
        state: "open" | "closed"
        url: string
        author: {
            login: string
            email?: string
        }
        isPullRequest: boolean
    }
    comment: {
        id: number
        body: string
        author: {
            login: string
            email?: string
        }
        url: string
        createdAt: string
        updatedAt: string
    }
}

export type GithubIssueCommentCreatedTrigger = SDKTrigger<GithubIssueCommentCreatedTriggerPayload>

export type GithubPRTrigger = GithubPROpenedTrigger | GithubPRSynchronizedTrigger | GithubPRClosedTrigger | GithubPRMergedTrigger

export type GithubTrigger = GithubPushTrigger | GithubPRTrigger | GithubIssueCommentCreatedTrigger

export const githubTriggers = {
    /** Trigger on push to a repository */
    onPush(opts: { repo: Repos }): TypedTrigger<GithubPushTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.PUSH])
    },
    /** Trigger when a pull request is opened */
    onPROpened(opts: { repo: Repos }): TypedTrigger<GithubPROpenedTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.PR_OPENED])
    },
    /** Trigger when a pull request is merged */
    onPRMerged(opts: { repo: Repos }): TypedTrigger<GithubPRMergedTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.PR_MERGED])
    },
    /** Trigger when a pull request is closed */
    onPRClosed(opts: { repo: Repos }): TypedTrigger<GithubPRClosedTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.PR_CLOSED])
    },
    /** Trigger when a pull request is synchronized */
    onPRSynchronized(opts: { repo: Repos }): TypedTrigger<GithubPRSynchronizedTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.PR_SYNCHRONIZE])
    },
    /** Trigger on any pull request event */
    onPR(opts: { repo: Repos }): TypedTrigger<GithubPRTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.PR_OPENED, GitHubEventType.PR_MERGED, GitHubEventType.PR_CLOSED, GitHubEventType.PR_SYNCHRONIZE])
    },
    /** Trigger when a comment is created on an issue or pull request */
    onIssueComment(opts: { repo: Repos }): TypedTrigger<GithubIssueCommentCreatedTrigger> {
        return new GitHubConfig("120409451", [opts.repo.repositoryId], [GitHubEventType.ISSUE_COMMENT_CREATED])
    },
    /** Trigger on specific GitHub events for the given repositories */
    trigger(opts: { repos: Repos[]; eventTypes?: GitHubEventType[] }): TypedTrigger<GithubTrigger> {
        return new GitHubConfig("120409451", opts.repos.map(r => r.repositoryId), opts.eventTypes)
    },
}