// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { GitHubConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── GitHub resources ──────────────────────────────────────────

export class GithubOwner {
    constructor(public readonly name: string) {}

    static TerseAI = new GithubOwner("TerseAI")
}

export class Repos {
    constructor(
        public readonly repositoryId: number,
        public readonly name: string,
        public readonly owner: GithubOwner,
        public readonly fullName: string
    ) {}

    static TerseAI = {
        TerseLandingPage: new Repos(1049979398, "Terse-landing-page", GithubOwner.TerseAI, "TerseAI/Terse-landing-page"),
        SorIngestionPoc: new Repos(1065380348, "sor-ingestion-poc", GithubOwner.TerseAI, "TerseAI/sor-ingestion-poc"),
        SorConfluenceIngestion: new Repos(1068097633, "sor-confluence-ingestion", GithubOwner.TerseAI, "TerseAI/sor-confluence-ingestion"),
        Terse: new Repos(1076128380, "Terse", GithubOwner.TerseAI, "TerseAI/Terse"),
        LandingPage: new Repos(1089214477, "Landing-Page", GithubOwner.TerseAI, "TerseAI/Landing-Page"),
        RrwebViewerAgentService: new Repos(1128446417, "rrweb-viewer-agent-service", GithubOwner.TerseAI, "TerseAI/rrweb-viewer-agent-service"),
        VideoAnalyser: new Repos(1135185431, "video-analyser", GithubOwner.TerseAI, "TerseAI/video-analyser"),
        OpenAIAgentsSdkPersistenceBug: new Repos(1163485219, "openAIAgentsSdkPersistenceBug", GithubOwner.TerseAI, "TerseAI/openAIAgentsSdkPersistenceBug"),
        OpenAIAgentsSdkMultiProvider: new Repos(1174739616, "openAIAgentsSdkMultiProvider", GithubOwner.TerseAI, "TerseAI/openAIAgentsSdkMultiProvider"),
        Docs: new Repos(1189882316, "docs", GithubOwner.TerseAI, "TerseAI/docs"),
        TerseJobs: new Repos(1210580853, "Terse-Jobs", GithubOwner.TerseAI, "TerseAI/Terse-Jobs"),
        MultiModelSupport: new Repos(1222576887, "MultiModelSupport", GithubOwner.TerseAI, "TerseAI/MultiModelSupport"),
        OpenAISDKSample: new Repos(1222995744, "OpenAI-SDK-Sample", GithubOwner.TerseAI, "TerseAI/OpenAI-SDK-Sample"),
        TerseSkill: new Repos(1223712746, "terse-skill", GithubOwner.TerseAI, "TerseAI/terse-skill"),
        TerseCommercial: new Repos(1225725324, "terse-commercial", GithubOwner.TerseAI, "TerseAI/terse-commercial"),
        SandboxTracing: new Repos(1245052308, "Sandbox-tracing", GithubOwner.TerseAI, "TerseAI/Sandbox-tracing"),
        SampleProjects: new Repos(1249355222, "SampleProjects", GithubOwner.TerseAI, "TerseAI/SampleProjects"),
        TerseLitellm: new Repos(1272281041, "terse-litellm", GithubOwner.TerseAI, "TerseAI/terse-litellm"),
        RateCardSync: new Repos(1274545227, "rate-card-sync", GithubOwner.TerseAI, "TerseAI/rate-card-sync"),
        ExampleGtmWorkflows: new Repos(1297886629, "example-gtm-workflows", GithubOwner.TerseAI, "TerseAI/example-gtm-workflows"),
        TerseAttioSync: new Repos(1303276714, "Terse-Attio-Sync", GithubOwner.TerseAI, "TerseAI/Terse-Attio-Sync"),
        TerseResend: new Repos(1304023705, "terse-resend", GithubOwner.TerseAI, "TerseAI/terse-resend"),
        AutomationbenchContextAsCode: new Repos(1307039327, "automationbench-context-as-code", GithubOwner.TerseAI, "TerseAI/automationbench-context-as-code"),
        TerseDataPlaneStarter: new Repos(1310376815, "terse-data-plane-starter", GithubOwner.TerseAI, "TerseAI/terse-data-plane-starter"),
    } as const
}

const __githubRepoNameToFullName = new Map<string, string>([
    ["automationbench-context-as-code", "TerseAI/automationbench-context-as-code"],
    ["docs", "TerseAI/docs"],
    ["example-gtm-workflows", "TerseAI/example-gtm-workflows"],
    ["Landing-Page", "TerseAI/Landing-Page"],
    ["MultiModelSupport", "TerseAI/MultiModelSupport"],
    ["OpenAI-SDK-Sample", "TerseAI/OpenAI-SDK-Sample"],
    ["openAIAgentsSdkMultiProvider", "TerseAI/openAIAgentsSdkMultiProvider"],
    ["openAIAgentsSdkPersistenceBug", "TerseAI/openAIAgentsSdkPersistenceBug"],
    ["rate-card-sync", "TerseAI/rate-card-sync"],
    ["rrweb-viewer-agent-service", "TerseAI/rrweb-viewer-agent-service"],
    ["SampleProjects", "TerseAI/SampleProjects"],
    ["Sandbox-tracing", "TerseAI/Sandbox-tracing"],
    ["sor-confluence-ingestion", "TerseAI/sor-confluence-ingestion"],
    ["sor-ingestion-poc", "TerseAI/sor-ingestion-poc"],
    ["Terse", "TerseAI/Terse"],
    ["Terse-Attio-Sync", "TerseAI/Terse-Attio-Sync"],
    ["terse-commercial", "TerseAI/terse-commercial"],
    ["terse-data-plane-starter", "TerseAI/terse-data-plane-starter"],
    ["Terse-Jobs", "TerseAI/Terse-Jobs"],
    ["Terse-landing-page", "TerseAI/Terse-landing-page"],
    ["terse-litellm", "TerseAI/terse-litellm"],
    ["terse-resend", "TerseAI/terse-resend"],
    ["terse-skill", "TerseAI/terse-skill"],
    ["video-analyser", "TerseAI/video-analyser"],
])

function __normalizeGitHubRepos(repo: unknown): string {
    if (repo && typeof repo === "object" && "fullName" in (repo as Record<string, unknown>)) {
        const fullName = (repo as { fullName?: unknown }).fullName
        if (typeof fullName === "string" && fullName.length > 0) return fullName
    }
    if (typeof repo === "string") {
        if (repo.includes("/")) return repo
        return __githubRepoNameToFullName.get(repo) ?? repo
    }
    return String(repo ?? "")
}

function __normalizeGitHubReposNames(repositories: unknown): string[] {
    if (!Array.isArray(repositories)) return []
    return repositories.map(repo => __normalizeGitHubRepos(repo))
}

// ── GitHub tools ──────────────────────────────────────────────

/**
 * Search GitHub repositories for code by SEMANTIC MEANING (conceptual search). Use this when you DON'T know the exact code text.
 *
 * Use searchGitHubCode for:
 * - Concepts and patterns: "authentication", "error handling", "database connections"
 * - Unknown implementations: "how is validation done?", "where are API routes?"
 * - Exploring codebases: "logging implementations", "payment processing"
 * - Finding code by what it DOES, not what it's CALLED
 *
 * Use grepGitHubCode instead when you KNOW the exact text string (function name, import, etc.)
 *
 * Examples:
 * - ✅ "authentication middleware" (finds login, auth, verifyToken, etc.)
 * - ✅ "error handling patterns" (finds try/catch, error handlers, etc.)
 * - ✅ "database queries" (finds prisma, mysql, query builders)
 * - ❌ "getUserById(" → Use grepGitHubCode for exact matches
 *
 * Tips:
 * - Start with broad searches, then narrow down
 * - Use natural language or domain terms
 * - Combine multiple terms for more specific results
 */
export interface SearchGitHubCodeParams {
    /**
     * Array of repository full names (owner/repo format) to search in.
     */
    repositoryNames: string[]
    /**
     * The search query. Use natural language or code-specific terms. Examples: "authentication middleware", "class UserRepository", "handleSubmit form validation"
     */
    query: string
    /**
     * Filter by programming language (e.g., "typescript", "javascript"). Use null to search all languages.
     */
    language?: string | null
    /**
     * Filter by filename pattern (e.g., "*.test.ts" for test files, "*.config.*" for config files). Use null to search all files.
     */
    filename?: string | null
    /**
     * Filter by path (e.g., "src/components" to only search in that directory). Use null to search everywhere.
     */
    path?: string | null
    /**
     * Number of results to return (default: 10, max: 100)
     */
    perPage: number
    /**
     * Page number for pagination (default: 1). Use this to fetch additional results if there are more than perPage results. Use null for page 1. Must be a positive integer >= 1.
     */
    page: number | null
}

export interface SearchGitHubCodeResult {
    success: boolean
    actions?: RunHistoryAction[]
    totalCount: number
    resultsReturned: number
    query: string
    repositories: string[]
    pagination: {
        page: number
        perPage: number
        hasMore: boolean
    }
    results: {
        index: number
        repository: string
        path: string
        url: string
        snippets: string
    }[]
    message: string
    tip: string
}

/**
 * Search GitHub repositories for EXACT TEXT MATCHES (like grep). Use this when you KNOW the exact string you're looking for.
 *
 * Use grepGitHubCode for:
 * - Exact function calls: "getUserById(", "processPayment()"
 * - Exact imports: "from '@prisma/client'", "import React from"
 * - Exact strings: "API_KEY", "TODO:", "FIXME:"
 * - Known identifiers: class names, constants, variable names you know exist
 *
 * Use searchGitHubCode instead when you DON'T know the exact text (looking for concepts/patterns).
 *
 * Examples:
 * - ✅ "getUserById(" (exact function call)
 * - ✅ "from '@prisma/client'" (exact import statement)
 * - ✅ "TODO: refactor" (exact comment)
 * - ✅ "useState" (exact React hook name)
 * - ❌ "state management" → Use searchGitHubCode for concepts
 *
 * This is more precise than semantic search - use it when you know exactly what text to find.
 */
export interface GrepGitHubCodeParams {
    /**
     * Array of repository full names (owner/repo format) to search in.
     */
    repositoryNames: string[]
    /**
     * The exact text pattern to search for. For function calls, include the opening parenthesis (e.g., "fetchUser("). For strings, include quotes if needed.
     */
    pattern: string
    /**
     * Filter by file extension (e.g., "ts", "js", "py"). Do not include the dot. Use null to search all file types.
     */
    fileExtension?: string | null
    /**
     * Filter by directory path (e.g., "src/services" to only search in that directory). Use null to search everywhere.
     */
    path?: string | null
    /**
     * Number of results to return (default: 20, max: 100)
     */
    perPage: number
    /**
     * Page number for pagination (default: 1). Use this to fetch additional results if there are more than perPage results. Use null for page 1. Must be a positive integer >= 1.
     */
    page: number | null
}

export interface GrepGitHubCodeResult {
    success: boolean
    actions?: RunHistoryAction[]
    totalCount: number
    resultsReturned: number
    pattern: string
    query: string
    repositories: string[]
    pagination: {
        page: number
        perPage: number
        hasMore: boolean
    }
    results: {
        index: number
        repository: string
        file: string
        url: string
        matches: string
    }[]
    message: string
    tip: string
}

/**
 * Read the full contents of a file from a GitHub repository. Use this after finding relevant files via search to:
 * - Understand the complete implementation of a function or class
 * - See imports and dependencies
 * - Review the full context around a code snippet
 * - Understand file structure and organization
 *
 * Note: This reads from the default branch (main/master). Large files may be truncated.
 */
export interface ReadGitHubFileParams {
    /**
     * The repository in "owner/repo" format (e.g., "facebook/react"). Must be one of the configured repositories.
     */
    repository: string
    /**
     * The file path within the repository (e.g., "src/components/Button.tsx" or "README.md")
     */
    path: string
    /**
     * Start reading from this line number (1-indexed). Use with endLine for partial file reads. Use null to start from beginning.
     */
    startLine?: number | null
    /**
     * Stop reading at this line number (1-indexed, inclusive). Use with startLine for partial file reads. Use null to read to end.
     */
    endLine?: number | null
}

export interface ReadGitHubFileResult {
    success: boolean
    actions?: RunHistoryAction[]
    repository: string
    path: string
    url: string
    totalLines: number
    displayedLines: string
    size: number
    content: string
    warning?: string
}

/**
 * List files and directories in a GitHub repository. Use this to:
 * - Explore the repository structure
 * - Find where specific types of files are located
 * - Understand the project organization
 * - Navigate to specific directories before reading files
 *
 * Start with the root directory (empty path) to see the top-level structure, then drill down into interesting directories.
 */
export interface ListGitHubDirectoryParams {
    /**
     * The repository in "owner/repo" format (e.g., "facebook/react"). Must be one of the configured repositories.
     */
    repository: string
    /**
     * The directory path to list (e.g., "src/components"). Use empty string "" for root directory.
     */
    path: string
    /**
     * If true, list all files recursively (can be large for big repos). Use false for single-level listing.
     */
    recursive: boolean
}

export interface ListGitHubDirectoryResult {
    success: boolean
    actions?: RunHistoryAction[]
    repository: string
    path: string
    recursive: boolean
    totalItems: number
    directories: (
        | {
              name?: string
              path?: string
              type?: "directory"
          }
        | string
    )[]
    files: {
        name?: string
        path: string
        type?: "file"
        size?: number
    }[]
    warning?: string
    tip?: string
    truncated?: boolean
    other?: {
        name: string
        type: string
    }[]
}

/**
 * List pull requests in GitHub repositories within a time window. Use this to:
 * - Find recently merged PRs to understand recent changes
 * - Review what work has been completed in a given period
 * - Track PR activity for specific repositories
 * - Understand the development history and velocity
 *
 * The tool returns PR details including title, description, author, merge status, and dates.
 * Dates are specified in YYYY-MM-DD format (e.g., "2024-01-15"). The since date is interpreted as the start of that day (00:00:00), and the until date is interpreted as the end of that day (23:59:59).
 */
export interface ListGitHubPullRequestsParams {
    /**
     * Repository in "owner/repo" format (e.g., "facebook/react"). Must be one of the configured repositories.
     */
    repository: string
    /**
     * Filter by PR state. Use "closed" to see merged PRs, "open" for in-progress, or "all" for both.
     */
    state: "open" | "closed" | "all"
    /**
     * Start date in YYYY-MM-DD format (e.g., "2024-01-15"). Only PRs updated on or after this date (starting at 00:00:00) are included. Use null for no start filter.
     */
    since: string | null
    /**
     * End date in YYYY-MM-DD format (e.g., "2024-01-15"). Only PRs updated on or before this date (ending at 23:59:59) are included. Use null for no end filter.
     */
    until: string | null
    /**
     * Number of results to return (default: 20, max: 100)
     */
    perPage: number
    /**
     * Page number for pagination (default: 1). Use this to fetch additional PRs if there are more than perPage results. Use null for page 1. Must be a positive integer >= 1.
     */
    page: number | null
}

export interface ListGitHubPullRequestsResult {
    success: boolean
    actions?: RunHistoryAction[]
    repository: string
    timeWindow: string
    summary: {
        total: number
        merged: number
        open: number
        closed: number
    }
    pagination: {
        page: number
        perPage: number
        hasMore: boolean
    }
    pullRequests: {
        number: number
        title: string
        description: string
        author: string
        state: string
        merged: boolean
        mergedAt?: string
        createdAt: string
        closedAt?: string
        labels: string[]
        baseBranch: string
        headBranch: string
        url: string
    }[]
    message: string
}

/**
 * List commits in GitHub repositories within a time window. Use this to:
 * - Review recent changes and development activity
 * - Track what code was modified in a specific period
 * - Find commits by a specific author
 * - See commit history for a specific file or directory
 * - Understand the pace and nature of development
 *
 * The tool returns commit details including message, author, date, and SHA.
 */
export interface ListGitHubCommitsParams {
    /**
     * Repository in "owner/repo" format (e.g., "facebook/react"). Must be one of the configured repositories.
     */
    repository: string
    /**
     * Start of time window (ISO date string, e.g., "2024-01-01" or "2024-01-15T00:00:00Z"). Only commits after this date are included. Use null for no start filter.
     */
    since: string | null
    /**
     * End of time window (ISO date string). Only commits before this date are included. Use null for no end filter.
     */
    until?: string | null
    /**
     * Branch name to list commits from (e.g., "main", "develop"). Use null for the repository's default branch.
     */
    branch?: string | null
    /**
     * Only include commits that affect this file or directory path (e.g., "src/components" or "package.json"). Use null for all paths.
     */
    path?: string | null
    /**
     * Filter commits by author (GitHub username or email). Use null for all authors.
     */
    author?: string | null
    /**
     * Number of results to return (default: 30, max: 100)
     */
    perPage: number
}

export interface ListGitHubCommitsResult {
    success: boolean
    actions?: RunHistoryAction[]
    repository: string
    timeWindow: string
    filters: string
    summary: {
        total: number
        byAuthor: {
            [k: string]: number
        }
    }
    commits: {
        sha: string
        fullSha: string
        message: string
        fullMessage: string
        author: string
        date: string
        url: string
    }[]
    message: string
    tip: string
}

/**
 * Summarize the diff of a pull request from a GitHub repository using an intelligent sub-agent. Use this to:
 * - Understand what changes were made in a specific PR without loading the full diff into context
 * - Get a concise summary of code changes before merging
 * - Analyze the impact of a PR on the codebase efficiently
 * - See file-by-file changes with key insights
 *
 * The tool launches a sub-agent that:
 * - Reads the full PR diff from GitHub
 * - Analyzes the changes using a compact model
 * - Provides a structured summary including:
 *   - Overview of changes
 *   - Key files modified
 *   - Notable additions/removals
 *   - Impact assessment
 *
 * You can optionally provide high-level context about what you're looking for in the PR, which will help the sub-agent focus its analysis.
 */
export interface SummarizeGitHubPullRequestDiffParams {
    /**
     * The repository in "owner/repo" format (e.g., "facebook/react"). Must be one of the configured repositories.
     */
    repository: string
    /**
     * The pull request number (e.g., 123 for PR #123)
     */
    pullNumber: number
    /**
     * Page number for pagination (default: 1). Use this to fetch additional files if a PR has more than 100 files. Use null for page 1. Must be a positive integer >= 1.
     */
    page: number | null
    /**
     * Optional high-level context about what you're looking for in this PR. This helps the sub-agent focus its analysis. For example: "I need to understand the authentication changes" or "Focus on database migration changes". Use null if no specific context.
     */
    context: string | null
}

export interface SummarizeGitHubPullRequestDiffResult {
    success: boolean
    actions?: RunHistoryAction[]
    repository: string
    pullRequest: {
        number: number
        title: string
        state: string
        merged: boolean
        baseBranch: string
        headBranch: string
        url: string
    }
    summary: {
        [k: string]: unknown
    }
    pagination: {
        page: number
        perPage: number
        hasMore: boolean
    }
    analysis: string
    message: string
}

export type GithubGeneratedTools = {
    /** Search GitHub repositories for code by SEMANTIC MEANING (conceptual search). Use this when you DON'T know the exact code text.

Use searchGitHubCode for:
- Concepts and patterns: "authentication", "error handling", "database connections"
- Unknown implementations: "how is validation done?", "where are API routes?"
- Exploring codebases: "logging implementations", "payment processing"
- Finding code by what it DOES, not what it's CALLED

Use grepGitHubCode instead when you KNOW the exact text string (function name, import, etc.)

Examples:
- ✅ "authentication middleware" (finds login, auth, verifyToken, etc.)
- ✅ "error handling patterns" (finds try/catch, error handlers, etc.)
- ✅ "database queries" (finds prisma, mysql, query builders)
- ❌ "getUserById(" → Use grepGitHubCode for exact matches

Tips:
- Start with broad searches, then narrow down
- Use natural language or domain terms
- Combine multiple terms for more specific results */
    searchCode(params: SearchGitHubCodeParams): Promise<SearchGitHubCodeResult>
    /** Search GitHub repositories for EXACT TEXT MATCHES (like grep). Use this when you KNOW the exact string you're looking for.

Use grepGitHubCode for:
- Exact function calls: "getUserById(", "processPayment()"
- Exact imports: "from '@prisma/client'", "import React from"
- Exact strings: "API_KEY", "TODO:", "FIXME:"
- Known identifiers: class names, constants, variable names you know exist

Use searchGitHubCode instead when you DON'T know the exact text (looking for concepts/patterns).

Examples:
- ✅ "getUserById(" (exact function call)
- ✅ "from '@prisma/client'" (exact import statement)
- ✅ "TODO: refactor" (exact comment)
- ✅ "useState" (exact React hook name)
- ❌ "state management" → Use searchGitHubCode for concepts

This is more precise than semantic search - use it when you know exactly what text to find. */
    grepCode(params: GrepGitHubCodeParams): Promise<GrepGitHubCodeResult>
    /** Read the full contents of a file from a GitHub repository. Use this after finding relevant files via search to:
- Understand the complete implementation of a function or class
- See imports and dependencies
- Review the full context around a code snippet
- Understand file structure and organization

Note: This reads from the default branch (main/master). Large files may be truncated. */
    readFile(params: ReadGitHubFileParams): Promise<ReadGitHubFileResult>
    /** List files and directories in a GitHub repository. Use this to:
- Explore the repository structure
- Find where specific types of files are located
- Understand the project organization
- Navigate to specific directories before reading files

Start with the root directory (empty path) to see the top-level structure, then drill down into interesting directories. */
    listDirectory(params: ListGitHubDirectoryParams): Promise<ListGitHubDirectoryResult>
    /** List pull requests in GitHub repositories within a time window. Use this to:
- Find recently merged PRs to understand recent changes
- Review what work has been completed in a given period
- Track PR activity for specific repositories
- Understand the development history and velocity

The tool returns PR details including title, description, author, merge status, and dates.
Dates are specified in YYYY-MM-DD format (e.g., "2024-01-15"). The since date is interpreted as the start of that day (00:00:00), and the until date is interpreted as the end of that day (23:59:59). */
    listPullRequests(params: ListGitHubPullRequestsParams): Promise<ListGitHubPullRequestsResult>
    /** List commits in GitHub repositories within a time window. Use this to:
- Review recent changes and development activity
- Track what code was modified in a specific period
- Find commits by a specific author
- See commit history for a specific file or directory
- Understand the pace and nature of development

The tool returns commit details including message, author, date, and SHA. */
    listCommits(params: ListGitHubCommitsParams): Promise<ListGitHubCommitsResult>
    /** Summarize the diff of a pull request from a GitHub repository using an intelligent sub-agent. Use this to:
- Understand what changes were made in a specific PR without loading the full diff into context
- Get a concise summary of code changes before merging
- Analyze the impact of a PR on the codebase efficiently
- See file-by-file changes with key insights

The tool launches a sub-agent that:
- Reads the full PR diff from GitHub
- Analyzes the changes using a compact model
- Provides a structured summary including:
  - Overview of changes
  - Key files modified
  - Notable additions/removals
  - Impact assessment

You can optionally provide high-level context about what you're looking for in the PR, which will help the sub-agent focus its analysis. */
    summarizePRDiff(params: SummarizeGitHubPullRequestDiffParams): Promise<SummarizeGitHubPullRequestDiffResult>
}

export const githubTools: GithubGeneratedTools = {
    searchCode: (params: SearchGitHubCodeParams) =>
        TerseAgent.executeTool<SearchGitHubCodeResult>("searchGitHubCode", { ...({ ...params, repositoryNames: __normalizeGitHubReposNames((params).repositoryNames) }) }),
    grepCode: (params: GrepGitHubCodeParams) =>
        TerseAgent.executeTool<GrepGitHubCodeResult>("grepGitHubCode", { ...({ ...params, repositoryNames: __normalizeGitHubReposNames((params).repositoryNames) }) }),
    readFile: (params: ReadGitHubFileParams) =>
        TerseAgent.executeTool<ReadGitHubFileResult>("readGitHubFile", { ...({ ...params, repository: __normalizeGitHubRepos((params).repository) }) }),
    listDirectory: (params: ListGitHubDirectoryParams) =>
        TerseAgent.executeTool<ListGitHubDirectoryResult>("listGitHubDirectory", { ...({ ...params, repository: __normalizeGitHubRepos((params).repository) }) }),
    listPullRequests: (params: ListGitHubPullRequestsParams) =>
        TerseAgent.executeTool<ListGitHubPullRequestsResult>("listGitHubPullRequests", { ...({ ...params, repository: __normalizeGitHubRepos((params).repository) }) }),
    listCommits: (params: ListGitHubCommitsParams) =>
        TerseAgent.executeTool<ListGitHubCommitsResult>("listGitHubCommits", { ...({ ...params, repository: __normalizeGitHubRepos((params).repository) }) }),
    summarizePRDiff: (params: SummarizeGitHubPullRequestDiffParams) =>
        TerseAgent.executeTool<SummarizeGitHubPullRequestDiffResult>("summarizeGitHubPullRequestDiff", { ...({ ...params, repository: __normalizeGitHubRepos((params).repository) }) }),
}

// ── GitHub skill ──────────────────────────────────────────────

/** GitHub — read code and pull requests from the given repositories */
export function githubSkill(opts: { repos: Repos[] }): TypedSkill<never> {
    return new GitHubConfig("120409451", opts.repos.map(r => r.repositoryId))
}