// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    GmailConfig,
    GmailEventType,
    SDKTrigger,
    TypedTrigger,
} from "terse-sdk"

// ── Gmail triggers ────────────────────────────────────────────

export interface GmailTriggerPayload {
    integrationType: "gmail"
    eventType: "email.received"
    id: string
    threadId: string
    subject: string
    from: string
    to: string
    date: string
    internalDate: string
    messageId: string
    body: string
    snippet: string
    labelIds: string[]
    attachments?: {
        attachmentId: string
        filename: string
        mimeType: string
        contentId?: string
        isInline: boolean
    }[]
}

export type GmailTrigger = SDKTrigger<GmailTriggerPayload>

export const gmailTriggers = {
    /** Trigger when a new email is received */
    onEmail(): TypedTrigger<GmailTrigger> {
        return new GmailConfig("cmgwveigf0001oh21cvroq9xu", [GmailEventType.EMAIL_RECEIVED])
    },
    /** Trigger on all Gmail events */
    trigger(opts?: { eventTypes?: GmailEventType[] }): TypedTrigger<GmailTrigger> {
        return new GmailConfig("cmgwveigf0001oh21cvroq9xu", opts?.eventTypes)
    },
}