// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    GmailDraftOutputConfig,
    GmailOutputConfig,
    TerseAgent,
    TypedSkill,
} from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Gmail tools ───────────────────────────────────────────────

/**
 * Send email or reply to an existing email thread via Gmail. Use thread_id (the Gmail Thread ID, not the Message-ID) to reply to an existing thread, or omit it to send a new email. IMPORTANT: Never put image URLs directly in html_body — remote URLs expire and will result in broken images. Always use image_urls to embed images as base64-encoded inline MIME parts (CID attachments), then reference them in html_body with <img src="cid:image-1.png">. image_urls must be signed URLs from our internal GCS image bucket.
 */
export interface GmailSendEmailParams {
    /**
     * Recipient email address(es). Multiple addresses can be comma-separated.
     */
    to: string
    /**
     * Email subject line
     */
    subject: string
    /**
     * Plain text email body content. Do not include image URLs here — images cannot be embedded in plain text.
     */
    body?: string | null
    /**
     * HTML email body content. If provided with body, sends multipart/alternative. NEVER use <img src="https://..."> with remote URLs — they will expire. Images must be passed via image_urls and referenced as <img src="cid:image-1.png">.
     */
    html_body?: string | null
    /**
     * Gmail Thread ID (numeric string from the email event, NOT the Message-ID header). Omit for new emails.
     */
    thread_id?: string | null
    /**
     * CC recipient email address(es). Multiple addresses can be comma-separated.
     */
    cc?: string | null
    /**
     * BCC recipient email address(es). Multiple addresses can be comma-separated.
     */
    bcc?: string | null
    /**
     * URLs of images to embed in the email. Must be signed URLs from our internal GCS image bucket. Each image is downloaded and base64-encoded as an inline MIME attachment with a Content-ID. Images are assigned sequential filenames: image-1.png, image-2.png, etc. (extension reflects actual MIME type). You MUST reference each one in html_body as <img src="cid:image-1.png">, <img src="cid:image-2.png">, etc. Do NOT put the raw URLs in html_body.
     */
    image_urls?: string[] | null
    /**
     * Custom email headers as key-value pairs. Useful for adding headers like List-Unsubscribe, List-Unsubscribe-Post, X-Priority, etc. Example: {"List-Unsubscribe": "<mailto:unsubscribe@example.com>", "List-Unsubscribe-Post": "List-Unsubscribe=One-Click"}
     */
    custom_headers?:
        | {
              key: string
              value: string
          }[]
        | null
}

export interface GmailSendEmailResult {
    success: true
    actions?: RunHistoryAction[]
    message_id: string
    thread_id: string
    to: string
    subject: string
    summary: string
    is_reply: boolean
}

/**
 * Create a draft email in Gmail. Use thread_id (the Gmail Thread ID, not the Message-ID) to create a draft reply to an existing thread, or omit it to create a new draft email. The draft will appear in the user's Gmail Drafts folder for review before sending. IMPORTANT: Never put image URLs directly in html_body — remote URLs expire and will result in broken images. Always use image_urls to embed images as base64-encoded inline MIME parts (CID attachments), then reference them in html_body with <img src="cid:image-1.png">. image_urls must be signed URLs from our internal GCS image bucket.
 */
export interface GmailCreateDraftParams {
    /**
     * Recipient email address(es). Multiple addresses can be comma-separated.
     */
    to: string
    /**
     * Email subject line
     */
    subject: string
    /**
     * Plain text email body content. Do not include image URLs here — images cannot be embedded in plain text.
     */
    body?: string | null
    /**
     * HTML email body content. If provided with body, sends multipart/alternative. NEVER use <img src="https://..."> with remote URLs — they will expire. Images must be passed via image_urls and referenced as <img src="cid:image-1.png">.
     */
    html_body?: string | null
    /**
     * Gmail Thread ID (numeric string from the email event, NOT the Message-ID header). Omit for new drafts.
     */
    thread_id?: string | null
    /**
     * CC recipient email address(es). Multiple addresses can be comma-separated.
     */
    cc?: string | null
    /**
     * BCC recipient email address(es). Multiple addresses can be comma-separated.
     */
    bcc?: string | null
    /**
     * URLs of images to embed in the email. Must be signed URLs from our internal GCS image bucket. Each image is downloaded and base64-encoded as an inline MIME attachment with a Content-ID. Images are assigned sequential filenames: image-1.png, image-2.png, etc. (extension reflects actual MIME type). You MUST reference each one in html_body as <img src="cid:image-1.png">, <img src="cid:image-2.png">, etc. Do NOT put the raw URLs in html_body.
     */
    image_urls?: string[] | null
    /**
     * Custom email headers as key-value pairs. Useful for adding headers like List-Unsubscribe, List-Unsubscribe-Post, X-Priority, etc. Example: {"List-Unsubscribe": "<mailto:unsubscribe@example.com>", "List-Unsubscribe-Post": "List-Unsubscribe=One-Click"}
     */
    custom_headers?:
        | {
              key: string
              value: string
          }[]
        | null
}

export interface GmailCreateDraftResult {
    success: true
    actions?: RunHistoryAction[]
    draft_id: string
    message_id: string
    thread_id: string
    draft_url: string
    to: string
    subject: string
    summary: string
    is_reply: boolean
}

export type GmailGeneratedTools = {
    /** Send email or reply to an existing email thread via Gmail. Use thread_id (the Gmail Thread ID, not the Message-ID) to reply to an existing thread, or omit it to send a new email. IMPORTANT: Never put image URLs directly in html_body — remote URLs expire and will result in broken images. Always use image_urls to embed images as base64-encoded inline MIME parts (CID attachments), then reference them in html_body with <img src="cid:image-1.png">. image_urls must be signed URLs from our internal GCS image bucket. */
    sendEmail(params: GmailSendEmailParams): Promise<GmailSendEmailResult>
    /** Create a draft email in Gmail. Use thread_id (the Gmail Thread ID, not the Message-ID) to create a draft reply to an existing thread, or omit it to create a new draft email. The draft will appear in the user's Gmail Drafts folder for review before sending. IMPORTANT: Never put image URLs directly in html_body — remote URLs expire and will result in broken images. Always use image_urls to embed images as base64-encoded inline MIME parts (CID attachments), then reference them in html_body with <img src="cid:image-1.png">. image_urls must be signed URLs from our internal GCS image bucket. */
    createDraft(params: GmailCreateDraftParams): Promise<GmailCreateDraftResult>
}

export const gmailTools: GmailGeneratedTools = {
    sendEmail: (params: GmailSendEmailParams) =>
        TerseAgent.executeTool<GmailSendEmailResult>("gmail_send_email", { ...(params), integrationId: "cmgwveigf0001oh21cvroq9xu" }),
    createDraft: (params: GmailCreateDraftParams) =>
        TerseAgent.executeTool<GmailCreateDraftResult>("gmail_create_draft", { ...(params), integrationId: "cmgwveigf0001oh21cvroq9xu" }),
}

// ── Gmail skills ──────────────────────────────────────────────

/** Gmail — send emails */
export function gmailSkill(): TypedSkill<"gmail_create_draft" | "gmail_send_email"> {
    return new GmailOutputConfig("cmgwveigf0001oh21cvroq9xu")
}

/** Gmail — create draft emails (no auto-send) */
export function gmailDraftSkill(): TypedSkill<"gmail_create_draft" | "gmail_send_email"> {
    return new GmailDraftOutputConfig("cmgwveigf0001oh21cvroq9xu")
}