// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    HeyReachEventType,
    HeyReachInputConfig,
    SDKTrigger,
    TypedTrigger,
} from "terse-sdk"
import { HeyReachCampaign } from "./hey_reach.tools.js"

// ── HeyReach triggers ─────────────────────────────────────────

export interface HeyReachConnectionRequestSentTriggerPayload {
    integrationType: "hey_reach"
    eventType: "CONNECTION_REQUEST_SENT"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
}

export type HeyReachConnectionRequestSentTrigger = SDKTrigger<HeyReachConnectionRequestSentTriggerPayload>

export interface HeyReachConnectionRequestAcceptedTriggerPayload {
    integrationType: "hey_reach"
    eventType: "CONNECTION_REQUEST_ACCEPTED"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
}

export type HeyReachConnectionRequestAcceptedTrigger = SDKTrigger<HeyReachConnectionRequestAcceptedTriggerPayload>

export interface HeyReachMessageSentTriggerPayload {
    integrationType: "hey_reach"
    eventType: "MESSAGE_SENT"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
    messageBody?: string
}

export type HeyReachMessageSentTrigger = SDKTrigger<HeyReachMessageSentTriggerPayload>

export interface HeyReachMessageReplyReceivedTriggerPayload {
    integrationType: "hey_reach"
    eventType: "MESSAGE_REPLY_RECEIVED"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
    messageBody?: string
}

export type HeyReachMessageReplyReceivedTrigger = SDKTrigger<HeyReachMessageReplyReceivedTriggerPayload>

export interface HeyReachInmailSentTriggerPayload {
    integrationType: "hey_reach"
    eventType: "INMAIL_SENT"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
    messageBody?: string
}

export type HeyReachInmailSentTrigger = SDKTrigger<HeyReachInmailSentTriggerPayload>

export interface HeyReachInmailReplyReceivedTriggerPayload {
    integrationType: "hey_reach"
    eventType: "INMAIL_REPLY_RECEIVED"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
    messageBody?: string
}

export type HeyReachInmailReplyReceivedTrigger = SDKTrigger<HeyReachInmailReplyReceivedTriggerPayload>

export interface HeyReachFollowSentTriggerPayload {
    integrationType: "hey_reach"
    eventType: "FOLLOW_SENT"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
}

export type HeyReachFollowSentTrigger = SDKTrigger<HeyReachFollowSentTriggerPayload>

export interface HeyReachLikedPostTriggerPayload {
    integrationType: "hey_reach"
    eventType: "LIKED_POST"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
    postUrl?: string
}

export type HeyReachLikedPostTrigger = SDKTrigger<HeyReachLikedPostTriggerPayload>

export interface HeyReachViewedProfileTriggerPayload {
    integrationType: "hey_reach"
    eventType: "VIEWED_PROFILE"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
}

export type HeyReachViewedProfileTrigger = SDKTrigger<HeyReachViewedProfileTriggerPayload>

export interface HeyReachCampaignCompletedTriggerPayload {
    integrationType: "hey_reach"
    eventType: "CAMPAIGN_COMPLETED"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
}

export type HeyReachCampaignCompletedTrigger = SDKTrigger<HeyReachCampaignCompletedTriggerPayload>

export interface HeyReachLeadTagUpdatedTriggerPayload {
    integrationType: "hey_reach"
    eventType: "LEAD_TAG_UPDATED"
    eventId: string
    createdAt: string
    lead?: {
        id?: string | number
        profile_url?: string
        first_name?: string
        last_name?: string
        full_name?: string
        location?: string
        summary?: string
        company_url?: string
        company_name?: string
        position?: string
        about?: string
        email_address?: string
        enriched_email?: string | null
        custom_email?: string | null
        tags?: unknown[]
        lists?: unknown[]
    }
    campaign?: {
        id?: string | number
        name?: string
        status?: string | null
    }
    linkedInAccount?: {
        id?: string | number
        first_name?: string
        last_name?: string
        full_name?: string
        email_address?: string
        profile_url?: string
    }
    rawPayload: {
        [k: string]: unknown
    }
    tags?: string[]
}

export type HeyReachLeadTagUpdatedTrigger = SDKTrigger<HeyReachLeadTagUpdatedTriggerPayload>

export type HeyReachTrigger = HeyReachConnectionRequestSentTrigger | HeyReachConnectionRequestAcceptedTrigger | HeyReachMessageSentTrigger | HeyReachMessageReplyReceivedTrigger | HeyReachInmailSentTrigger | HeyReachInmailReplyReceivedTrigger | HeyReachFollowSentTrigger | HeyReachLikedPostTrigger | HeyReachViewedProfileTrigger | HeyReachCampaignCompletedTrigger | HeyReachLeadTagUpdatedTrigger

export const heyReachTriggers = {
    /** Trigger when a connection request is sent */
    onConnectionRequestSent(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachConnectionRequestSentTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.CONNECTION_REQUEST_SENT, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when a connection request is accepted */
    onConnectionRequestAccepted(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachConnectionRequestAcceptedTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.CONNECTION_REQUEST_ACCEPTED, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when a LinkedIn message is sent */
    onMessageSent(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachMessageSentTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.MESSAGE_SENT, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger on the first reply to a LinkedIn message */
    onMessageReplyReceived(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachMessageReplyReceivedTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.MESSAGE_REPLY_RECEIVED, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when an InMail is sent */
    onInmailSent(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachInmailSentTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.INMAIL_SENT, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger on the first reply to an InMail */
    onInmailReplyReceived(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachInmailReplyReceivedTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.INMAIL_REPLY_RECEIVED, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when a follow is sent */
    onFollowSent(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachFollowSentTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.FOLLOW_SENT, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when a post is liked */
    onLikedPost(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachLikedPostTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.LIKED_POST, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when a profile is viewed */
    onViewedProfile(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachViewedProfileTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.VIEWED_PROFILE, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when a campaign completes */
    onCampaignCompleted(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachCampaignCompletedTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.CAMPAIGN_COMPLETED, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger when lead tags are updated */
    onLeadTagUpdated(opts?: { campaigns?: HeyReachCampaign[] }): TypedTrigger<HeyReachLeadTagUpdatedTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", HeyReachEventType.LEAD_TAG_UPDATED, (opts?.campaigns ?? []).map(c => c.campaignId))
    },
    /** Trigger on specific HeyReach event types */
    trigger(opts: { campaigns?: HeyReachCampaign[]; eventType: HeyReachEventType }): TypedTrigger<HeyReachTrigger> {
        return new HeyReachInputConfig("cmplfqh69000jo92gxwa6p4d2", opts.eventType, (opts.campaigns ?? []).map(c => c.campaignId))
    },
}