// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

// ── HeyReach resources ────────────────────────────────────────

export class HeyReachCampaign {
    constructor(public readonly campaignId: string, public readonly name: string) {}
}