// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { LaunchDarklyConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── LaunchDarkly resources ────────────────────────────────────

export class LaunchDarklyProject {
    constructor(public readonly projectKey: string, public readonly name: string) {}

    static Terse = new LaunchDarklyProject("default", "Terse")
}

// ── LaunchDarkly tools ────────────────────────────────────────

/**
 * List all feature flags with enabled/disabled states per environment. Use summary=true for quick overview, summary=false for full details.
 */
export interface ListLaunchDarklyFlagsParams {
    /**
     * The LaunchDarkly project key.
     */
    projectKey: string
    /**
     * Array of environment keys to query.
     */
    environmentKeys: string[]
    /**
     * If true, return only flag key, name, and on/off state per environment. If false, return full flag details.
     */
    summary?: boolean
    /**
     * Optional: Filter flags by name/key containing this text.
     */
    filter?: string | null
    /**
     * Optional: Filter flags by tags.
     */
    tags?: string[] | null
}

export interface ListLaunchDarklyFlagsResult {
    success: boolean
    actions?: RunHistoryAction[]
    projectKey: string
    totalFlags: number
    flags: {
        key: string
        name: string
        description: string
        environments: {
            [k: string]: boolean
        }
        url: string
        environmentUrls: {
            [k: string]: string
        }
    }[]
    flagsLink: string
    message: string
}

/**
 * Get detailed information about a specific feature flag including targeting rules, rollout strategies, variations, and per-environment configuration. Optionally includes change history when includeHistory=true.
 */
export interface GetLaunchDarklyFlagDetailsParams {
    /**
     * The LaunchDarkly project key.
     */
    projectKey: string
    /**
     * Array of environment keys to query.
     */
    environmentKeys: string[]
    /**
     * The flag key to retrieve.
     */
    flagKey: string
    /**
     * Optional: Specific environment to get details for (if not provided, returns all configured environments).
     */
    environmentKey?: string | null
    /**
     * If true, includes change history for the flag over the specified time window.
     */
    includeHistory?: boolean
    /**
     * Optional: ISO date - only return history entries before this date (only used if includeHistory is true).
     */
    before?: string | null
    /**
     * Optional: ISO date - only return history entries after this date (only used if includeHistory is true).
     */
    after?: string | null
    /**
     * Number of history entries to return if includeHistory is true (default: 20, max: 20).
     */
    historyLimit?: number
}

export interface GetLaunchDarklyFlagDetailsResult {
    success: boolean
    actions?: RunHistoryAction[]
    projectKey: string
    flag: {
        key: string
        name: string
        description: string
        kind: string
        variations: {
            [k: string]: unknown
        }[]
        tags: string[]
        maintainerId: string | null
    }
    environments: {
        [k: string]: {
            on: boolean
            targets: {
                [k: string]: unknown
            }[]
            contextTargets: {
                [k: string]: unknown
            }[]
            rules: {
                [k: string]: unknown
            }[]
            fallthrough: {
                [k: string]: unknown
            } | null
            offVariation: number | null
            prerequisites: {
                [k: string]: unknown
            }[]
        }
    }
    url: string
    history?: {
        entries: {
            id: string
            timestamp: string
            kind: string
            key: string
            name: string
            description: string
            member: {
                [k: string]: unknown
            } | null
            changes: {
                [k: string]: unknown
            }[]
        }[]
        totalEntries: number
        url: string
    }
    message: string
}

export type LaunchdarklyGeneratedTools = {
    /** List all feature flags with enabled/disabled states per environment. Use summary=true for quick overview, summary=false for full details. */
    listFeatureFlags(params: ListLaunchDarklyFlagsParams): Promise<ListLaunchDarklyFlagsResult>
    /** Get detailed information about a specific feature flag including targeting rules, rollout strategies, variations, and per-environment configuration. Optionally includes change history when includeHistory=true. */
    getFlagDetails(params: GetLaunchDarklyFlagDetailsParams): Promise<GetLaunchDarklyFlagDetailsResult>
}

export const launchdarklyTools: LaunchdarklyGeneratedTools = {
    listFeatureFlags: (params: ListLaunchDarklyFlagsParams) =>
        TerseAgent.executeTool<ListLaunchDarklyFlagsResult>("listLaunchDarklyFlags", { ...(params), integrationId: "cmkq0rm5l00nphz2il6w0xjnd" }),
    getFlagDetails: (params: GetLaunchDarklyFlagDetailsParams) =>
        TerseAgent.executeTool<GetLaunchDarklyFlagDetailsResult>("getLaunchDarklyFlagDetails", { ...(params), integrationId: "cmkq0rm5l00nphz2il6w0xjnd" }),
}

// ── LaunchDarkly skill ────────────────────────────────────────

/** LaunchDarkly — read and toggle feature flags in a project + environments */
export function launchDarklySkill(opts: { project: LaunchDarklyProject; environmentKeys: string[] }): TypedSkill<never> {
    return new LaunchDarklyConfig("cmkq0rm5l00nphz2il6w0xjnd", opts.project.projectKey, opts.environmentKeys)
}