// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    LinearEventType,
    LinearInputConfig,
    SDKTrigger,
    TypedTrigger,
} from "terse-sdk"
import { LinearTeam, LinearProject } from "./linear.tools.js"

// ── Linear triggers ───────────────────────────────────────────

export interface LinearIssueCreatedTriggerPayload {
    integrationType: "linear"
    action: "create"
    actor: {
        id: string
        name: string
        email: string
        url: string
        type: string
    }
    createdAt: string
    url?: string
    organizationId: string
    webhookTimestamp: number
    webhookId: string
    eventType: "issue.created"
    type: "Issue"
    data: {
        id: string
        createdAt?: string
        updatedAt?: string
        number?: number
        title?: string
        priority?: number
        sortOrder?: number
        prioritySortOrder?: number
        slaType?: string
        addedToTeamAt?: string
        trashed?: boolean | null
        labelIds?: string[]
        teamId?: string
        previousIdentifiers?: string[]
        stateId?: string
        reactionData?: unknown[]
        priorityLabel?: string
        botActor?: string | null
        identifier?: string
        url?: string
        subscriberIds?: string[]
        state?: {
            id: string
            color: string
            name: string
            type: string
        }
        team?: {
            id: string
            key: string
            name: string
        }
        labels?: unknown[]
        description?: string
        descriptionData?: string
        assignee?: {
            id: string
            name: string
        }
        projectId?: string
        [k: string]: unknown
    }
}

export type LinearIssueCreatedTrigger = SDKTrigger<LinearIssueCreatedTriggerPayload>

export interface LinearIssueUpdatedTriggerPayload {
    integrationType: "linear"
    action: "update"
    actor: {
        id: string
        name: string
        email: string
        url: string
        type: string
    }
    createdAt: string
    url?: string
    organizationId: string
    webhookTimestamp: number
    webhookId: string
    eventType: "issue.updated"
    type: "Issue"
    data: {
        id: string
        createdAt?: string
        updatedAt?: string
        number?: number
        title?: string
        priority?: number
        sortOrder?: number
        prioritySortOrder?: number
        slaType?: string
        addedToTeamAt?: string
        trashed?: boolean | null
        labelIds?: string[]
        teamId?: string
        previousIdentifiers?: string[]
        stateId?: string
        reactionData?: unknown[]
        priorityLabel?: string
        botActor?: string | null
        identifier?: string
        url?: string
        subscriberIds?: string[]
        state?: {
            id: string
            color: string
            name: string
            type: string
        }
        team?: {
            id: string
            key: string
            name: string
        }
        labels?: unknown[]
        description?: string
        descriptionData?: string
        assignee?: {
            id: string
            name: string
        }
        projectId?: string
        [k: string]: unknown
    }
}

export type LinearIssueUpdatedTrigger = SDKTrigger<LinearIssueUpdatedTriggerPayload>

export interface LinearCommentCreatedTriggerPayload {
    integrationType: "linear"
    action: "create"
    actor: {
        id: string
        name: string
        email: string
        url: string
        type: string
    }
    createdAt: string
    url?: string
    organizationId: string
    webhookTimestamp: number
    webhookId: string
    eventType: "comment.created"
    type: "Comment"
    data: {
        id: string
        body?: string
        issueId?: string
        [k: string]: unknown
    }
}

export type LinearCommentCreatedTrigger = SDKTrigger<LinearCommentCreatedTriggerPayload>

export type LinearTrigger = LinearIssueCreatedTrigger | LinearIssueUpdatedTrigger | LinearCommentCreatedTrigger

export const linearTriggers = {
    /** Trigger when a new issue is created. Optionally scope with `LinearTeam.*` / `LinearProject.*`. */
    onIssueCreated(opts?: { team?: LinearTeam; project?: LinearProject }): TypedTrigger<LinearIssueCreatedTrigger> {
        return new LinearInputConfig("cmr0tmgud043noe29m08xekp2", opts?.project?.projectId ?? null, [LinearEventType.ISSUE_CREATED], opts?.team?.teamId ?? null)
    },
    /** Trigger when an issue is updated */
    onIssueUpdated(opts?: { team?: LinearTeam; project?: LinearProject }): TypedTrigger<LinearIssueUpdatedTrigger> {
        return new LinearInputConfig("cmr0tmgud043noe29m08xekp2", opts?.project?.projectId ?? null, [LinearEventType.ISSUE_UPDATED], opts?.team?.teamId ?? null)
    },
    /** Trigger when a comment is added to an issue */
    onComment(opts?: { team?: LinearTeam; project?: LinearProject }): TypedTrigger<LinearCommentCreatedTrigger> {
        return new LinearInputConfig("cmr0tmgud043noe29m08xekp2", opts?.project?.projectId ?? null, [LinearEventType.COMMENT_CREATED], opts?.team?.teamId ?? null)
    },
    /** Trigger on all Linear events */
    trigger(opts?: { team?: LinearTeam; project?: LinearProject; eventTypes?: LinearEventType[] }): TypedTrigger<LinearTrigger> {
        return new LinearInputConfig("cmr0tmgud043noe29m08xekp2", opts?.project?.projectId ?? null, opts?.eventTypes, opts?.team?.teamId ?? null)
    },
}