// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { LinearOutputConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Linear resources ──────────────────────────────────────────

export class LinearTeam {
    constructor(public readonly teamId: string, public readonly name: string, public readonly key: string) {}

    static TerseInc = new LinearTeam("fc56076d-531f-417f-940f-36ea01b1e884", "Terse Inc", "TER")
}

export class LinearProject {
    constructor(public readonly projectId: string, public readonly name: string) {}

    static GTMIntegrations = new LinearProject("fb5f5153-860a-427e-b880-32976353634c", "GTM Integrations")
    static TerseOSSLaunchMarketing = new LinearProject("f15f12a8-a073-41f1-8a06-f45b5de4c131", "Terse OSS launch - Marketing")
    static OSSLaunchOfTerse = new LinearProject("ba5488fe-166b-476c-982a-90cc284d7f87", "OSS Launch of Terse")
    static ModalGTMOrchestrationPlatform = new LinearProject("05c2f595-0e89-4031-855c-f40f8be531b6", "Modal GTM Orchestration Platform")
    static TerseSDK = new LinearProject("c16ba571-0c78-4009-8b59-9169c73285c8", "Terse SDK")
    static TersePlatform = new LinearProject("ab4779f8-19bf-4d61-b5df-4a50f1ae0ec3", "Terse Platform")
}

// ── Linear tools ──────────────────────────────────────────────

/**
 * Searches Linear issues by keyword, state filter, and/or date range filters. Use this before reading individual tickets. Results are ordered by most recently updated first. Use 'after' cursor to paginate.
 */
export interface LinearSearchTicketParams {
    /**
     * Plain-text keyword search (matched against titles, descriptions, etc.).
     *             Do NOT include operators or field filters. Use dedicated parameters instead.
     *             ✓ "block kit"
     *             ✗ "team:TER state:Done updated:>2026-02-04 block kit"
     */
    searchTerm?: string
    /**
     * Filter to only include issues with these state names. Available states: Triage, Backlog, Todo, In Progress, In Review, Done, Canceled.
     */
    stateNames?: ("Triage" | "Backlog" | "Todo" | "In Progress" | "In Review" | "Done" | "Canceled")[] | null
    /**
     * Which date field to filter on. Required if using dateAfter or dateBefore. Options: 'updatedAt' (when issue was last modified) or 'createdAt' (when issue was created).
     */
    dateFilterField?: ("updatedAt" | "createdAt") | null
    /**
     * Filter to only include issues where the dateFilterField is on or after this date. ISO 8601 format (e.g., '2026-01-01' or '2026-01-01T00:00:00Z').
     */
    dateAfter?: string | null
    /**
     * Filter to only include issues where the dateFilterField is on or before this date. ISO 8601 format (e.g., '2026-02-01' or '2026-02-01T23:59:59Z').
     */
    dateBefore?: string | null
    /**
     * Maximum number of issues to return. Defaults to 10 if not provided.
     */
    limit?: number | null
    /**
     * Cursor for pagination. Use the endCursor from the previous response to fetch the next page of results.
     */
    after?: string | null
}

export interface LinearSearchTicketResult {
    success: boolean
    actions?: RunHistoryAction[]
    issues: {
        id: string
        identifier: string
        title: string
        description?: string | null
        state: string
        priority?: number | null
        assignee: {
            id: string
            name: string
            email?: string
        } | null
        url: string
        createdAt: string | Date
        updatedAt: string | Date
    }[]
    count: number
    query: string
    pagination: {
        hasNextPage: boolean
        endCursor: string | null
        limit: number | null
    }
}

/**
 * List teams in the Linear workspace. Use to pick teamId when creating tickets or when calling linear_get_states, linear_get_labels, or linear_get_projects for a specific team.
 */
export interface LinearGetTeamsParams {}

export interface LinearGetTeamsResult {
    success: boolean
    actions?: RunHistoryAction[]
    teams: {
        id: string
        name: string
        key: string
    }[]
}

/**
 * List workflow states for the Linear workspace or a specific team. Use when creating or updating issues to pick a valid stateId (e.g. "Todo", "In Progress", "Done").
 */
export interface LinearGetStatesParams {
    /**
     * Optional team ID to limit results to that team's states.
     */
    teamId?: string | null
}

export interface LinearGetStatesResult {
    success: boolean
    actions?: RunHistoryAction[]
    states: {
        id: string
        name: string
        type: string
        color: string
        teamId: string
    }[]
}

/**
 * List issue labels for the Linear workspace or a specific team. Use to pick labelIds for linear_create_ticket or linear_update_ticket.
 */
export interface LinearGetLabelsParams {
    /**
     * Optional team ID to limit results to that team's labels.
     */
    teamId?: string | null
}

export interface LinearGetLabelsResult {
    success: boolean
    actions?: RunHistoryAction[]
    labels: {
        id: string
        name: string
        color: string
        teamId: string
    }[]
}

/**
 * List projects for the Linear workspace or a specific team. Use to pick projectId when creating or updating issues.
 */
export interface LinearGetProjectsParams {
    /**
     * Optional team ID to limit results to that team's projects.
     */
    teamId?: string | null
}

export interface LinearGetProjectsResult {
    success: boolean
    actions?: RunHistoryAction[]
    projects: {
        id: string
        name: string
        description?: string
        teamId: string
    }[]
}

/**
 * List users in the Linear workspace. Use to pick assigneeId or subscriberIds when creating or updating issues.
 */
export interface LinearGetUsersParams {}

export interface LinearGetUsersResult {
    success: boolean
    actions?: RunHistoryAction[]
    users: {
        id: string
        name: string
        email: string
        avatarUrl?: string
    }[]
}

/**
 * Create a new Linear issue/ticket.
 */
export interface LinearCreateTicketParams {
    ticket: {
        title: string
        teamId: string
        description?: string | null
        stateId?: string | null
        priority?: number | null
        projectId?: string | null
        labelIds?: string[] | null
        assigneeId?: string | null
    }
}

export interface LinearCreateTicketResult {
    success: boolean
    actions?: RunHistoryAction[]
    issue: {
        id: string
        identifier: string
        title: string
        description?: string | null
        url: string
        createdAt?: string | Date
        updatedAt?: string | Date
    }
}

/**
 * Update an existing Linear issue/ticket. Use linear_search_ticket to find the issue ID, and linear_get_states, linear_get_users, linear_get_projects, linear_get_teams to find valid IDs for each field.
 */
export interface LinearUpdateTicketParams {
    /**
     * The ID of the Linear issue to update. Use linear_search_ticket to find the issue ID.
     */
    issueId: string
    updates: {
        /**
         * The updated title of the ticket.
         */
        title?: string | null
        /**
         * The updated description of the ticket.
         */
        description?: string | null
        /**
         * The ID of the state to set. Use linear_get_states to find available states.
         */
        stateId?: string | null
        /**
         * The priority of the ticket. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
         */
        priority?: number | null
        /**
         * The ID of the project to associate with the ticket. Use linear_get_projects to find available projects.
         */
        projectId?: string | null
        /**
         * The IDs of labels to add to the ticket. Use linear_get_labels to find available labels.
         */
        labelIds?: string[] | null
        /**
         * The ID of the user to assign the ticket to. Use linear_get_users to find available users and their IDs.
         */
        assigneeId?: string | null
    }
}

export interface LinearUpdateTicketResult {
    success: boolean
    actions?: RunHistoryAction[]
    issue: {
        id: string
        identifier: string
        title: string
        description?: string | null
        url: string
        createdAt?: string | Date
        updatedAt?: string | Date
    }
}

/**
 * Add a comment to an existing Linear issue. Use linear_search_ticket to find the issue ID.
 */
export interface LinearAddCommentParams {
    /**
     * The ID of the Linear issue to add the comment to. Use linear_search_ticket to find the issue ID.
     */
    issueId: string
    /**
     * The comment text to add to the issue.
     */
    body: string
}

export interface LinearAddCommentResult {
    success: boolean
    actions?: RunHistoryAction[]
    comment: {
        id: string
        body?: string
        createdAt?: string | Date
        updatedAt?: string | Date
    }
}

/**
 * Read detailed information about a Linear issue/ticket including title, description, state, assignee, and optionally all comments.
 * Use the issue ID (UUID) or the issue identifier (e.g. "TEAM-123"). Use this after searching for tickets to get full details.
 */
export interface LinearReadTicketParams {
    /**
     * The Linear issue ID (UUID) or identifier (e.g. 'PROJ-123').
     */
    issueId: string
    /**
     * Whether to include comments. Defaults to true.
     */
    includeComments?: boolean | null
}

export interface LinearReadTicketResult {
    success: boolean
    actions?: RunHistoryAction[]
    issue: {
        id: string
        identifier: string
        title: string
        description?: string | null
        state: string
        priority?: number | null
        assignee: {
            id: string
            name: string
            email?: string
        } | null
        url: string
        createdAt: string | Date
        updatedAt: string | Date
        team: {
            id: string
            name: string
            key: string
        } | null
        project: {
            id: string
            name: string
        } | null
        dueDate?: string | Date
        estimate?: number | null
    }
    comments?: {
        id: string
        body: string
        authorId: string
        createdAt: string
    }[]
}

export type LinearGeneratedTools = {
    /** Searches Linear issues by keyword, state filter, and/or date range filters. Use this before reading individual tickets. Results are ordered by most recently updated first. Use 'after' cursor to paginate. */
    searchTickets(params: LinearSearchTicketParams): Promise<LinearSearchTicketResult>
    /** List teams in the Linear workspace. Use to pick teamId when creating tickets or when calling linear_get_states, linear_get_labels, or linear_get_projects for a specific team. */
    getTeams(params: LinearGetTeamsParams): Promise<LinearGetTeamsResult>
    /** List workflow states for the Linear workspace or a specific team. Use when creating or updating issues to pick a valid stateId (e.g. "Todo", "In Progress", "Done"). */
    getStates(params: LinearGetStatesParams): Promise<LinearGetStatesResult>
    /** List issue labels for the Linear workspace or a specific team. Use to pick labelIds for linear_create_ticket or linear_update_ticket. */
    getLabels(params: LinearGetLabelsParams): Promise<LinearGetLabelsResult>
    /** List projects for the Linear workspace or a specific team. Use to pick projectId when creating or updating issues. */
    getProjects(params: LinearGetProjectsParams): Promise<LinearGetProjectsResult>
    /** List users in the Linear workspace. Use to pick assigneeId or subscriberIds when creating or updating issues. */
    getUsers(params: LinearGetUsersParams): Promise<LinearGetUsersResult>
    /** Create a new Linear issue/ticket. */
    createTicket(params: LinearCreateTicketParams): Promise<LinearCreateTicketResult>
    /** Update an existing Linear issue/ticket. Use linear_search_ticket to find the issue ID, and linear_get_states, linear_get_users, linear_get_projects, linear_get_teams to find valid IDs for each field. */
    updateTicket(params: LinearUpdateTicketParams): Promise<LinearUpdateTicketResult>
    /** Add a comment to an existing Linear issue. Use linear_search_ticket to find the issue ID. */
    addComment(params: LinearAddCommentParams): Promise<LinearAddCommentResult>
    /** Read detailed information about a Linear issue/ticket including title, description, state, assignee, and optionally all comments.
Use the issue ID (UUID) or the issue identifier (e.g. "TEAM-123"). Use this after searching for tickets to get full details. */
    readTicket(params: LinearReadTicketParams): Promise<LinearReadTicketResult>
}

export const linearTools: LinearGeneratedTools = {
    searchTickets: (params: LinearSearchTicketParams) =>
        TerseAgent.executeTool<LinearSearchTicketResult>("linear_search_ticket", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    getTeams: (params: LinearGetTeamsParams) =>
        TerseAgent.executeTool<LinearGetTeamsResult>("linear_get_teams", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    getStates: (params: LinearGetStatesParams) =>
        TerseAgent.executeTool<LinearGetStatesResult>("linear_get_states", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    getLabels: (params: LinearGetLabelsParams) =>
        TerseAgent.executeTool<LinearGetLabelsResult>("linear_get_labels", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    getProjects: (params: LinearGetProjectsParams) =>
        TerseAgent.executeTool<LinearGetProjectsResult>("linear_get_projects", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    getUsers: (params: LinearGetUsersParams) =>
        TerseAgent.executeTool<LinearGetUsersResult>("linear_get_users", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    createTicket: (params: LinearCreateTicketParams) =>
        TerseAgent.executeTool<LinearCreateTicketResult>("linear_create_ticket", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    updateTicket: (params: LinearUpdateTicketParams) =>
        TerseAgent.executeTool<LinearUpdateTicketResult>("linear_update_ticket", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    addComment: (params: LinearAddCommentParams) =>
        TerseAgent.executeTool<LinearAddCommentResult>("linear_add_comment", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
    readTicket: (params: LinearReadTicketParams) =>
        TerseAgent.executeTool<LinearReadTicketResult>("linear_read_ticket", { ...(params), integrationId: "cmr0tmgud043noe29m08xekp2" }),
}

// ── Linear skill ──────────────────────────────────────────────

/** Linear — read and write issues, optionally scoped to a team or project */
export function linearSkill(opts?: { team?: LinearTeam; project?: LinearProject }): TypedSkill<"linear_add_comment" | "linear_create_ticket" | "linear_update_ticket"> {
    return new LinearOutputConfig(
        "cmr0tmgud043noe29m08xekp2",
        opts?.team?.teamId ?? null,
        opts?.team?.name ?? null,
        opts?.project?.projectId ?? null
    )
}