// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { NotionConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Notion resources ──────────────────────────────────────────

export class NotionDatabase {
    constructor(public readonly databaseId: string, public readonly title: string) {}

    static OlivierBlogPosts = new NotionDatabase("38f71d11-679e-807a-8b30-000b61c05c40", "Olivier Blog Posts")
}

export class NotionPage {
    constructor(public readonly pageId: string, public readonly title: string) {}

    static CodingAgentsHaveSettledTheStaticVsDynamicTypingDebate = new NotionPage("38d71d11-679e-807e-8d5b-d944c1ee0c49", "Coding agents have settled the static vs. dynamic typing debate")
    static HowIUsedVercelSDeepsecToFix109SecurityIssuesFor139 = new NotionPage("39e71d11-679e-80ed-a166-c0383238b5f1", "How I used Vercel’s deepsec to fix 109 security issues for $139")
    static HowWeBuiltSecureAutomatedLearningLoopsInModalAndClaudeCode = new NotionPage("38371d11-679e-80cd-b5bc-ec08c9916d69", "How we built secure automated learning loops in Modal and Claude Code")
    static WhatIsContextAsCode = new NotionPage("38f71d11-679e-80a7-940a-e84215ac2536", "What is Context as Code")
}

// ── Notion tools ──────────────────────────────────────────────

/**
 * Gets the schema/structure of the Notion data source. This tool retrieves all property definitions including property names, types, valid options for select/status fields, and exact format examples for how to construct each property when writing to the database.
 *
 * Use this tool:
 * - Before writing any data to determine available properties and their correct formats
 * - To understand what property names exist and their data types
 * - To get valid option values for select, multi_select, and status properties
 * - To see exact format examples for constructing properties in the Notion API format
 * - To determine how to write to the Notion database by understanding its structure
 *
 * The schema information returned by this tool should be used to properly format properties when calling notion_create_or_update_database_row to create or update rows in the database.
 */
export interface NotionGetSchemaParams {
    /**
     * The Notion database ID (data source ID) to get the schema for.
     */
    databaseId: string
}

export interface NotionGetSchemaResult {
    success: true
    actions?: RunHistoryAction[]
    data_source_id: string
    database_name: string
    schema: {
        [k: string]: {
            type: string
            id: string
            options?: string[]
            format_example?: string
        }
    }
    property_count: number
}

/**
 * Query a Notion data source (database) to retrieve pages that match specific criteria.
 *
 * WHEN TO USE THIS TOOL:
 * - Verify if the database contains any existing records and avoid creating duplicates.
 * - When you need to find specific pages matching certain criteria (e.g., status, date ranges, property values)
 * - When you need to retrieve a subset of pages rather than all pages in the database
 * - When working with large databases and need pagination to retrieve results in batches
 * - When you only need specific properties from pages (use filter_properties for efficiency)
 *
 * WHAT THIS TOOL DOES:
 * 1. Filters pages at the Notion API level (not client-side) for maximum efficiency
 * 2. Supports complex filtering with AND/OR logic, property filters, and timestamp filters
 * 3. Supports pagination - use start_cursor from previous responses to get next page
 * 4. Supports filter_properties to only fetch needed fields, reducing response size and improving speed
 *
 * FILTERING:
 * - Property filters: Filter by any database property (title, number, date, select, status, checkbox, etc.)
 * - Timestamp filters: Filter by created_time or last_edited_time (these are SYSTEM FIELDS, not database properties)
 * - Compound filters: Combine filters with AND/OR logic
 * - All filtering happens server-side at Notion for efficiency
 *
 * SYSTEM FIELDS (available on ALL pages, not shown in schema):
 * - created_time: When the page was created. Use timestamp filter format (NO "property" field).
 * - last_edited_time: When the page was last edited. Use timestamp filter format (NO "property" field).
 * - created_by: User who created the page. Use people filter WITH "property" field.
 * - last_edited_by: User who last edited the page. Use people filter WITH "property" field.
 *
 * IMPORTANT: Timestamp filters (created_time, last_edited_time) use a DIFFERENT format than property filters:
 * - CORRECT: {"timestamp": "created_time", "created_time": {"on_or_after": "2024-01-01"}}
 * - WRONG: {"property": "created_time", "date": {"on_or_after": "2024-01-01"}}
 *
 * PAGINATION:
 * - Use page_size to control how many results per page (default: all results)
 * - Use start_cursor from the response to fetch the next page
 * - The response includes has_more and next_cursor when more pages are available
 *
 * FILTER_PROPERTIES:
 * - Specify only the properties you need to reduce response size and improve performance
 * - Especially important for databases with many properties or complex formulas/rollups
 * - You can fetch additional properties later using Retrieve page property item API
 *
 * NOTE: This tool does NOT return the database schema. Use notion_get_schema if you need schema information.
 */
export interface NotionQueryDatabaseParams {
    /**
     * The Notion database ID (data source ID) to query.
     */
    databaseId: string
    /**
     * Array of property names or IDs to include in results. Only these properties will be returned, improving performance. Use property names from the database schema.
     */
    filter_properties?: string[] | null
    /**
     * JSON string with filter object to query pages matching specific criteria. Supports complex filtering with AND/OR logic, property filters, and timestamp filters.
     *
     * BASIC STRUCTURE:
     * - Property filter: { "property": "Property Name", "type": { "condition": value } }
     * - Timestamp filter: { "timestamp": "created_time" | "last_edited_time", "created_time" | "last_edited_time": { "condition": value } }
     * - Compound filter: { "and": [...] } or { "or": [...] } to combine multiple filters (nesting supported up to 2 levels)
     *
     * PROPERTY FILTER TYPES AND CONDITIONS:
     *
     * 1. CHECKBOX: { "property": "Name", "checkbox": { "equals": true|false } | { "does_not_equal": true|false } }
     *
     * 2. DATE: { "property": "Name", "date": {
     * "after": "2021-05-10" | "2021-05-10T12:00:00" | "2021-10-15T12:00:00-07:00",
     * "before": "2021-05-10",
     * "equals": "2021-05-10",
     * "on_or_after": "2021-05-10",
     * "on_or_before": "2021-05-10",
     * "is_empty": true,
     * "is_not_empty": true,
     * "past_week": {},
     * "past_month": {},
     * "past_year": {},
     * "next_week": {},
     * "next_month": {},
     * "next_year": {},
     * "this_week": {}
     * } }
     *
     * 3. FILES: { "property": "Name", "files": { "is_empty": true } | { "is_not_empty": true } }
     *
     * 4. FORMULA: { "property": "Name", "formula": {
     * "checkbox": { checkbox conditions },
     * "date": { date conditions },
     * "number": { number conditions },
     * "string": { rich_text conditions }
     * } }
     *
     * 5. MULTI_SELECT: { "property": "Name", "multi_select": {
     * "contains": "Value",
     * "does_not_contain": "Value",
     * "is_empty": true,
     * "is_not_empty": true
     * } }
     *
     * 6. NUMBER: { "property": "Name", "number": {
     * "equals": 42,
     * "does_not_equal": 42,
     * "greater_than": 42,
     * "less_than": 42,
     * "greater_than_or_equal_to": 42,
     * "less_than_or_equal_to": 42,
     * "is_empty": true,
     * "is_not_empty": true
     * } }
     *
     * 7. PEOPLE (also for created_by, last_edited_by): { "property": "Name", "people": {
     * "contains": "uuid-v4",
     * "does_not_contain": "uuid-v4",
     * "is_empty": true,
     * "is_not_empty": true
     * } }
     *
     * 8. RELATION: { "property": "Name", "relation": {
     * "contains": "uuid-v4",
     * "does_not_contain": "uuid-v4",
     * "is_empty": true,
     * "is_not_empty": true
     * } }
     *
     * 9. RICH_TEXT (also title): { "property": "Name", "rich_text": {
     * "contains": "string",
     * "does_not_contain": "string",
     * "does_not_equal": "string",
     * "ends_with": "string",
     * "equals": "string",
     * "is_empty": true,
     * "is_not_empty": true,
     * "starts_with": "string"
     * } }
     *
     * 10. ROLLUP: { "property": "Name", "rollup": {
     * "any": { filter condition },
     * "every": { filter condition },
     * "none": { filter condition },
     * "date": { date conditions },
     * "number": { number conditions }
     * } }
     *
     * 11. SELECT: { "property": "Name", "select": {
     * "equals": "Value",
     * "does_not_equal": "Value",
     * "is_empty": true,
     * "is_not_empty": true
     * } }
     *
     * 12. STATUS: { "property": "Name", "status": {
     * "equals": "Value",
     * "does_not_equal": "Value",
     * "is_empty": true,
     * "is_not_empty": true
     * } }
     *
     * 13. TIMESTAMP: { "timestamp": "created_time" | "last_edited_time", "created_time" | "last_edited_time": {
     * same conditions as DATE filter (after, before, equals, on_or_after, on_or_before, is_empty, is_not_empty, past_week, past_month, past_year, next_week, next_month, next_year, this_week)
     * } }
     * NOTE: Do NOT include "property" field for timestamp filters.
     *
     * 14. VERIFICATION: { "property": "Name", "verification": { "status": "verified" | "expired" | "none" } }
     *
     * 15. UNIQUE_ID: { "property": "Name", "unique_id": {
     * "equals": 42,
     * "does_not_equal": 42,
     * "greater_than": 42,
     * "less_than": 42,
     * "greater_than_or_equal_to": 42,
     * "less_than_or_equal_to": 42
     * } }
     *
     * COMPOUND FILTERS:
     * - AND: { "and": [filter1, filter2, ...] } - all conditions must match
     * - OR: { "or": [filter1, filter2, ...] } - any condition can match
     * - Nesting: Can nest AND/OR up to 2 levels deep
     *
     * EXAMPLES:
     * - Simple: "{\"property\": \"Task completed\", \"checkbox\": {\"equals\": true}}"
     * - Compound: "{\"and\": [{\"property\": \"Done\", \"checkbox\": {\"equals\": true}}, {\"or\": [{\"property\": \"Tags\", \"multi_select\": {\"contains\": \"A\"}}, {\"property\": \"Tags\", \"multi_select\": {\"contains\": \"B\"}}]}]}"
     * - Timestamp: "{\"timestamp\": \"created_time\", \"created_time\": {\"on_or_after\": \"2023-02-08\"}}"
     */
    filter?: string | null
    /**
     * Number of results per page (1-100). Default returns all results. Use pagination for large databases.
     */
    page_size?: number | null
    /**
     * Cursor from previous response to fetch next page. Use next_cursor from response when has_more is true.
     */
    start_cursor?: string | null
    /**
     * Filter results to only pages or data sources. Only relevant for wiki databases.
     */
    result_type?: ("page" | "data_source") | null
}

export type NotionQueryDatabaseResult =
    | {
          success: true
          actions?: RunHistoryAction[]
          pages: {
              page_id: string
              properties: {
                  [k: string]:
                      | string
                      | number
                      | boolean
                      | null
                      | string[]
                      | {
                            start?: string
                            end?: string | null
                            time_zone?: string | null
                        }
                      | {
                            id: string
                            name?: string
                            object?: string
                        }
                      | {
                            id: string
                            name?: string
                            object?: string
                        }[]
                      | {
                            name: string
                            type: string
                            file?: string
                            external?: string
                        }[]
                      | {
                            [k: string]: unknown
                        }
              }
              url?: string
              created_time?: string
              last_edited_time?: string
          }[]
          total_returned: number
          has_more: boolean
          next_cursor: string | null
      }
    | {
          success: false
          actions?: RunHistoryAction[]
          pages: {
              page_id: string
              properties: {
                  [k: string]:
                      | string
                      | number
                      | boolean
                      | null
                      | string[]
                      | {
                            start?: string
                            end?: string | null
                            time_zone?: string | null
                        }
                      | {
                            id: string
                            name?: string
                            object?: string
                        }
                      | {
                            id: string
                            name?: string
                            object?: string
                        }[]
                      | {
                            name: string
                            type: string
                            file?: string
                            external?: string
                        }[]
                      | {
                            [k: string]: unknown
                        }
              }
              url?: string
              created_time?: string
              last_edited_time?: string
          }[]
          total_returned: 0
          has_more: false
          next_cursor: null
          error: string
          hint: string
      }

/**
 * Create or update a **row** (entry) in a Notion database. Use with databaseId and properties_json. Not for standalone pages — use notion_create_or_update_page for those.
 *
 * Use notion_get_schema first to understand property names and types. Use notion_query_database to find page_id for updates. Provide page_id null to create a new row, or a valid page_id to update. Property format: Title, Rich Text, Select, Status, etc. per notion_get_schema.
 */
export interface NotionCreateOrUpdateDatabaseRowParams {
    /**
     * The Notion database ID (data source ID).
     */
    databaseId: string
    /**
     * The ID of the row to update (from notion_query_database). MUST be null to create a new row. Provide a valid page ID to update an existing row.
     */
    page_id: string | null
    /**
     * JSON string with property names and Notion-formatted values. Example: "{\"Name\": {\"title\": [{\"text\": {\"content\": \"New Item\"}}]}, \"Status\": {\"select\": {\"name\": \"In Progress\"}}}"
     */
    properties_json: string
}

export interface NotionCreateOrUpdateDatabaseRowResult {
    success: true
    actions?: RunHistoryAction[]
    action: "created" | "updated"
    page_id: string
    url?: string
}

/**
 * Create or update a **standalone page**. Not for database entries — use notion_create_or_update_database_row for those.
 *
 * **Create**: Omit page_id (or pass null). Supply parentPageId (allowed page ID from config), title. Creates a new empty subpage under the parent. Use notion_modify_blocks on the returned page_id to add content.
 * **Update**: Pass page_id of an existing page to update its title. parentPageId is ignored when updating. Use notion_modify_blocks to change page content.
 */
export interface NotionCreateOrUpdatePageParams {
    /**
     * ID of an existing page to update. Omit or null to create a new subpage under parentPageId.
     */
    page_id?: string | null
    /**
     * Required for create: the allowed page ID under which to create the new subpage (from the Notion config list). Ignored when page_id is provided for update.
     */
    parentPageId?: string | null
    /**
     * The page title (used for both create and update).
     */
    title: string
}

export interface NotionCreateOrUpdatePageResult {
    success: true
    actions?: RunHistoryAction[]
    action: "created" | "updated"
    page_id: string
    url?: string
}

/**
 * Call this tool ONCE at the beginning of your run to get the page state. After calling it once, remember and reuse the results - DO NOT call it multiple times in the same run.
 *
 * This tool returns the current state of the page including all properties, metadata, and content blocks.
 */
export interface NotionQueryPageParams {
    /**
     * The Notion page ID to query.
     */
    pageId: string
}

export interface NotionQueryPageResult {
    page_id: string
    object: string
    url?: string
    public_url?: string | null
    created_time?: string
    last_edited_time?: string
    archived?: boolean
    icon?: {
        [k: string]: unknown
    } | null
    cover?: {
        [k: string]: unknown
    } | null
    parent?: {
        [k: string]: unknown
    }
    created_by?: {
        id: string
        name?: string
        object?: string
    }
    last_edited_by?: {
        id: string
        name?: string
        object?: string
    }
    in_trash?: boolean
    success: true
    actions?: RunHistoryAction[]
    properties: {
        [k: string]:
            | string
            | number
            | boolean
            | null
            | string[]
            | {
                  start?: string
                  end?: string | null
                  time_zone?: string | null
              }
            | {
                  id: string
                  name?: string
                  object?: string
              }
            | {
                  id: string
                  name?: string
                  object?: string
              }[]
            | {
                  name: string
                  type: string
                  file?: string
                  external?: string
              }[]
            | {
                  [k: string]: unknown
              }
    }
    properties_raw?: {
        [k: string]: unknown
    }
    blocks: NotionBlock[]
    blocks_count: number
}
export interface NotionBlock {
    id: string
    type: string
    object: string
    created_time?: string
    last_edited_time?: string
    created_by?: {
        id: string
        name?: string
        object?: string
    }
    last_edited_by?: {
        id: string
        name?: string
        object?: string
    }
    has_children?: boolean
    archived?: boolean
    content?: string
    rich_text?: {
        [k: string]: unknown
    }[]
    checked?: boolean
    language?: string
    icon?: {
        [k: string]: unknown
    }
    table_width?: number
    has_column_header?: boolean
    has_row_header?: boolean
    caption?: string
    file?: string
    external?: string
    url?: string
    page_id?: string
    database_id?: string
    children?: NotionBlock[]
}

/**
 * Add, update, or delete blocks in page content. Use this to modify page content (paragraphs, headings, lists, etc.).
 *
 * Accepts a single operation object (backwards compatible) OR an array of operation objects executed sequentially. One approval covers the whole batch.
 *
 * Operations:
 * - append: Add new blocks to the page (or to a parent block if parent_block_id is provided). Use optional after_block_id to insert after a specific block instead of at the end. Get block IDs from notion_query_page.
 * - update: Update an existing block by block_id
 * - delete: Delete (archive) a block by block_id
 *
 * Positional insertion: Use after_block_id with append to insert blocks after a specific block instead of at the end.
 *
 * Moving blocks within a page:
 * 1. Retrieve the block content with notion_query_page.
 * 2. Append the block at the desired position (use after_block_id for position, or parent_block_id for container).
 * 3. Delete the original block with the "delete" operation.
 *
 * Examples — single operation:
 * - Append: {"operation": "append", "blocks": [{"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Hello world"}}]}}]}
 * - Append after a block: {"operation": "append", "after_block_id": "xyz789", "blocks": [{"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Inserted here"}}]}}]}
 * - Update: {"operation": "update", "block_id": "abc123", "block": {"paragraph": {"rich_text": [{"type": "text", "text": {"content": "Updated text"}}]}}}
 * - Delete: {"operation": "delete", "block_id": "abc123"}
 *
 * Examples — batch (array):
 * [{"operation": "append", "blocks": [...]}, {"operation": "update", "block_id": "abc", "block": {...}}, {"operation": "delete", "block_id": "def"}]
 *
 * Error recovery: If Notion returns an error that suggests JSON/body/validation incompatibility, retry. First fix the specific issue mentioned in the error; if that is unclear or still failing, retry with a simpler payload (fewer blocks, simpler block types like plain paragraphs).
 */
export interface NotionModifyBlocksParams {
    /**
     * The Notion page ID to modify.
     */
    pageId: string
    /**
     * JSON string: a single operation object OR an array of operation objects (executed in order).
     * Each operation: operation ("append"|"update"|"delete"); for append: blocks (array), optional parent_block_id, optional after_block_id; for update: block_id, block; for delete: block_id.
     * Append with after_block_id inserts after that block; omit for end of page/parent.
     */
    operation_json: string
}

export type NotionModifyBlocksResult =
    | (
          | {
                success: true
                actions?: RunHistoryAction[]
                operation: "append"
                block_ids: string[]
                blocks_count: number
            }
          | {
                success: true
                actions?: RunHistoryAction[]
                operation: "update" | "delete"
                block_id: string
            }
          | {
                success: true
                actions?: RunHistoryAction[]
                operations: (
                    | {
                          operation: "append"
                          actions: RunHistoryAction[]
                          block_ids: string[]
                          blocks_count: number
                      }
                    | {
                          operation: "update"
                          actions: RunHistoryAction[]
                          block_id: string
                      }
                    | {
                          operation: "delete"
                          actions: RunHistoryAction[]
                          block_id: string
                      }
                )[]
                block_ids: string[]
                total_operations: number
            }
      )
    | {
          success: false
          actions?: RunHistoryAction[]
          error: string
          block_ids: string[]
          operations?: (
              | {
                    operation: "append"
                    actions: RunHistoryAction[]
                    block_ids: string[]
                    blocks_count: number
                }
              | {
                    operation: "update"
                    actions: RunHistoryAction[]
                    block_id: string
                }
              | {
                    operation: "delete"
                    actions: RunHistoryAction[]
                    block_id: string
                }
          )[]
          failed_at_index?: number
          total_operations?: number
          hint?: string
          retry_instructions?: string
      }

/**
 * List users in the Notion workspace. Use this to resolve user names to Notion user IDs
 * for populating People properties (e.g., Assignee, Owner) when creating or updating database pages.
 *
 * Returns workspace members (not bots). Optionally filter by name with the query parameter.
 *
 * Use the returned user IDs in people property format:
 * {"Assignee": {"people": [{"object": "user", "id": "<user_id>"}]}}
 */
export interface NotionListUsersParams {
    /**
     * Optional search query to filter users by name. Case-insensitive partial match.
     */
    query?: string | null
}

export interface NotionListUsersResult {
    success: true
    actions?: RunHistoryAction[]
    users: {
        id: string
        name: string
        email?: string
    }[]
    count: number
}

export type NotionGeneratedTools = {
    /** Gets the schema/structure of the Notion data source. This tool retrieves all property definitions including property names, types, valid options for select/status fields, and exact format examples for how to construct each property when writing to the database.

Use this tool:
- Before writing any data to determine available properties and their correct formats
- To understand what property names exist and their data types
- To get valid option values for select, multi_select, and status properties
- To see exact format examples for constructing properties in the Notion API format
- To determine how to write to the Notion database by understanding its structure

The schema information returned by this tool should be used to properly format properties when calling notion_create_or_update_database_row to create or update rows in the database. */
    getDatasourceSchema(params: NotionGetSchemaParams): Promise<NotionGetSchemaResult>
    /** Query a Notion data source (database) to retrieve pages that match specific criteria.

WHEN TO USE THIS TOOL:
- Verify if the database contains any existing records and avoid creating duplicates.
- When you need to find specific pages matching certain criteria (e.g., status, date ranges, property values)
- When you need to retrieve a subset of pages rather than all pages in the database
- When working with large databases and need pagination to retrieve results in batches
- When you only need specific properties from pages (use filter_properties for efficiency)

WHAT THIS TOOL DOES:
1. Filters pages at the Notion API level (not client-side) for maximum efficiency
2. Supports complex filtering with AND/OR logic, property filters, and timestamp filters
3. Supports pagination - use start_cursor from previous responses to get next page
4. Supports filter_properties to only fetch needed fields, reducing response size and improving speed

FILTERING:
- Property filters: Filter by any database property (title, number, date, select, status, checkbox, etc.)
- Timestamp filters: Filter by created_time or last_edited_time (these are SYSTEM FIELDS, not database properties)
- Compound filters: Combine filters with AND/OR logic
- All filtering happens server-side at Notion for efficiency

SYSTEM FIELDS (available on ALL pages, not shown in schema):
- created_time: When the page was created. Use timestamp filter format (NO "property" field).
- last_edited_time: When the page was last edited. Use timestamp filter format (NO "property" field).
- created_by: User who created the page. Use people filter WITH "property" field.
- last_edited_by: User who last edited the page. Use people filter WITH "property" field.

IMPORTANT: Timestamp filters (created_time, last_edited_time) use a DIFFERENT format than property filters:
- CORRECT: {"timestamp": "created_time", "created_time": {"on_or_after": "2024-01-01"}}
- WRONG: {"property": "created_time", "date": {"on_or_after": "2024-01-01"}}

PAGINATION:
- Use page_size to control how many results per page (default: all results)
- Use start_cursor from the response to fetch the next page
- The response includes has_more and next_cursor when more pages are available

FILTER_PROPERTIES:
- Specify only the properties you need to reduce response size and improve performance
- Especially important for databases with many properties or complex formulas/rollups
- You can fetch additional properties later using Retrieve page property item API

NOTE: This tool does NOT return the database schema. Use notion_get_schema if you need schema information. */
    queryDatabase(params: NotionQueryDatabaseParams): Promise<NotionQueryDatabaseResult>
    /** Create or update a **row** (entry) in a Notion database. Use with databaseId and properties_json. Not for standalone pages — use notion_create_or_update_page for those.

Use notion_get_schema first to understand property names and types. Use notion_query_database to find page_id for updates. Provide page_id null to create a new row, or a valid page_id to update. Property format: Title, Rich Text, Select, Status, etc. per notion_get_schema. */
    createOrUpdateDatabaseRow(params: NotionCreateOrUpdateDatabaseRowParams): Promise<NotionCreateOrUpdateDatabaseRowResult>
    /** Create or update a **standalone page**. Not for database entries — use notion_create_or_update_database_row for those.

**Create**: Omit page_id (or pass null). Supply parentPageId (allowed page ID from config), title. Creates a new empty subpage under the parent. Use notion_modify_blocks on the returned page_id to add content.
**Update**: Pass page_id of an existing page to update its title. parentPageId is ignored when updating. Use notion_modify_blocks to change page content. */
    createOrUpdatePageStandalone(params: NotionCreateOrUpdatePageParams): Promise<NotionCreateOrUpdatePageResult>
    /** Call this tool ONCE at the beginning of your run to get the page state. After calling it once, remember and reuse the results - DO NOT call it multiple times in the same run.

This tool returns the current state of the page including all properties, metadata, and content blocks. */
    queryPage(params: NotionQueryPageParams): Promise<NotionQueryPageResult>
    /** Add, update, or delete blocks in page content. Use this to modify page content (paragraphs, headings, lists, etc.).

Accepts a single operation object (backwards compatible) OR an array of operation objects executed sequentially. One approval covers the whole batch.

Operations:
- append: Add new blocks to the page (or to a parent block if parent_block_id is provided). Use optional after_block_id to insert after a specific block instead of at the end. Get block IDs from notion_query_page.
- update: Update an existing block by block_id
- delete: Delete (archive) a block by block_id

Positional insertion: Use after_block_id with append to insert blocks after a specific block instead of at the end.

Moving blocks within a page:
1. Retrieve the block content with notion_query_page.
2. Append the block at the desired position (use after_block_id for position, or parent_block_id for container).
3. Delete the original block with the "delete" operation.

Examples — single operation:
- Append: {"operation": "append", "blocks": [{"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Hello world"}}]}}]}
- Append after a block: {"operation": "append", "after_block_id": "xyz789", "blocks": [{"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Inserted here"}}]}}]}
- Update: {"operation": "update", "block_id": "abc123", "block": {"paragraph": {"rich_text": [{"type": "text", "text": {"content": "Updated text"}}]}}}
- Delete: {"operation": "delete", "block_id": "abc123"}

Examples — batch (array):
[{"operation": "append", "blocks": [...]}, {"operation": "update", "block_id": "abc", "block": {...}}, {"operation": "delete", "block_id": "def"}]

Error recovery: If Notion returns an error that suggests JSON/body/validation incompatibility, retry. First fix the specific issue mentioned in the error; if that is unclear or still failing, retry with a simpler payload (fewer blocks, simpler block types like plain paragraphs). */
    modifyBlocks(params: NotionModifyBlocksParams): Promise<NotionModifyBlocksResult>
    /** List users in the Notion workspace. Use this to resolve user names to Notion user IDs
for populating People properties (e.g., Assignee, Owner) when creating or updating database pages.

Returns workspace members (not bots). Optionally filter by name with the query parameter.

Use the returned user IDs in people property format:
{"Assignee": {"people": [{"object": "user", "id": "<user_id>"}]}} */
    listWorkspaceUsers(params: NotionListUsersParams): Promise<NotionListUsersResult>
}

export const notionTools: NotionGeneratedTools = {
    getDatasourceSchema: (params: NotionGetSchemaParams) =>
        TerseAgent.executeTool<NotionGetSchemaResult>("notion_get_schema", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
    queryDatabase: (params: NotionQueryDatabaseParams) =>
        TerseAgent.executeTool<NotionQueryDatabaseResult>("notion_query_database", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
    createOrUpdateDatabaseRow: (params: NotionCreateOrUpdateDatabaseRowParams) =>
        TerseAgent.executeTool<NotionCreateOrUpdateDatabaseRowResult>("notion_create_or_update_database_row", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
    createOrUpdatePageStandalone: (params: NotionCreateOrUpdatePageParams) =>
        TerseAgent.executeTool<NotionCreateOrUpdatePageResult>("notion_create_or_update_page", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
    queryPage: (params: NotionQueryPageParams) =>
        TerseAgent.executeTool<NotionQueryPageResult>("notion_query_page", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
    modifyBlocks: (params: NotionModifyBlocksParams) =>
        TerseAgent.executeTool<NotionModifyBlocksResult>("notion_modify_blocks", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
    listWorkspaceUsers: (params: NotionListUsersParams) =>
        TerseAgent.executeTool<NotionListUsersResult>("notion_list_users", { ...(params), integrationId: "cmhiiqxz3001yq52jb9qbkz2p" }),
}

// ── Notion skill ──────────────────────────────────────────────

/** Notion — read and write to the given databases or pages */
export function notionSkill(opts?: { databases?: NotionDatabase[]; pages?: NotionPage[] }): TypedSkill<"notion_create_or_update_database_row" | "notion_create_or_update_page" | "notion_modify_blocks"> {
    return new NotionConfig("cmhiiqxz3001yq52jb9qbkz2p",
        opts?.databases?.map(d => d.databaseId), opts?.databases?.map(d => d.title),
        opts?.pages?.map(p => p.pageId), opts?.pages?.map(p => p.title))
}