// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { PosthogConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── PostHog resources ─────────────────────────────────────────

export class PosthogProject {
    constructor(public readonly projectId: string, public readonly name: string) {}

    static DefaultProject = new PosthogProject("220160", "Default project")
    static Terse = new PosthogProject("250907", "Terse")
    static TestBuggyApp = new PosthogProject("281984", "TestBuggyApp")
}

/**
 * Custom event names observed in your PostHog project over the last 180 days.
 * Built-in $-prefixed events (e.g. "$pageview") are always accepted alongside these.
 * Terse supports US PostHog Cloud (us.posthog.com) only; EU-hosted PostHog is not supported.
 */
export type PosthogEventName =
    | "action_taken"
    | "job_triggered"
    | "job_completed"
    | "agent_triggered"
    | "integration_added"
    | "agent_created"
    | "job_failed"
    | "project_created"
    | "project_deleted"
    | "project_deployed"
    | "job_suspended"
    | "job_resumed"
    | "cli_logged_in"
    | "job_created"
    | "user_signed_out"
    | "project_deploy_failed"
    | "job_disabled"
    | "user_integrated_github"
    | "integration_removed"
    | "job_auto_paused"
    | "user_signed_in"
    | "organization_created"
    | "job_enabled"

// ── PostHog tools ─────────────────────────────────────────────

/**
 * Query PostHog logs with flexible filtering. Returns logs data and a link to view logs in PostHog. You can filter by user email, log severity levels (error, warn, info, debug), message text search, or combinations. At least one filter (user email, severity levels, or message search) should be provided to avoid overly broad queries. Use this when you need to investigate user activity, errors, or events in PostHog logs.
 */
export interface SearchPosthogLogsParams {
    /**
     * The PostHog project ID.
     */
    projectId: string
    /**
     * Optional: User email to filter logs by (e.g., "user@example.com").
     */
    userEmail?: string | null
    /**
     * Optional: Array of log severity levels to filter by (e.g., ["error", "warn"]). If not provided, all severity levels are included.
     */
    severityLevels: ("error" | "warn" | "info" | "debug")[] | null
    /**
     * Optional: Text to search for within log messages. Searches are case-insensitive and match partial text.
     */
    messageSearch?: string | null
    /**
     * Maximum number of log entries to return (default: 50, max: 250)
     */
    limit?: number
    /**
     * Offset for pagination (default: 0). Use with limit to page through results. For example, offset=0 gets logs 1-50, offset=50 gets logs 51-100, etc.
     */
    offset?: number
    /**
     * If true and dateFrom is not provided, filters logs from the last 7 days only (default: false). If false, no date restriction is applied unless dateFrom is explicitly provided.
     */
    last7Days?: boolean
    /**
     * Start date for filtering (ISO format or relative like "-7d"). If not provided and last7Days is true, defaults to 7 days ago. If not provided and last7Days is false, no date restriction is applied.
     */
    dateFrom: string | null
    /**
     * End date for filtering (ISO format or relative like "now"). If not provided, defaults to now.
     */
    dateTo?: string | null
}

export interface SearchPosthogLogsResult {
    success: true
    actions?: RunHistoryAction[]
    userEmail: string | null
    severityLevels: ("error" | "warn" | "info" | "debug")[] | null
    messageSearch: string | null
    projectId: string
    totalLogs: number
    logs: {
        id: string
        timestamp?: string
        level: string
        message: string
        service: string
        attributes: {
            [k: string]: unknown
        }
    }[]
    logsLink: string
    pagination: {
        limit: number
        offset: number
        hasMore: boolean
        nextOffset: number | null
        showing: string
    }
    message: string
}

/**
 * Query PostHog session recordings for a specific user by their email address. Returns session recordings data and links to view sessions in PostHog. Use this when you need to replay user sessions, investigate user behavior, or understand how users interact with the application. Returns the most recent session recordings first.
 */
export interface SearchPosthogSessionsParams {
    /**
     * The PostHog project ID.
     */
    projectId: string
    /**
     * The email address of the user to query session recordings for. Must be a valid email address.
     */
    userEmail: string
    /**
     * Maximum number of session recordings to return (default: 10, max: 100)
     */
    limit?: number
    /**
     * Offset for pagination (default: 0)
     */
    offset?: number
    /**
     * If true and dateFrom is not provided, filters session recordings from the last 7 days only (default: false). If false, no date restriction is applied unless dateFrom is explicitly provided.
     */
    last7Days?: boolean
    /**
     * Start date for filtering (ISO format or relative like "-7d"). If not provided and last7Days is true, defaults to 7 days ago. If not provided and last7Days is false, no date restriction is applied.
     */
    dateFrom: string | null
    /**
     * End date for filtering (ISO format or relative like "now"). If not provided, defaults to now.
     */
    dateTo?: string | null
}

export type SearchPosthogSessionsResult =
    | {
          success: true
          actions?: RunHistoryAction[]
          userEmail: string
          projectId: string
          personFound: true
          personId: string
          distinctId: string
          totalSessions: number
          sessions: {
              id: string
              startTime?: string
              endTime?: string
              duration?: number
              eventsCount: number
              sessionUrl: string
              personId: string
              distinctId: string
          }[]
          sessionsLink: string
          pagination: {
              limit: number
              offset: number
              hasNext: boolean
              hasPrevious: boolean
              nextOffset: number | null
              previousOffset: number | null
          }
          message: string
      }
    | {
          success: true
          actions?: RunHistoryAction[]
          userEmail: string
          projectId: string
          personFound: false
          /**
           * @minItems 0
           * @maxItems 0
           */
          sessions: []
          totalSessions: 0
          message: string
      }

/**
 * Fetch and decode session replay events from PostHog. Returns summarized meaningful events (clicks, inputs, scroll, console logs, network errors, navigation) within a specified time window. Use this to investigate what a user did during a session - what they clicked, what they typed, any errors that occurred, etc. The events are decoded and summarized for easy analysis.
 */
export interface GetPosthogSessionEventsParams {
    /**
     * The PostHog project ID.
     */
    projectId: string
    /**
     * The PostHog session ID (UUID format) to fetch events for. You can get this from searchPosthogSessions.
     */
    sessionId: string
    /**
     * Optional: Start time in seconds from the beginning of the session. If not provided, starts from the beginning.
     */
    startSeconds?: number | null
    /**
     * Optional: End time in seconds from the beginning of the session. If not provided, goes until the end.
     */
    endSeconds?: number | null
}

export interface GetPosthogSessionEventsResult {
    success: true
    actions?: RunHistoryAction[]
    sessionId: string
    sessionUrl: string
    startTime: string
    duration?: number
    timeWindow: {
        startSeconds: number
        endSeconds: number | null
    }
    summary: {
        totalRawEvents: number
        meaningfulEventsReturned: number
        consoleLogsReturned: number
    }
    events: {
        type:
            | "click"
            | "input"
            | "scroll"
            | "console"
            | "network_error"
            | "navigation"
            | "custom"
            | "page_load"
            | "viewport_resize"
        timestamp: number
        relativeTime: number
        data: {
            [k: string]: unknown
        }
    }[]
    consoleLogs: {
        timestamp: string
        level: string
        message: string
    }[]
    message: string
}

/**
 * List PostHog event names with how often each occurred, most frequent first (US PostHog Cloud only). Scope with distinctId to profile a single user's activity, or with event/person propertyFilters and a date range.
 */
export interface ListPosthogEventNamesParams {
    /**
     * The PostHog project ID.
     */
    projectId: string
    /**
     * If true (default), exclude PostHog built-in events (names starting with $, e.g. $pageview) and list only the project's custom-tracked events.
     */
    customEventsOnly?: boolean
    /**
     * Optional: only include events sent by this user, matched against the event's distinct ID (the ID your app passes to posthog.identify(), often your internal user ID).
     */
    distinctId?: string | null
    /**
     * Optional: property filters. To filter by a user's email use {key: "email", value: "user@example.com", type: "person"}.
     */
    propertyFilters?:
        | {
              /**
               * Property key to filter on (e.g. "$current_url", "plan", "email").
               */
              key: string
              /**
               * Property value to match
               */
              value: string | number | boolean
              /**
               * Comparison operator (default: "exact")
               */
              operator?: "exact" | "is_not" | "icontains" | "not_icontains" | "gt" | "lt" | "gte" | "lte"
              /**
               * "event" (default) matches a property on the event itself; "person" matches a property on the person who sent it (e.g. {key: "email", value: "user@example.com", type: "person"}).
               */
              type?: "event" | "person"
          }[]
        | null
    /**
     * Optional: start of the time range. UTC "YYYY-MM-DD HH:mm:ss" or "YYYY-MM-DD", or relative like "-30m", "-24h", "-7d", "-2w". If omitted, no lower bound.
     */
    dateFrom?: string | null
    /**
     * Optional: end of the time range, same formats as dateFrom. Defaults to now.
     */
    dateTo?: string | null
}

export interface ListPosthogEventNamesResult {
    success: true
    actions?: RunHistoryAction[]
    eventCounts: {
        eventName: string
        count: number
    }[]
    totalEventTypes: number
    eventsLink: string
}

/**
 * Fetch PostHog analytics events, newest first (US PostHog Cloud only). Filter by eventName, distinctId, and event/person propertyFilters. Use listPosthogEventNames first to discover which event names exist.
 */
export interface SearchPosthogEventsParams {
    /**
     * The PostHog project ID.
     */
    projectId: string
    /**
     * Optional: specific event name to filter by (e.g., "$pageview", "button_clicked"). Use listPosthogEventNames to discover available names.
     */
    eventName?: PosthogEventName | `$${string}` | null
    /**
     * If true (default), exclude PostHog built-in events (names starting with $). Ignored when eventName is provided.
     */
    customEventsOnly?: boolean
    /**
     * Optional: only include events sent by this user, matched against the event's distinct ID (the ID your app passes to posthog.identify(), often your internal user ID).
     */
    distinctId?: string | null
    /**
     * Optional: property filters. To filter by a user's email use {key: "email", value: "user@example.com", type: "person"}.
     */
    propertyFilters?:
        | {
              /**
               * Property key to filter on (e.g. "$current_url", "plan", "email").
               */
              key: string
              /**
               * Property value to match
               */
              value: string | number | boolean
              /**
               * Comparison operator (default: "exact")
               */
              operator?: "exact" | "is_not" | "icontains" | "not_icontains" | "gt" | "lt" | "gte" | "lte"
              /**
               * "event" (default) matches a property on the event itself; "person" matches a property on the person who sent it (e.g. {key: "email", value: "user@example.com", type: "person"}).
               */
              type?: "event" | "person"
          }[]
        | null
    /**
     * Maximum number of events to return (default: 50, max: 100).
     */
    limit?: number
    /**
     * Pagination cursor: pass nextCursor from the previous response to fetch the next (older) page.
     */
    cursor?: string | null
    /**
     * Optional: start of the time range. UTC "YYYY-MM-DD HH:mm:ss" or "YYYY-MM-DD", or relative like "-30m", "-24h", "-7d", "-2w". If omitted, no lower bound.
     */
    dateFrom?: string | null
    /**
     * Optional: end of the time range, same formats as dateFrom. Defaults to now.
     */
    dateTo?: string | null
}

export interface SearchPosthogEventsResult {
    success: true
    actions?: RunHistoryAction[]
    events: {
        id: string
        event: string
        timestamp?: string
        distinctId?: string
        url?: string
    }[]
    totalEvents: number
    hasMore: boolean
    nextCursor: string | null
    eventsLink: string
}

export type PosthogGeneratedTools = {
    /** Query PostHog logs with flexible filtering. Returns logs data and a link to view logs in PostHog. You can filter by user email, log severity levels (error, warn, info, debug), message text search, or combinations. At least one filter (user email, severity levels, or message search) should be provided to avoid overly broad queries. Use this when you need to investigate user activity, errors, or events in PostHog logs. */
    searchLogs(params: SearchPosthogLogsParams): Promise<SearchPosthogLogsResult>
    /** Query PostHog session recordings for a specific user by their email address. Returns session recordings data and links to view sessions in PostHog. Use this when you need to replay user sessions, investigate user behavior, or understand how users interact with the application. Returns the most recent session recordings first. */
    searchSessions(params: SearchPosthogSessionsParams): Promise<SearchPosthogSessionsResult>
    /** Fetch and decode session replay events from PostHog. Returns summarized meaningful events (clicks, inputs, scroll, console logs, network errors, navigation) within a specified time window. Use this to investigate what a user did during a session - what they clicked, what they typed, any errors that occurred, etc. The events are decoded and summarized for easy analysis. */
    getSessionEvents(params: GetPosthogSessionEventsParams): Promise<GetPosthogSessionEventsResult>
    /** List PostHog event names with how often each occurred, most frequent first (US PostHog Cloud only). Scope with distinctId to profile a single user's activity, or with event/person propertyFilters and a date range. */
    listEventNames(params: ListPosthogEventNamesParams): Promise<ListPosthogEventNamesResult>
    /** Fetch PostHog analytics events, newest first (US PostHog Cloud only). Filter by eventName, distinctId, and event/person propertyFilters. Use listPosthogEventNames first to discover which event names exist. */
    searchEvents(params: SearchPosthogEventsParams): Promise<SearchPosthogEventsResult>
}

export const posthogTools: PosthogGeneratedTools = {
    searchLogs: (params: SearchPosthogLogsParams) =>
        TerseAgent.executeTool<SearchPosthogLogsResult>("searchPosthogLogs", { ...(params), integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
    searchSessions: (params: SearchPosthogSessionsParams) =>
        TerseAgent.executeTool<SearchPosthogSessionsResult>("searchPosthogSessions", { ...(params), integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
    getSessionEvents: (params: GetPosthogSessionEventsParams) =>
        TerseAgent.executeTool<GetPosthogSessionEventsResult>("getPosthogSessionEvents", { ...(params), integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
    listEventNames: (params: ListPosthogEventNamesParams) =>
        TerseAgent.executeTool<ListPosthogEventNamesResult>("listPosthogEventNames", { ...(params), integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
    searchEvents: (params: SearchPosthogEventsParams) =>
        TerseAgent.executeTool<SearchPosthogEventsResult>("searchPosthogEvents", { ...(params), integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
}

// ── PostHog skill ─────────────────────────────────────────────

/** PostHog — query analytics for a specific project */
export function posthogSkill(opts: { project: PosthogProject }): TypedSkill<never> {
    return new PosthogConfig("cmr9jgvgn0001y5uz1kcdoic0", opts.project.projectId, opts.project.name)
}