// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { ResendOutputConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Resend templates ──────────────────────────────────────────

export type ResendTemplateVariableValue = string | number

export interface GeneratedResendTemplate {
    readonly templateId: string
    readonly alias: string | null
    readonly name: string
    readonly variables: readonly { key: string; type: "string" | "number"; required: boolean; fallbackValue: ResendTemplateVariableValue | null }[]
}

export const ResendTemplates = {
    TerseFeedbackBasic: {
        templateId: "b5ef1f8b-a24a-4b1f-92fb-6872ba9de7af",
        alias: "terse-feedback-basic",
        name: "terse-feedback-basic",
        variables: [{"key":"USER_NAME","type":"string","required":false,"fallbackValue":"there"}],
    },
    TerseNudge: {
        templateId: "e791a114-9098-43fe-a57d-712efbec47cc",
        alias: "terse-nudge",
        name: "terse-nudge",
        variables: [],
    },
    TerseFeedback: {
        templateId: "141a3f8c-0595-4458-8557-a405e053b032",
        alias: "terse-feedback",
        name: "terse-feedback",
        variables: [{"key":"USER_NAME","type":"string","required":false,"fallbackValue":"there"}, {"key":"CALL_OFFER_SECTION","type":"string","required":false,"fallbackValue":"<p style=\"font-size:16px;line-height:26px;color:#3d3730;text-align:left;margin:0 0 16px;margin-top:0;margin-right:0;margin-bottom:16px;margin-left:0\">If you&#x27;re up for it, we&#x27;d also love to hop on a short call to hear what you&#x27;re building. It genuinely helps us shape what we ship next.</p><a href=\"mailto:thomas@useterse.ai?subject=Terse%20feedback%20call\" style=\"line-height:100%;text-decoration:none;display:block;max-width:100%;mso-padding-alt:0px;background-color:#2e7d57;border-radius:8px;color:#ffffff;font-size:16px;font-weight:600;text-align:center;width:100%;padding:12px 0;margin:8px 0 0;box-sizing:border-box;padding-top:12px;padding-right:0;padding-bottom:12px;padding-left:0\" target=\"_blank\"><span><!--[if mso]><i style=\"mso-font-width:0%;mso-text-raise:18px\" hidden></i><![endif]--></span><span style=\"max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:9px\">Grab 15 minutes with the founders</span><span><!--[if mso]><i style=\"mso-font-width:0%\" hidden>&#8203;</i><![endif]--></span></a><p style=\"font-size:16px;line-height:26px;color:#3d3730;text-align:left;margin:24px 0 16px;margin-top:24px;margin-right:0;margin-bottom:16px;margin-left:0\">Prefer async? You can always find us in the<!-- --> <a href=\"https://join.slack.com/t/tersecommunity/shared_invite/zt-3y01ap0bn-VvOqz~iJW0LbJ0cTqWuAIQ\" style=\"color:#a85b42;text-decoration-line:none;text-decoration:underline\" target=\"_blank\">Slack community</a>.</p>"}],
    },
    TerseWelcome: {
        templateId: "20e0482c-9354-4cc5-a953-ff4b1a38dbe3",
        alias: "terse-welcome",
        name: "terse-welcome",
        variables: [{"key":"USER_NAME","type":"string","required":false,"fallbackValue":"there"}],
    },
    TerseCreditsSent: {
        templateId: "f20be7b7-0c69-4a70-aea9-b81e6ea4a4b2",
        alias: "terse-credits-sent",
        name: "Terse Credits sent",
        variables: [{"key":"ORG_NAME","type":"string","required":false,"fallbackValue":"there"}, {"key":"CREDITS","type":"string","required":false,"fallbackValue":"10,000"}],
    },
} as const satisfies Record<string, GeneratedResendTemplate>

export type ResendTemplate = (typeof ResendTemplates)[keyof typeof ResendTemplates]

export interface ResendSendTemplateBaseParams {
    /**
     * Recipient email addresses
     *
     * @minItems 1
     * @maxItems 50
     */
    to: [string, ...string[]]
    /**
     * Optional sender override; omit when the template defines one
     */
    from?: string | null
    /**
     * Optional subject override; omit when the template defines one
     */
    subject?: string | null
    /**
     * Optional reply-to override
     */
    replyTo?: string | null
    /**
     * Optional CC recipients
     */
    cc?: string[] | null
    /**
     * Optional BCC recipients
     */
    bcc?: string[] | null
    /**
     * Optional idempotency key, retained by Resend for 24 hours
     */
    idempotencyKey?: string | null
}

/** Send a published Resend email template. `variables` is typed per template, keyed by `templateId`. */
export type ResendSendTemplateParams =
    | (ResendSendTemplateBaseParams & { templateId: typeof ResendTemplates.TerseFeedbackBasic.templateId; variables: { "USER_NAME"?: string } })
    | (ResendSendTemplateBaseParams & { templateId: typeof ResendTemplates.TerseNudge.templateId; variables: Record<string, never> })
    | (ResendSendTemplateBaseParams & { templateId: typeof ResendTemplates.TerseFeedback.templateId; variables: { "USER_NAME"?: string; "CALL_OFFER_SECTION"?: string } })
    | (ResendSendTemplateBaseParams & { templateId: typeof ResendTemplates.TerseWelcome.templateId; variables: { "USER_NAME"?: string } })
    | (ResendSendTemplateBaseParams & { templateId: typeof ResendTemplates.TerseCreditsSent.templateId; variables: { "ORG_NAME"?: string; "CREDITS"?: string } })

// ── Resend tools ──────────────────────────────────────────────

export interface ResendSendTemplateResult {
    success: boolean
    actions?: RunHistoryAction[]
    emailId: string
    templateId: string
    to: string[]
    summary: string
}

export type ResendGeneratedTools = {
    /** Send a published Resend email template. Supply every required template variable without a fallback value. */
    sendTemplate(params: ResendSendTemplateParams): Promise<ResendSendTemplateResult>
}

export const resendTools: ResendGeneratedTools = {
    sendTemplate: (params: ResendSendTemplateParams) =>
        TerseAgent.executeTool<ResendSendTemplateResult>("resend_send_template", { ...(params), integrationId: "cmrjspd6m0001y5fnew1q4he6" }),
}

// ── Resend skill ──────────────────────────────────────────────

/** Resend — send transactional email using generated published templates */
export function resendSkill(): TypedSkill<"resend_send_template"> {
    return new ResendOutputConfig("cmrjspd6m0001y5fnew1q4he6")
}