// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { SlackOutputConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Slack resources ───────────────────────────────────────────

export class SlackChannel {
    constructor(public readonly channelId: string, public readonly name: string) {}

    static AllTerseInc = new SlackChannel("C09DEL0AUE5", "all-terse-inc")
    static MpdmOlivierTerse2Terse3Thomas1 = new SlackChannel("C0A2DV3N4GL", "mpdm-olivier--terse2--terse3--thomas-1")
}

export class SlackUser {
    constructor(public readonly userId: string, public readonly name: string) {}

    static Slackbot = new SlackUser("USLACKBOT", "slackbot")
    static Thomas = new SlackUser("U09DEL0634Z", "thomas")
    static Olivier = new SlackUser("U09FXB1UPDM", "olivier")
}

// ── Slack tools ───────────────────────────────────────────────

/**
 * Send message to a Slack channel or DM. Provide channelId (C…/G…/D…) or slackUserId (U…) to open or reuse a 1:1 DM. Supports plain text (mrkdwn) or Block Kit (JSON blocks). If both are set, channelId is used.
 */
export interface SlackSendMessageParams {
    /**
     * Slack channel ID (C…/G…) or existing DM channel ID (D…). Omit when sending via slackUserId (opens DM if needed).
     */
    channelId?: string | null
    /**
     * Slack member ID (U…) to send a direct message. The workspace opens the DM conversation if one does not exist yet. Omit when sending to channelId.
     */
    slackUserId?: string | null
    /**
     * Message content (mrkdwn). Used as fallback for Block Kit or main message.
     */
    message: string
    /**
     * Thread timestamp to reply to existing thread. If sending a message to a thread, this should be the timestamp of the thread to reply to. If sending an unthreaded message, this should be set to null.
     */
    thread_ts?: string | null
    /**
     * Block Kit JSON array string for interactive messages with buttons, structured layouts
     */
    blocks?: string | null
}

export interface SlackSendMessageResult {
    success: boolean
    actions?: RunHistoryAction[]
    message_ts?: string
    channel: string
    thread_ts?: string
    summary: string
    has_blocks: boolean
}

/**
 * List Slack workspace users (id, name, email). Use this to resolve user IDs to names when needed.
 * Returns non-bot members. Optionally filter by name or email with the query parameter.
 */
export interface SlackListUsersParams {
    /**
     * Optional search query to filter users by name or email. Case-insensitive partial match.
     */
    query?: string | null
}

export interface SlackListUsersResult {
    success: boolean
    actions?: RunHistoryAction[]
    users: {
        id: string
        name: string
        email?: string
    }[]
    count: number
}

/**
 * List available Slack channels and conversations (public, private, DMs, multi-person DMs) that the integration can access.
 * Use this to discover channel IDs before reading conversation history.
 * Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more.
 */
export interface SlackListChannelsParams {
    /**
     * Filter by type: public (public channels), private (private channels), im (DMs), mpim (group DMs), or all. Defaults to all.
     */
    types?: ("public" | "private" | "im" | "mpim" | "all") | null
    /**
     * Maximum number of conversations to return.
     */
    limit?: number | null
    /**
     * Pagination cursor from a previous response (nextCursor). Omit on first call.
     */
    cursor?: string | null
}

export interface SlackListChannelsResult {
    success: boolean
    actions?: RunHistoryAction[]
    channels: {
        id?: string
        name: string
        isPrivate: boolean
        isIm: boolean
        isMpim: boolean
        userId?: string
    }[]
    count: number
    nextCursor: string | null
    hasMore: boolean
}

/**
 * Read message history from a Slack channel or DM.
 * Use the channel ID from slack_list_channels. Supports public channels, private channels, and DMs.
 * Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more messages.
 */
export interface SlackReadConversationParams {
    /**
     * The Slack channel ID to read (from slack_list_channels).
     */
    channelId: string
    /**
     * Maximum number of messages to return.
     */
    limit?: number | null
    /**
     * Pagination cursor from a previous response (nextCursor). Omit on first call.
     */
    cursor?: string | null
}

export interface SlackReadConversationResult {
    success: boolean
    actions?: RunHistoryAction[]
    channelId: string
    channelName?: string
    messages: {
        userId?: string
        userName?: string
        text: string
        timestamp?: string
        threadTs?: string
    }[]
    count: number
    hasMore: boolean
    nextCursor: string | null
}

export type SlackGeneratedTools = {
    /** Send message to a Slack channel or DM. Provide channelId (C…/G…/D…) or slackUserId (U…) to open or reuse a 1:1 DM. Supports plain text (mrkdwn) or Block Kit (JSON blocks). If both are set, channelId is used. */
    sendMessage(params: SlackSendMessageParams): Promise<SlackSendMessageResult>
    /** List Slack workspace users (id, name, email). Use this to resolve user IDs to names when needed.
Returns non-bot members. Optionally filter by name or email with the query parameter. */
    listUsers(params: SlackListUsersParams): Promise<SlackListUsersResult>
    /** List available Slack channels and conversations (public, private, DMs, multi-person DMs) that the integration can access.
Use this to discover channel IDs before reading conversation history.
Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more. */
    listChannels(params: SlackListChannelsParams): Promise<SlackListChannelsResult>
    /** Read message history from a Slack channel or DM.
Use the channel ID from slack_list_channels. Supports public channels, private channels, and DMs.
Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more messages. */
    readConversation(params: SlackReadConversationParams): Promise<SlackReadConversationResult>
}

export const slackTools: SlackGeneratedTools = {
    sendMessage: (params: SlackSendMessageParams) =>
        TerseAgent.executeTool<SlackSendMessageResult>("slack_send_message", { ...(params), integrationId: "cmr3r2xb80002y5em42x4nqae" }),
    listUsers: (params: SlackListUsersParams) =>
        TerseAgent.executeTool<SlackListUsersResult>("slack_list_users", { ...(params), integrationId: "cmr3r2xb80002y5em42x4nqae" }),
    listChannels: (params: SlackListChannelsParams) =>
        TerseAgent.executeTool<SlackListChannelsResult>("slack_list_channels", { ...(params), integrationId: "cmr3r2xb80002y5em42x4nqae" }),
    readConversation: (params: SlackReadConversationParams) =>
        TerseAgent.executeTool<SlackReadConversationResult>("slack_read_conversation", { ...(params), integrationId: "cmr3r2xb80002y5em42x4nqae" }),
}

// ── Slack skill ───────────────────────────────────────────────

/** Slack — send messages and manage threads in a specific channel */
export function slackSkill(opts: { channel: SlackChannel; userIds?: string[]; userNames?: string[]; listenToUserDms?: boolean }): TypedSkill<"slack_send_message"> {
    return new SlackOutputConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId ?? null, opts.channel.name ?? null, opts.userIds ?? [], opts.userNames ?? null, opts.listenToUserDms)
}