// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    SDKTrigger,
    SlackAttachments,
    SlackBlocks,
    SlackConfig,
    SlackEventType,
    SlackFiles,
    TypedTrigger,
} from "terse-sdk"
import { SlackChannel } from "./slack.tools.js"

// ── Slack triggers ────────────────────────────────────────────

export interface SlackMessageTriggerPayload {
    integrationType: "slack"
    eventType: "message"
    channelId: string
    channelName: string | null
    userId: string
    userName: string | null
    text: string
    timestamp: string
    threadTs?: string | null
    threadTimestamp: string | null
    teamId: string
    permalink: string | null
    channelType: ("channel" | "group" | "mpim" | "im") | null
    blocks: SlackBlocks | null
    attachments: SlackAttachments | null
    files: SlackFiles | null
}

export type SlackMessageTrigger = SDKTrigger<SlackMessageTriggerPayload>

export interface SlackAppMentionTriggerPayload {
    integrationType: "slack"
    eventType: "app_mention"
    channelId: string
    channelName: string | null
    userId: string
    userName: string | null
    text: string
    timestamp: string
    threadTs?: string | null
    threadTimestamp: string | null
    teamId: string
    permalink: string | null
    channelType: ("channel" | "group" | "mpim" | "im") | null
    blocks: SlackBlocks | null
    attachments: SlackAttachments | null
    files: SlackFiles | null
}

export type SlackAppMentionTrigger = SDKTrigger<SlackAppMentionTriggerPayload>

export interface SlackReactionAddedTriggerPayload {
    integrationType: "slack"
    eventType: "reaction_added"
    channelId: string
    channelName: string | null
    userId: string
    userName: string | null
    text: string
    timestamp: string
    threadTs?: string | null
    threadTimestamp: string | null
    teamId: string
    permalink: string | null
    channelType: ("channel" | "group" | "mpim" | "im") | null
    blocks: SlackBlocks | null
    attachments: SlackAttachments | null
    files: SlackFiles | null
    reaction: string
    itemType: string | null
    itemUserId: string | null
    itemChannelId: string | null
    itemTimestamp: string | null
}

export type SlackReactionAddedTrigger = SDKTrigger<SlackReactionAddedTriggerPayload>

export type SlackTrigger = SlackMessageTrigger | SlackAppMentionTrigger | SlackReactionAddedTrigger

export const slackTriggers = {
    /** Trigger on any message in a channel */
    onMessage(opts: { channel: SlackChannel; userIds?: string[] }): TypedTrigger<SlackMessageTrigger> {
        return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId, opts.channel.name, false, opts.userIds ?? [], [SlackEventType.MESSAGE])
    },
    /** Trigger on direct messages to the bot */
    onDm(opts?: { userIds?: string[] }): TypedTrigger<SlackMessageTrigger> {
        return new SlackConfig("cmr3r2xb80002y5em42x4nqae", undefined, undefined, true, opts?.userIds ?? [], [SlackEventType.MESSAGE])
    },
    /** Trigger when the Slack app is directly mentioned */
    onAppMention(opts: { channel: SlackChannel; userIds?: string[] }): TypedTrigger<SlackAppMentionTrigger> {
        return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId, opts.channel.name, false, opts.userIds ?? [], [SlackEventType.APP_MENTION])
    },
    /** Trigger when a reaction is added to a message in a channel */
    onReactionAdded(opts: { channel: SlackChannel; userIds?: string[] }): TypedTrigger<SlackReactionAddedTrigger> {
        return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId, opts.channel.name, false, opts.userIds ?? [], [SlackEventType.REACTION_ADDED])
    },
    /** Trigger on all Slack events (messages + DMs) for a channel */
    trigger(opts?: { channel?: SlackChannel; listenToUserDms?: boolean; userIds?: string[]; eventTypes?: SlackEventType[] }): TypedTrigger<SlackTrigger> {
        return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts?.channel?.channelId, opts?.channel?.name, opts?.listenToUserDms, opts?.userIds ?? [], opts?.eventTypes)
    },
}