// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { SnowflakeOutputConfig, TerseAgent, TypedSkill } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Snowflake tools ───────────────────────────────────────────

/**
 * Get the query execution plan for a Snowflake SQL query using EXPLAIN. Use this to understand how Snowflake will execute a query before running it.
 */
export interface SnowflakeExplainQueryParams {
    /**
     * The SQL query to explain.
     */
    query: string
}

export interface SnowflakeExplainQueryResult {
    success: boolean
    actions?: RunHistoryAction[]
    explainPlan: {
        [k: string]: unknown
    }[]
    columns: string[]
    rowCount: number
}

/**
 * Execute a read-only SQL query against a Snowflake data warehouse. Returns rows and column metadata. SQL safety is enforced by the Snowflake role configured for the integration — use a read-only role.
 */
export interface SnowflakeExecuteQueryParams {
    /**
     * The SQL query to execute. Should be a read-only SELECT statement.
     */
    query: string
}

export interface SnowflakeExecuteQueryResult {
    success: boolean
    actions?: RunHistoryAction[]
    rows: {
        [k: string]: unknown
    }[]
    columns: string[]
    rowCount: number
}

export type SnowflakeGeneratedTools = {
    /** Get the query execution plan for a Snowflake SQL query using EXPLAIN. Use this to understand how Snowflake will execute a query before running it. */
    explainQuery(params: SnowflakeExplainQueryParams): Promise<SnowflakeExplainQueryResult>
    /** Execute a read-only SQL query against a Snowflake data warehouse. Returns rows and column metadata. SQL safety is enforced by the Snowflake role configured for the integration — use a read-only role. */
    executeQuery(params: SnowflakeExecuteQueryParams): Promise<SnowflakeExecuteQueryResult>
}

export const snowflakeTools: SnowflakeGeneratedTools = {
    explainQuery: (params: SnowflakeExplainQueryParams) =>
        TerseAgent.executeTool<SnowflakeExplainQueryResult>("snowflakeExplainQuery", { ...(params), integrationId: "cmn541p7k007fnp2ixtam61yw" }),
    executeQuery: (params: SnowflakeExecuteQueryParams) =>
        TerseAgent.executeTool<SnowflakeExecuteQueryResult>("snowflakeExecuteQuery", { ...(params), integrationId: "cmn541p7k007fnp2ixtam61yw" }),
}

// ── Snowflake skill ───────────────────────────────────────────

/** Snowflake — run SQL queries against your warehouse */
export function snowflakeSkill(): TypedSkill<"snowflakeExecuteQuery"> {
    return new SnowflakeOutputConfig("cmn541p7k007fnp2ixtam61yw")
}