// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    FrequencyUnit,
    InferStructuredOutput,
    SDKTrigger,
    TimeTriggerConfig,
    Timezone,
    TypedTrigger,
    WebMonitorConfig,
    WebhookInputConfig,
} from "terse-sdk"

// ── Built-in triggers ─────────────────────────────────────────

export interface CronTriggerPayload {
    integrationType: "cron_job"
    eventType: "cron"
    inputId: string
    isManualTrigger?: boolean
    manualContext?: string
}

export type CronTrigger = SDKTrigger<CronTriggerPayload>

export interface WebhookTriggerPayload<TBody = unknown> {
    integrationType: "webhook"
    eventType: "webhook"
    body: TBody
    headers: {
        [k: string]: string
    }
    method: string
}

export type WebhookTrigger<TBody = unknown> = SDKTrigger<WebhookTriggerPayload<TBody>>

export interface WebMonitorTriggerPayload<TStructured = unknown> {
    integrationType: "webmonitor"
    eventType: "webmonitor"
    inputId: string
    query: string
    frequency: {
        number: number
        unit: "hour" | "day" | "week"
    }
    monitorId: string
    eventGroupId: string
    metadata: {
        [k: string]: string
    }
    outputType: "text" | "json"
    rawPayload?: string
    payload: TStructured
    eventDate: string
    sourceUrls: string[]
}

export type WebMonitorTrigger<TStructured = unknown> = SDKTrigger<WebMonitorTriggerPayload<TStructured>>

export const scheduleTriggers = {
    /** Run on a cron schedule (5-field cron expression, evaluated as wall-clock time in `timezone` — an IANA name like "America/New_York", DST-aware — defaulting to UTC) */
    cron(opts: { expression: string; timezone?: Timezone }): TypedTrigger<CronTrigger> {
        return new TimeTriggerConfig(opts.expression, opts.timezone)
    },
}

export const webhookTriggers = {
    /** Trigger via an external HTTP request to a generated URL */
    onRequest<TBody = unknown>(): TypedTrigger<WebhookTrigger<TBody>> {
        return new WebhookInputConfig()
    },
}

/** Bind a web-monitor event to a Zod schema: the `payload` field types as the schema's output */
export type WebMonitorTriggerFor<TSchema> = WebMonitorTrigger<InferStructuredOutput<TSchema>>

export const webMonitorTriggers = {
    /** Trigger when a query against the live web matches the given schema */
    onEvent<const TSchema>(opts: {
        query: string
        frequency: { number: number; unit: FrequencyUnit }
        outputSchema?: TSchema
    }): TypedTrigger<WebMonitorTrigger<InferStructuredOutput<TSchema>>> {
        return new WebMonitorConfig(opts.query, opts.frequency, opts.outputSchema)
    },
}