// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    ImageEditConfig,
    MemoryConfig,
    TerseAgent,
    TypedSkill,
    WebConfig,
} from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── Terse built-in tools ──────────────────────────────────────

/**
 * Persistent memory stored under /memories that survives across runs. Commands: view (read a file or list a directory), create, str_replace, insert, delete, rename. Always view /memories before starting a task, and record durable progress and learnings as you work.
 */
export interface MemoryParams {
    /**
     * The memory operation to perform and its arguments
     */
    command:
        | {
              op: "view"
              /**
               * Path under /memories to view; omit to list the memory root
               */
              path?: string | null
              /**
               * Optional [startLine, endLine] (1-indexed) to view a slice of a file
               */
              view_range?: number[] | null
          }
        | {
              op: "create"
              /**
               * Path under /memories to create (e.g. '/memories/notes.md')
               */
              path: string
              /**
               * Full file contents; defaults to empty
               */
              file_text?: string | null
          }
        | {
              op: "str_replace"
              /**
               * Path under /memories to edit
               */
              path: string
              /**
               * Exact text to replace (must appear verbatim exactly once)
               */
              old_str: string
              /**
               * Replacement text; omit to delete the matched text
               */
              new_str?: string | null
          }
        | {
              op: "insert"
              /**
               * Path under /memories to edit
               */
              path: string
              /**
               * Line number after which to insert (0 = beginning of file)
               */
              insert_line: number
              /**
               * Text to insert; defaults to empty
               */
              insert_text?: string | null
          }
        | {
              op: "delete"
              /**
               * Path under /memories to delete
               */
              path: string
          }
        | {
              op: "rename"
              /**
               * Source path under /memories
               */
              old_path: string
              /**
               * Destination path under /memories
               */
              new_path: string
          }
}

export interface MemoryResult {
    success: boolean
    actions?: RunHistoryAction[]
    result: string
}

/**
 * Search the web for up-to-date information. Returns ranked results with titles, URLs, and content snippets. Use for questions about current events, facts, or topics requiring web sources.
 */
export interface WebSearchParams {
    /**
     * The search query
     */
    query: string
    /**
     * Number of results to return (default 5)
     */
    max_results: number | null
    /**
     * 'basic' is faster, 'advanced' is more thorough (default 'basic')
     */
    search_depth: ("basic" | "advanced") | null
    /**
     * Include an LLM-generated answer summarizing the results (default false)
     */
    include_answer: boolean | null
    /**
     * 'news' for recent news articles, 'general' for all web content (default 'general')
     */
    topic: ("general" | "news") | null
    /**
     * Filter results by recency
     */
    time_range: ("day" | "week" | "month" | "year") | null
    /**
     * Restrict results to these domains (e.g. ['example.com']). Required when web access is limited to an allowed list of domains.
     */
    include_domains: string[] | null
}

export interface WebSearchResult {
    query: string
    answer?: string
    results: {
        title: string
        url: string
        content: string
        score: number
    }[]
}

/**
 * Extract the full text content from one or more web page URLs. Use this when you need to read the complete contents of a specific page.
 */
export interface WebExtractParams {
    /**
     * URL or list of URLs to extract content from
     */
    urls: string | string[]
    /**
     * 'advanced' handles JavaScript-heavy pages but is slower
     */
    extract_depth: ("basic" | "advanced") | null
}

export interface WebExtractResult {
    results: {
        url: string
        raw_content: string
    }[]
    failed_results: unknown
}

/**
 * Conduct deep, multi-source research on a topic. Autonomously searches across many sources and returns a comprehensive report with citations. Best for complex questions requiring synthesis across multiple sources. Takes longer than a regular search (up to 2 minutes).
 */
export interface WebResearchParams {
    /**
     * The research question or topic to investigate
     */
    input: string
    /**
     * 'mini' for quick focused research, 'pro' for comprehensive multi-angle research, 'auto' picks automatically
     */
    model: ("mini" | "pro" | "auto") | null
}

export interface WebResearchResult {
    success: boolean
    actions?: RunHistoryAction[]
    status: "completed"
    request_id: string
    content?: string
    sources?: {
        title: string
        url: string
    }[]
}

/**
 * Edit or transform an image from a URL using a natural language prompt. Supports crops, style changes, object removal/addition, color adjustments, and other visual edits. The edited image is automatically sent to the chat UI for the user to see.
 */
export interface ImageEditParams {
    /**
     * URL of the image to edit. Must be a signed URL from our internal GCS image bucket.
     */
    image_url: string
    /**
     * Natural language instruction describing how to edit the image.
     */
    prompt: string
}

export interface ImageEditResult {
    success: boolean
    actions?: RunHistoryAction[]
    url: string
    image_url: string
    summary: string
    snippets: {
        type: "image"
        url: string
    }[]
}

export type TerseGeneratedTools = {
    /** Persistent memory stored under /memories that survives across runs. Commands: view (read a file or list a directory), create, str_replace, insert, delete, rename. Always view /memories before starting a task, and record durable progress and learnings as you work. */
    memory(params: MemoryParams): Promise<MemoryResult>
    /** Search the web for up-to-date information. Returns ranked results with titles, URLs, and content snippets. Use for questions about current events, facts, or topics requiring web sources. */
    webSearch(params: WebSearchParams): Promise<WebSearchResult>
    /** Extract the full text content from one or more web page URLs. Use this when you need to read the complete contents of a specific page. */
    extractPage(params: WebExtractParams): Promise<WebExtractResult>
    /** Conduct deep, multi-source research on a topic. Autonomously searches across many sources and returns a comprehensive report with citations. Best for complex questions requiring synthesis across multiple sources. Takes longer than a regular search (up to 2 minutes). */
    research(params: WebResearchParams): Promise<WebResearchResult>
    /** Edit or transform an image from a URL using a natural language prompt. Supports crops, style changes, object removal/addition, color adjustments, and other visual edits. The edited image is automatically sent to the chat UI for the user to see. */
    editImage(params: ImageEditParams): Promise<ImageEditResult>
}

export const terseTools: TerseGeneratedTools = {
    memory: (params: MemoryParams) =>
        TerseAgent.executeTool<MemoryResult>("memory", { ...(params) }),
    webSearch: (params: WebSearchParams) =>
        TerseAgent.executeTool<WebSearchResult>("web_search", { ...(params) }),
    extractPage: (params: WebExtractParams) =>
        TerseAgent.executeTool<WebExtractResult>("web_extract", { ...(params) }),
    research: (params: WebResearchParams) =>
        TerseAgent.executeTool<WebResearchResult>("web_research", { ...(params) }),
    editImage: (params: ImageEditParams) =>
        TerseAgent.executeTool<ImageEditResult>("image_edit", { ...(params) }),
}

// ── Built-in skills ───────────────────────────────────────────

/** Web — built-in web search, page extraction, and multi-source research. Pass `allowedDomains` to restrict search and page extraction to specific sites (and their subdomains). */
export function webSkill(opts: { allowedDomains?: string[] } = {}): TypedSkill<"web_search" | "web_extract" | "web_research"> {
    return new WebConfig(opts)
}

/** ImageEdit — edit and generate images */
export function imageEditSkill(): TypedSkill<"image_edit"> {
    return new ImageEditConfig()
}

/** Memory — built-in persistent memory the agent reads and writes under /memories, scoped to this job and surviving across runs. */
export function memorySkill(): TypedSkill<"memory"> {
    return new MemoryConfig()
}