// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import { TerseAgent, TypedSkill, WorkOSOutputConfig } from "terse-sdk"
import type { RunHistoryAction } from "./common.js"

// ── WorkOS tools ──────────────────────────────────────────────

/**
 * List users from the customer's WorkOS account. Supports filtering by email and organization ID. Returns user profiles including email, name, and creation date. Use pagination (after cursor) for large user sets.
 */
export interface ListWorkOSUsersParams {
    /**
     * Optional exact email address filter. Omit or pass null to list all users.
     */
    email?: string | null
    /**
     * Optional WorkOS organization ID filter. Omit or pass null for all organizations.
     */
    organizationId?: string | null
    /**
     * Maximum number of users to return (default: 20, max: 100).
     */
    limit?: number
    /**
     * Optional pagination cursor. Use the 'after' value from a previous response to get the next page.
     */
    after?: string | null
}

export interface ListWorkOSUsersResult {
    success: boolean
    actions?: RunHistoryAction[]
    users: {
        id: string
        email: string
        emailVerified: boolean
        firstName?: string | null
        lastName?: string | null
        profilePictureUrl?: string | null
        createdAt: string
        updatedAt: string
    }[]
    pagination: {
        hasMore: boolean
        after?: string | null
    }
    message: string
}

/**
 * List organizations from the customer's WorkOS account. Returns organization names, domains, external IDs, and timestamps. Use pagination (after cursor) for large organization sets.
 */
export interface ListWorkOSOrganizationsParams {
    /**
     * Maximum number of organizations to return (default: 20, max: 100).
     */
    limit?: number
    /**
     * Optional pagination cursor. Use the 'after' value from a previous response to get the next page.
     */
    after?: string | null
}

export interface ListWorkOSOrganizationsResult {
    success: boolean
    actions?: RunHistoryAction[]
    organizations: {
        id: string
        name: string
        externalId?: string | null
        domains: string[]
        createdAt: string
        updatedAt: string
    }[]
    pagination: {
        hasMore: boolean
        after?: string | null
    }
    message: string
}

/**
 * Get detailed information about a specific WorkOS user by their user ID. Returns profile data including email, name, verification status, and timestamps.
 */
export interface GetWorkOSUserParams {
    /**
     * The WorkOS user ID to look up.
     */
    userId: string
}

export interface GetWorkOSUserResult {
    success: boolean
    actions?: RunHistoryAction[]
    user: {
        id: string
        email: string
        emailVerified: boolean
        firstName?: string | null
        lastName?: string | null
        profilePictureUrl?: string | null
        createdAt: string
        updatedAt: string
    }
    message: string
}

export type WorkosGeneratedTools = {
    /** List users from the customer's WorkOS account. Supports filtering by email and organization ID. Returns user profiles including email, name, and creation date. Use pagination (after cursor) for large user sets. */
    listUsers(params: ListWorkOSUsersParams): Promise<ListWorkOSUsersResult>
    /** List organizations from the customer's WorkOS account. Returns organization names, domains, external IDs, and timestamps. Use pagination (after cursor) for large organization sets. */
    listOrganizations(params: ListWorkOSOrganizationsParams): Promise<ListWorkOSOrganizationsResult>
    /** Get detailed information about a specific WorkOS user by their user ID. Returns profile data including email, name, verification status, and timestamps. */
    getUser(params: GetWorkOSUserParams): Promise<GetWorkOSUserResult>
}

export const workosTools: WorkosGeneratedTools = {
    listUsers: (params: ListWorkOSUsersParams) =>
        TerseAgent.executeTool<ListWorkOSUsersResult>("listWorkOSUsers", { ...(params), integrationId: "cmljxwx460005qu21tzhce2zt" }),
    listOrganizations: (params: ListWorkOSOrganizationsParams) =>
        TerseAgent.executeTool<ListWorkOSOrganizationsResult>("listWorkOSOrganizations", { ...(params), integrationId: "cmljxwx460005qu21tzhce2zt" }),
    getUser: (params: GetWorkOSUserParams) =>
        TerseAgent.executeTool<GetWorkOSUserResult>("getWorkOSUser", { ...(params), integrationId: "cmljxwx460005qu21tzhce2zt" }),
}

// ── WorkOS skill ──────────────────────────────────────────────

/** WorkOS — manage users, organizations and invitations */
export function workOSSkill(): TypedSkill<never> {
    return new WorkOSOutputConfig("cmljxwx460005qu21tzhce2zt")
}