// Auto-generated by `terse generate` — do not edit manually.
// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.

import {
    SDKTrigger,
    TypedTrigger,
    WorkOSEventType,
    WorkOSInputConfig,
} from "terse-sdk"

// ── WorkOS triggers ───────────────────────────────────────────

export interface WorkOSUserCreatedTriggerPayload {
    integrationType: "workos"
    eventType: "user.created"
    eventId: string
    createdAt: string
    user: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSUserCreatedTrigger = SDKTrigger<WorkOSUserCreatedTriggerPayload>

export interface WorkOSUserUpdatedTriggerPayload {
    integrationType: "workos"
    eventType: "user.updated"
    eventId: string
    createdAt: string
    user: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSUserUpdatedTrigger = SDKTrigger<WorkOSUserUpdatedTriggerPayload>

export interface WorkOSUserDeletedTriggerPayload {
    integrationType: "workos"
    eventType: "user.deleted"
    eventId: string
    createdAt: string
    user: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSUserDeletedTrigger = SDKTrigger<WorkOSUserDeletedTriggerPayload>

export type WorkOSUserTrigger = WorkOSUserCreatedTrigger | WorkOSUserUpdatedTrigger | WorkOSUserDeletedTrigger

export interface WorkOSOrganizationMembershipCreatedTriggerPayload {
    integrationType: "workos"
    eventType: "organization_membership.created"
    eventId: string
    createdAt: string
    membership: {
        id: string
        userId: string
        organizationId: string
        role: {
            slug: string
        }
        status: string
    }
}

export type WorkOSOrganizationMembershipCreatedTrigger = SDKTrigger<WorkOSOrganizationMembershipCreatedTriggerPayload>

export interface WorkOSOrganizationMembershipUpdatedTriggerPayload {
    integrationType: "workos"
    eventType: "organization_membership.updated"
    eventId: string
    createdAt: string
    membership: {
        id: string
        userId: string
        organizationId: string
        role: {
            slug: string
        }
        status: string
    }
}

export type WorkOSOrganizationMembershipUpdatedTrigger = SDKTrigger<WorkOSOrganizationMembershipUpdatedTriggerPayload>

export interface WorkOSOrganizationMembershipDeletedTriggerPayload {
    integrationType: "workos"
    eventType: "organization_membership.deleted"
    eventId: string
    createdAt: string
    membership: {
        id: string
        userId: string
        organizationId: string
        role: {
            slug: string
        }
        status: string
    }
}

export type WorkOSOrganizationMembershipDeletedTrigger = SDKTrigger<WorkOSOrganizationMembershipDeletedTriggerPayload>

export type WorkOSMembershipTrigger = WorkOSOrganizationMembershipCreatedTrigger | WorkOSOrganizationMembershipUpdatedTrigger | WorkOSOrganizationMembershipDeletedTrigger

export interface WorkOSInvitationCreatedTriggerPayload {
    integrationType: "workos"
    eventType: "invitation.created"
    eventId: string
    createdAt: string
    invitation: {
        id: string
        email: string
        organizationId: string
        inviterEmail?: string
        state: string
        acceptedAt?: string
    }
    user?: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSInvitationCreatedTrigger = SDKTrigger<WorkOSInvitationCreatedTriggerPayload>

export interface WorkOSInvitationAcceptedTriggerPayload {
    integrationType: "workos"
    eventType: "invitation.accepted"
    eventId: string
    createdAt: string
    invitation: {
        id: string
        email: string
        organizationId: string
        inviterEmail?: string
        state: string
        acceptedAt?: string
    }
    user?: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSInvitationAcceptedTrigger = SDKTrigger<WorkOSInvitationAcceptedTriggerPayload>

export interface WorkOSInvitationResentTriggerPayload {
    integrationType: "workos"
    eventType: "invitation.resent"
    eventId: string
    createdAt: string
    invitation: {
        id: string
        email: string
        organizationId: string
        inviterEmail?: string
        state: string
        acceptedAt?: string
    }
    user?: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSInvitationResentTrigger = SDKTrigger<WorkOSInvitationResentTriggerPayload>

export interface WorkOSInvitationRevokedTriggerPayload {
    integrationType: "workos"
    eventType: "invitation.revoked"
    eventId: string
    createdAt: string
    invitation: {
        id: string
        email: string
        organizationId: string
        inviterEmail?: string
        state: string
        acceptedAt?: string
    }
    user?: {
        id: string
        email: string
        firstName?: string
        lastName?: string
        emailVerified: boolean
        profilePictureUrl?: string
    }
}

export type WorkOSInvitationRevokedTrigger = SDKTrigger<WorkOSInvitationRevokedTriggerPayload>

export type WorkOSInvitationTrigger = WorkOSInvitationCreatedTrigger | WorkOSInvitationAcceptedTrigger | WorkOSInvitationResentTrigger | WorkOSInvitationRevokedTrigger

export interface WorkOSOrganizationTriggerPayload {
    integrationType: "workos"
    eventType: "organization.created"
    eventId: string
    createdAt: string
    organization: {
        id: string
        name: string
    }
}

export type WorkOSOrganizationTrigger = SDKTrigger<WorkOSOrganizationTriggerPayload>

export type WorkOSTrigger = WorkOSUserTrigger | WorkOSMembershipTrigger | WorkOSInvitationTrigger | WorkOSOrganizationTrigger

export const workOSTriggers = {
    /** Trigger on user creation */
    onUserCreated(): TypedTrigger<WorkOSUserCreatedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.USER_CREATED])
    },
    /** Trigger on user update */
    onUserUpdated(): TypedTrigger<WorkOSUserUpdatedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.USER_UPDATED])
    },
    /** Trigger on user deletion */
    onUserDeleted(): TypedTrigger<WorkOSUserDeletedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.USER_DELETED])
    },
    /** Trigger on organization membership creation */
    onMembershipCreated(): TypedTrigger<WorkOSOrganizationMembershipCreatedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.ORGANIZATION_MEMBERSHIP_CREATED])
    },
    /** Trigger on organization membership update */
    onMembershipUpdated(): TypedTrigger<WorkOSOrganizationMembershipUpdatedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.ORGANIZATION_MEMBERSHIP_UPDATED])
    },
    /** Trigger on organization membership deletion */
    onMembershipDeleted(): TypedTrigger<WorkOSOrganizationMembershipDeletedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.ORGANIZATION_MEMBERSHIP_DELETED])
    },
    /** Trigger on any organization membership change */
    onMembershipChanged(): TypedTrigger<WorkOSMembershipTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.ORGANIZATION_MEMBERSHIP_CREATED, WorkOSEventType.ORGANIZATION_MEMBERSHIP_UPDATED, WorkOSEventType.ORGANIZATION_MEMBERSHIP_DELETED])
    },
    /** Trigger when an invitation is sent (created or resent) */
    onInvitationSent(): TypedTrigger<WorkOSInvitationTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.INVITATION_CREATED, WorkOSEventType.INVITATION_RESENT])
    },
    /** Trigger when an invitation is first created */
    onInvitationCreated(): TypedTrigger<WorkOSInvitationCreatedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.INVITATION_CREATED])
    },
    /** Trigger when an invitation is resent */
    onInvitationResent(): TypedTrigger<WorkOSInvitationResentTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.INVITATION_RESENT])
    },
    /** Trigger on invitation accepted */
    onInvitationAccepted(): TypedTrigger<WorkOSInvitationAcceptedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.INVITATION_ACCEPTED])
    },
    /** Trigger when an invitation is revoked */
    onInvitationRevoked(): TypedTrigger<WorkOSInvitationRevokedTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.INVITATION_REVOKED])
    },
    /** Trigger on organization creation */
    onOrganizationCreated(): TypedTrigger<WorkOSOrganizationTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", [WorkOSEventType.ORGANIZATION_CREATED])
    },
    /** Trigger on specific WorkOS event types */
    trigger(opts?: { eventTypes?: WorkOSEventType[] }): TypedTrigger<WorkOSTrigger | WorkOSUserTrigger | WorkOSMembershipTrigger | WorkOSInvitationTrigger | WorkOSOrganizationTrigger> {
        return new WorkOSInputConfig("cmljxwx460005qu21tzhce2zt", opts?.eventTypes)
    },
}