// Auto-generated by `terse generate` — do not edit manually.
// Re-run `terse generate` to update.
//
// The integrations currently available in Terse: apollo, attio, cron_job, datadog, github, gmail, hey_reach, launchdarkly, linear, notion, posthog, resend, slack, snowflake, webmonitor, workos.
// Connect one with `terse integrate connect <type>`; list its tools with `terse integrate tool <type> --json`.
//
// This file is the only import surface — everything generated is re-exported here:
//   import { Triggers, Skills, toolbox, ... } from "./terse.generated"
// The terse.generated/ folder holds the per-integration declarations. Read only the files you need:
//   <integration>.triggers.ts — trigger factories (Triggers.<integration>.*) and their payload types
//   <integration>.tools.ts    — typed tool methods (toolbox.<integration>.*), their Params/Result types, pinned resources, and skills
//   terse.triggers.ts / terse.tools.ts — built-in triggers (schedule, webhook, webMonitor), built-in tools, and the web/imageEdit/memory skills
// Below the index, this file only composes: the Triggers/Skills/toolbox aggregates re-export what the folder defines.

// ── Platform primitives (from "terse-sdk") ────────────────────
//
// Everything below ships with the terse-sdk package. This summary is the
// reference for job code — do not read the terse-sdk dist to rediscover it.
//
// Defining jobs:
//   createJob({ name, triggers: [...], states?, filter?, onTrigger, durable? })
//     Registers a workflow. `filter` and `onTrigger` receive (event, state);
//     `filter` returns boolean to decide whether the run proceeds.
//   Every trigger event has event.formatForAgentRunner(): string — the
//     canonical way to inline the triggering event into an agent prompt.
//
// Agentic execution:
//   generateText({ prompt, skills: [...], toolApprovals?, outputSchema? })
//     One-shot agent run. Returns Promise<string>, or Promise<z.infer<schema>>
//     when `outputSchema` (a zod schema) is given. Skills come from the
//     generated `Skills` export below; the agent can only touch integrations
//     whose skills are passed.
//   TerseAgent.create({ prompt, skills, toolApprovals? })
//     Streaming variant: `for await (const result of agent.run(message))`.
//     `agent.tools` is typed to the generated tools of the passed skills.
//
// Per-job state (typed key/value store):
//   states: [{ key: "runCount", value: z.number().default(0) }]
//   then `await state.get("runCount")` / `await state.set("runCount", n)`
//   in `filter`/`onTrigger`. Keys and value types come from the declaration.
//
// Durability (all of these require `durable: true` on the job):
//   step(client.method(args))   Journals a single wrapped call; arguments and
//                               result must be serializable.
//   jobStep({ run, input?, inputSchema?, outputSchema? })
//                               Journals a code block as one step.
//   sleep("2h" | ms | Date)     Suspends the run; resumes after the duration.
//   await log(...args)          Replay-safe console.log (prints exactly once).
//   waitForInput({ via: slack({ channel: SlackChannel.X.channelId }), prompt, options })
//                               Suspends until a human answers; resolves to
//                               { choice, text?, respondent }. `options` is
//                               [{ id, label, description?, freeText? }].
//
// Secrets:
//   Write with `terse secrets add`; read in job code via process.env.MY_SECRET.
//   There is no value-returning secrets API — env vars are the read side.
//
// Index of the generated files. Line numbers are exact as of the last `terse generate`;
// if a formatter has touched a file since, search for the symbol name instead.
//
// terse.generated/common.ts
//   L6  type RunHistoryAction
// terse.generated/terse.tools.ts
//   L222  toolbox.terse.memory()  (params L18)
//   L224  toolbox.terse.webSearch()  (params L104)
//   L226  toolbox.terse.extractPage()  (params L149)
//   L228  toolbox.terse.research()  (params L171)
//   L230  toolbox.terse.editImage()  (params L197)
//   L249  function webSkill()
//   L254  function imageEditSkill()
//   L259  function memorySkill()
// terse.generated/terse.triggers.ts
//   L64  Triggers.schedule.cron()
//   L71  Triggers.webhook.onRequest()
//   L81  Triggers.webMonitor.onEvent()
// terse.generated/github.tools.ts
//   L9    class GithubOwner
//   L15   class Repos
//   L559  toolbox.github.searchCode()  (params L119)
//   L578  toolbox.github.grepCode()  (params L193)
//   L586  toolbox.github.readFile()  (params L253)
//   L594  toolbox.github.listDirectory()  (params L294)
//   L603  toolbox.github.listPullRequests()  (params L349)
//   L612  toolbox.github.listCommits()  (params L420)
//   L629  toolbox.github.summarizePRDiff()  (params L494)
//   L652  function githubSkill()
// terse.generated/github.triggers.ts
//   L315  Triggers.github.onPush()
//   L319  Triggers.github.onPROpened()
//   L323  Triggers.github.onPRMerged()
//   L327  Triggers.github.onPRClosed()
//   L331  Triggers.github.onPRSynchronized()
//   L335  Triggers.github.onPR()
//   L339  Triggers.github.onIssueComment()
//   L343  Triggers.github.trigger()
// terse.generated/resend.tools.ts
//   L9    type ResendTemplateVariableValue
//   L11   type GeneratedResendTemplate
//   L51   type ResendTemplate
//   L108  toolbox.resend.sendTemplate()  (params L88)
//   L119  function resendSkill()
// terse.generated/slack.tools.ts
//   L9    class SlackChannel
//   L16   class SlackUser
//   L159  toolbox.slack.sendMessage()  (params L29)
//   L162  toolbox.slack.listUsers()  (params L66)
//   L166  toolbox.slack.listChannels()  (params L89)
//   L170  toolbox.slack.readConversation()  (params L125)
//   L187  function slackSkill()
// terse.generated/slack.triggers.ts
//   L89   Triggers.slack.onMessage()
//   L93   Triggers.slack.onDm()
//   L97   Triggers.slack.onAppMention()
//   L101  Triggers.slack.onReactionAdded()
//   L105  Triggers.slack.trigger()
// terse.generated/posthog.tools.ts
//   L9    class PosthogProject
//   L22   type PosthogEventName
//   L402  toolbox.posthog.searchLogs()  (params L52)
//   L404  toolbox.posthog.searchSessions()  (params L123)
//   L406  toolbox.posthog.getSessionEvents()  (params L203)
//   L408  toolbox.posthog.listEventNames()  (params L266)
//   L410  toolbox.posthog.searchEvents()  (params L326)
//   L429  function posthogSkill()

import { TerseAgent } from "terse-sdk"
import { terseTools, webSkill, imageEditSkill, memorySkill } from "./terse.generated/terse.tools.js"
import type { TerseGeneratedTools } from "./terse.generated/terse.tools.js"
import { scheduleTriggers, webhookTriggers, webMonitorTriggers } from "./terse.generated/terse.triggers.js"
import { githubTools, githubSkill } from "./terse.generated/github.tools.js"
import type { GithubGeneratedTools } from "./terse.generated/github.tools.js"
import { githubTriggers } from "./terse.generated/github.triggers.js"
import { resendTools, resendSkill } from "./terse.generated/resend.tools.js"
import type { ResendGeneratedTools } from "./terse.generated/resend.tools.js"
import { slackTools, slackSkill } from "./terse.generated/slack.tools.js"
import type { SlackGeneratedTools } from "./terse.generated/slack.tools.js"
import { slackTriggers } from "./terse.generated/slack.triggers.js"
import { posthogTools, posthogSkill } from "./terse.generated/posthog.tools.js"
import type { PosthogGeneratedTools } from "./terse.generated/posthog.tools.js"

export * from "./terse.generated/common.js"
export * from "./terse.generated/terse.tools.js"
export * from "./terse.generated/terse.triggers.js"
export * from "./terse.generated/github.tools.js"
export * from "./terse.generated/github.triggers.js"
export * from "./terse.generated/resend.tools.js"
export * from "./terse.generated/slack.tools.js"
export * from "./terse.generated/slack.triggers.js"
export * from "./terse.generated/posthog.tools.js"

// ── Triggers ──────────────────────────────────────────────────

/**
 * Triggers available in your workspace.
 *
 * Type `Triggers.` in your editor to see every connected integration with triggers.
 * Use these in `createJob({ triggers: [...] })`.
 */
export const Triggers = {
    github: githubTriggers,
    slack: slackTriggers,
    /** Built-in: run on a cron schedule */
    schedule: scheduleTriggers,
    /** Built-in: trigger via an external HTTP request to a generated URL */
    webhook: webhookTriggers,
    /** Built-in: trigger when a query against the live web matches a schema */
    webMonitor: webMonitorTriggers,
}

// ── Skills ────────────────────────────────────────────────────

/**
 * Skills available in your workspace.
 *
 * Type `Skills.` in your editor to see every connected integration's skill at a glance.
 * Use these in `generateText({ skills: [...] })` (or `TerseAgent.create({ skills: [...] })`).
 */
export const Skills = {
    /** GitHub — read code and pull requests from the given repositories */
    github: githubSkill,
    /** Resend — send transactional email using generated published templates */
    resend: resendSkill,
    /** Slack — send messages and manage threads in a specific channel */
    slack: slackSkill,
    /** Web — built-in web search, page extraction, and multi-source research */
    web: webSkill,
    /** ImageEdit — edit and generate images */
    imageEdit: imageEditSkill,
    /** Memory — built-in persistent memory scoped to this job, surviving across runs */
    memory: memorySkill,
    /** PostHog — query analytics for a specific project */
    posthog: posthogSkill,
}

// ── Typed Tools ───────────────────────────────────────────────

export type GeneratedTools = {
    github: GithubGeneratedTools
    posthog: PosthogGeneratedTools
    resend: ResendGeneratedTools
    slack: SlackGeneratedTools
    terse: TerseGeneratedTools
}

declare module "terse-sdk" {
    interface TerseAgent {
        readonly tools: GeneratedTools
    }
}

function createTools(agent: TerseAgent): GeneratedTools {
    const allowed: Set<string> = new Set(agent.skills.map(config => config.integrationType))
    return {
        ...(allowed.has("github") ? { github: githubTools } : {}),
        ...(allowed.has("posthog") ? { posthog: posthogTools } : {}),
        ...(allowed.has("resend") ? { resend: resendTools } : {}),
        ...(allowed.has("slack") ? { slack: slackTools } : {}),
        ...(allowed.has("terse") ? { terse: terseTools } : {}),
    } as GeneratedTools
}

;(globalThis as any).__terse_createTools = createTools

/**
 * Deterministic tool calls without an agent.
 *
 * `toolbox` exposes every connected integration tool as a typed function. Unlike
 * `agent.tools`, it does not require constructing a `TerseAgent` and is not
 * filtered by `skills`. Use it when you know exactly which tool to call and
 * don't need an LLM in the loop.
 *
 * @example
 * ```ts
 * import { toolbox } from "./terse.generated"
 * await toolbox.slack.sendMessage({ channelId: "...", message: "hi" })
 * ```
 */
export const toolbox: GeneratedTools = {
    github: githubTools,
    posthog: posthogTools,
    resend: resendTools,
    slack: slackTools,
    terse: terseTools,
}